### ISSUE TITLE
Document adding baselines

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#1000]
### Describe what the documentation is missing.

The are a number of Flower Baselines, but there's no documentation on how to add new baselines.

### Suggest your improvement.

Add documentation that describes exactly how new baselines should be added. Questions include:

- Where does the Python code go?
- What should directories/files be named?
- Does the new baseline need to be added to any script(s)?
- Does the new baseline need to be added to any docs?

**Comment by harshlancer** [comment]
@danieljanes If nonone is assigned I'd like to work on this issue.
