### ISSUE TITLE
Did flower support PSI (Private Set Intersection) ?

### ISSUE THREAD

**Issue by kaiwang0112006** [adap/flower#1002]
### What is your question?

 I'm wondering did  flower support PSI, which is step for vertical federated learning.  It would be nice to see an example of vertical federated learning also.

**Comment by hei411** [comment]
Hi @kaiwang0112006!

Could you kindly provide us with more context for what you need PSI for? 
There are various protocols to achieve PSI, so it would be ideal if you could tell us how PSI is used for your experiments, together with the details of your experiment, e.g. how many clients, will there be a trusted third party, is there a particular protocol you want to execute?

e.g. Tensorflow encrypted supports the use of POND, a secret sharing protocol for two parties that require a trusted third party. https://alibaba-gemini-lab.github.io/docs/blog/tfe/

**Comment by kaiwang0112006** [comment]
> Hi @kaiwang0112006!
> 
> Could you kindly provide us with more context for what you need PSI for? There are various protocols to achieve PSI, so it would be ideal if you could tell us how PSI is used for your experiments, together with the details of your experiment, e.g. how many clients, will there be a trusted third party, is there a particular protocol you want to execute?
> 
> e.g. Tensorflow encrypted supports the use of POND, a secret sharing protocol for two parties that require a trusted third party. https://alibaba-gemini-lab.github.io/docs/blog/tfe/

Hi, @hei411 , 

First I have to clarify that I'm not an export on private computing, so I cannot provide the specific protocol to achieve PSI, or I should say any protocol is fine. To me, PSI is just a secure way to "merge" dataset from different hosts for vertical federated learning. The details of my experiment is that, host A have a dataset of 1100 samples containing sample id, feature1-10, and host B have a dataset of 1000 samples containing  sample id, feature9-20 and label (training target). For centeral machine learning, They just merge their dataset to a dataset of 900 samples with  feature1-20 and label and train a model. But to do  vertical federated learning, they have to PSI to find their consistent sample id. Like [this img](https://fintep.com/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSnJkbUZ5YVdGdWRITXZlVEJoZFhBeWVtSTBZV3RwTnpCaFpHeG5aWFZsYkhsMFoyWjZPUzgzTnpoalpqYzNPVEJpWVdKbE9XVTRNalUyT0dOa1lXUXhObVZrT1RnNU5HRTJNakU1WlRoaVpqZzJZamhqWVdOak56a3dNVEE0WkRVMk5EbGtOVE5qQmpvR1JWUTZFR1JwYzNCdmMybDBhVzl1U1NKRmFXNXNhVzVsT3lCbWFXeGxibUZ0WlQwaVNXMWhaMlZ1SURJdWNHNW5JanNnWm1sc1pXNWhiV1VxUFZWVVJpMDRKeWRKYldGblpXNGxNakF5TG5CdVp3WTdCbFE2RVdOdmJuUmxiblJmZEhsd1pVa2lEbWx0WVdkbEwzQnVad1k3QmxRPSIsImV4cCI6IjIwMjItMDEtMjFUMDc6MTk6MDYuMDYzWiIsInB1ciI6ImJsb2Jfa2V5In19--983a5964cbe9a1e36015737b2fcacff2c8b7afd7/Imagen%202.png?content_type=image%2Fpng&disposition=inline%3B+filename%3D%22Imagen+2.png%22%3B+filename%2A%3DUTF-8%27%27Imagen%25202.png)

A trusted third party is not necessary. I think I can change my questiong to "Did flower support vertical federated learning and is there an example?". But it would be a duplicate question to [issue 706](https://github.com/adap/flower/issues/706)

**Comment by hei411** [comment]
If I am not mistaken, a PSI protocol is an extra stage before a normal federated learning protocol.
Currently, the API of Flower allows you to modify the federated learning algorithm, but it is unable to add an extra arbitrary stage.
I heard the developers are considering the possibility of providing an API that enables users to extend any FL protocol with extra stages, e.g. PSI.

**Comment by BalticBytes** [comment]
Any updates on Private Set Intersection support for FLWR?

**Comment by WilliamLindskog** [comment]
Hi @kaiwang0112006, 

Thanks for raising this. Would current [VFL example](https://github.com/adap/flower/tree/main/examples/vertical-fl) serve your purpose?

**Comment by kaiwang0112006** [comment]
> Hi @kaiwang0112006,
> 
> Thanks for raising this. Would current [VFL example](https://github.com/adap/flower/tree/main/examples/vertical-fl) serve your purpose?

I quickly walked through the example and correct me if I'm wrong: "the dataset for different client should have the same set of sample id, wright?"

PSI [(Private Set Intersection) ?] means different client has different set of sample id, but they have intersections. For VFL, the first step is to find the  intersections (For example, client 1 have user A,B,C, client 2 have user A,C,D. For VFL, the intersections is A,C). Further more，“Private” means there is some secure setting to make sure sample id safty. But I'm not an expert on that.

The issue is two years ago. I used FATE for VFL with PSI back then. But flower is a more open framework and I like that. Maybe I will take a deep look on this issue further. LOL

But this issue can close for now.
