### ISSUE TITLE
ClientManager not being used in `initialize_parameters`

### ISSUE THREAD

**Issue by pedropgusmao** [adap/flower#1009]
`ClientManager` not being used in function. 
Should we consider the case where we call a client through the ClientManager and get their weights in case no `initial weights` have been set? 
https://github.com/adap/flower/blob/7c55e976f27cb66e74542d61eab31c473241dae0/src/py/flwr/server/strategy/fedavg.py#L159

**Comment by WilliamLindskog** [comment]
Closing this as `ClientManger` are used for certain baselines in `initialize_parameters` method e.g. HeteroFL.
