### ISSUE TITLE
Upgrade Ray to the latest stable version

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#1016]
### Describe the type of feature and its functionality.

The `ray` dependency is currently pinned to `==1.6` because `ray==1.7.0` introduced backwards-incompatible changes which broke the Virtual Client Engine. The current Ray release is 1.9, so Flower should (a) update to the latest version and (b) declare the dependency using `^` so that users can use Flower with future `1.x` Ray releases (`1.10` and above).

### Describe step by step what files and adjustments are you planning to include.

- Update the Ray dependency to the latest version
- Update `RayClientProxy` to be compatible with the latest Ray release
- Declare the dependency as `^`
- Test the change thoroughly

**Comment by jafermarq** [comment]
I was able to run the `simulation_pytorch` example with PyTorch 1.8.2 LTS, Ray 1.9.2 (the latests) and the latest flwr. I had no errors. I also run other of my projects that make use of the `RayClientProxy` without issues. 

Maybe the only thing required is to raise the Ray version in the .toml?

**Comment by danieljanes** [comment]
Thanks for giving it a shot @jafermarq , let's declare the Ray dependency with `^1.9.2` then.

**Comment by danieljanes** [comment]
Moved to Ray ~1.13 with Flower 1.0
