### ISSUE TITLE
Secure gRPC: Logging still reporing insecure connection

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#1023]
### Discussed in https://github.com/adap/flower/discussions/1020

<div type='discussions-op-text'>

<sup>Originally posted by **NathanSchot** January 21, 2022</sup>
Hey,

My team and I have enjoyed working with flower for a few months now. We are very excited with the recent implementation of secure gRPC connections, as security is one of our main focus points.

I realise I may be a bit early (and potentially nitpicky) with this question as secure gRPC is still under construction, but we noticed that the logging of the FL process does not take the existence of root certificates in account, therefore printing incorrect information. The two lines where this happens are:

https://github.com/adap/flower/blob/cb66854dcbf2e0c5bf14ee48149053a84be8a3be/src/py/flwr/client/app.py#L89
and 
https://github.com/adap/flower/blob/cb66854dcbf2e0c5bf14ee48149053a84be8a3be/src/py/flwr/client/grpc_client/connection.py#L114

Thanks in advance.</div>

**Comment by danieljanes** [comment]
Thanks for the report @NathanSchot, appreciated! CC @tanertopal

**Comment by tanertopal** [comment]
@NathanSchot much appreciated! We will update that asap!
