### ISSUE TITLE
Shouldn't operations on shared dictionary `clients` be synchronized in `SimpleClientManager.register` and `SimpleClientManager.unregister`?

### ISSUE THREAD

**Issue by FractalGiraffe** [adap/flower#1037]
### What is your question?

Shouldn't  the lock, associated with `_cv`, be used to synchronize the operations on the shared dictionary in both `SimpleClientManager.register` and `SimpleClientManager.unregister`? Although [CPython currently makes critical built-in types implicitly thread safe](https://docs.python.org/3/glossary.html#term-global-interpreter-lock), Google's style guide for open source projects [advises against relying upon atomicity of built-in types](https://github.com/google/styleguide/blob/91d6e367e384b0d8aaaf7ce95029514fcdf38651/pyguide.md#218-threading).
https://github.com/adap/flower/blob/86af2da1435da5826a5bfc8e9236b46d41687c29/src/py/flwr/server/client_manager.py#L99-L101
https://github.com/adap/flower/blob/86af2da1435da5826a5bfc8e9236b46d41687c29/src/py/flwr/server/client_manager.py#L111-L114

**Comment by tanertopal** [comment]
@FractalGiraffe was the question resolved? Feel free to ping me in Slack if not.
