### ISSUE TITLE
WEAKLY REFERENCED OBJECT NO LONGER EXISTS

### ISSUE THREAD

**Issue by adaptcvdm** [adap/flower#1047]
### What is your question?

Hello, first of all thank you for making such a wonderful library.
I recently updated my python environment to python 3.9 and I am facing this issue where either one of the clients or the server gives this error weakly referenced object no longer exists. But this error is very random, sometimes it occurs and sometimes the run is complete without any errors.

I have implemented my code using pytorch_lightning.

Thanks in advance.

**Comment by sisco0** [comment]
Could you kindly share the error line? as it contains module information. Thank you.

**Comment by adaptcvdm** [comment]
![image](https://user-images.githubusercontent.com/88665972/153340511-3fa9bdb9-87ef-43c2-8987-784fc0083854.png)

**Comment by adaptcvdm** [comment]
![image](https://user-images.githubusercontent.com/88665972/153341206-8650a5cb-e194-4c23-9952-b99bc1aff3c0.png)

**Comment by tanertopal** [comment]
@adaptcvdm unfortunately its hard to debug using this.  Could you share a repository?

**Comment by WilliamLindskog** [comment]
@adaptcvdm is this still a problem you are encountering?

**Comment by WilliamLindskog** [comment]
Closing this as older version is not longer supported and [current example](https://github.com/adap/flower/tree/7c55e976f27cb66e74542d61eab31c473241dae0/examples/quickstart_pytorch_lightning) runs.
