### ISSUE TITLE
Flower with virtual machine not working

### ISSUE THREAD

**Issue by IceQueen1996** [adap/flower#1052]
### What is your question?

 Hi, 
I relatively new to the new FL thing. I wanted to try out some of your qickstart tutorials. I'm using the following setup:
Host machine: Windows 10
Code development: Ubuntu Virtual Machine

So far i had never problems with my VM, but apparently now is the first time i can't solve the prblem on my own. When trying for example the tensorflow quickstart tutorial in windows, everything works fine, but when trying out the same code within the VM then i recieve the following error from client side: grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
```
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1644308324.902899684","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1644308324.902877086","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
```

I already switched out "localhost" and "[::]" on client and server side to different things like both on localhost, both on [::] or "0.0.0.0", but nothing works. 

Can someone help me with this special setting of VM and using gRCP protocol?

**Comment by Saugatkafley** [comment]
I am also facing Same issues with flower in Colab ,

**Comment by prathapkumarbaratam** [comment]
@IceQueen1996  , @Saugatkafley  use localhost in place of  [::]

**Comment by IceQueen1996** [comment]
That does not help unfortunately.
A workaround which i found is the following (at least it worked for me, i cannot say how it is in google colab)
Workaround: Add chanel option about http proxy to insecure_grcp chanel with this option:
  1. Find file within your python environment: flwr/client/grpc_client/connection.py
  2. Add "("grpc.enable_http_proxy", 0)" as additional option to line 44:
    Change
        ```
        channel = grpc.insecure_channel(
            server_address,
            options=[
                ("grpc.max_send_message_length", max_message_length),
                ("grpc.max_receive_message_length", max_message_length),
            ],
        )
        ```
      to
          ```
          channel = grpc.insecure_channel(
              server_address,
              options=[
                  ("grpc.max_send_message_length", max_message_length),
                  ("grpc.max_receive_message_length", max_message_length),
                  ("grpc.enable_http_proxy", 0)
              ],
          )
          ```
