### ISSUE TITLE
Regarding shared layer Customization & Federated Transfer Learning

### ISSUE THREAD

**Issue by arghasen10** [adap/flower#1059]
### What is your question?

Although I am familiar with federated learning, I am not very much accustomed to the flower framework. 

My question is can we customize the number of shared layers? Suppose my model consists of 5 layers. I want to share weights for the initial four layers but not share the last layer. Can we do that??

And suppose I want to initialize the server with some proxy data. That will initialize the server model; then, the server will pass the weights to the local clients for model initialization. Let me know if we can do that with the current implementation. If not, then let me know from where should I start?

**Comment by WilliamLindskog** [comment]
Hi, 

The FedPer baseline seems relevant for this case and is currently available: https://github.com/adap/flower/tree/968fc774156e3371ad0c58c5f2638c04e3ab0144/baselines/fedper

For the server, we can initialize it using weights trained on some proxy data if this is introduced in the first round. 

Closing this comment.
