### ISSUE TITLE
About one client distributed training on multiple machine support and different deep learning framework support

### ISSUE THREAD

**Issue by FourWinds021** [adap/flower#1074]
### What is your question?

I have two question:
1. Does a client support distributed training on multiple machine, such as two Nvidia-v100 machine?
2. Is there tutorials that support the new deep learning framework?

**Comment by WilliamLindskog** [comment]
Hi, 

we support deployment across various devices and examples for ML frameworks can be found here: https://github.com/adap/flower/tree/968fc774156e3371ad0c58c5f2638c04e3ab0144/examples

Closing this issue.
