### ISSUE TITLE
Unify documentation to use `-` instead of `_`

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#1083]
### Describe what the documentation is missing.

Some docs use `_` as the separator and some use `-`, for example:
- `https://flower.dev/docs/example_walkthrough_pytorch_mnist.html`
- `https://flower.dev/docs/example-mxnet-walk-through.html`

This is inconsistent.

### Suggest your improvement.

We want to unify all docs to use `-` ("minus") as the only separator. This involves the following TODO's:

- [ ] Rename all docs that use `_` (and replace it with `-`)
- [ ] For each renamed doc, configure a redirect from the old naming (e.g., `quickstart_pytorch`) to the new page (e.g., `quickstart-pytorch`) using, for example, https://documatt.gitlab.io/sphinx-reredirects/index.html
- [ ] Update all references in the docs with the new naming (e.g., in `index.rst`)
- [ ] Update all other references with the new naming (e.g., README.md, code examples, website, ...)

Last, but not least, this should all be done in a single PR. We should not split, for example, the renaming of a page and the configuration of a redirect into two PRs because it would lead to a deployed version of the docs where users would see a 404 page when they use a link that points to the old naming.

**Comment by danieljanes** [comment]
@RISHIKESHAVAN that would be awesome, please go ahead!

**Comment by RISHIKESHAVAN** [comment]
Hi @danieljanes, I have created a PR for this. Please do take a look into it whenver possible.
