### ISSUE TITLE
Need FedProx,FedNOVA implementation using Flower

### ISSUE THREAD

**Issue by prathapkumarbaratam** [adap/flower#1087]
### What is your question?

hi all, I want to use Strategies like FedPROX,FEDNOVA using Flower.

Thanks and Regards,
Prathap Kumar

**Comment by sisco0** [comment]
The _FedProx_ baseline should be implemented as pointed out in https://flower.dev/docs/using-baselines.html. However, I could not find the cited folder `flower/baselines/flwr_baselines/publications/fedprox/system_heterogeneity` in any branch.
However, I could find the following reference when running `git log -i -G "FedProx" --all -r -p .`:
`src/flower/strategy/fedprox.py`

The cited file was included before in the `fedprox` branch, which is currently deleted as you could see in https://github.com/adap/flower/commit/06fddf9c details. The information we could grab is had from https://github.com/adap/flower/blob/06fddf9c7144efaefcb2b02127bd760400c449de/src/flwr/strategy/fedprox.py.

You could base your implementation in the referenced file if no further information is given in this thread.

**Comment by prathapkumarbaratam** [comment]
hi @sisco0 , Can I able to use this Fedprox code for my experiments?

**Comment by jafermarq** [comment]
Hey @prathapkumarbaratam , you can find both `FedProx` and `FedNova` in the `baselines/` directory:
* `FedNova`: https://github.com/adap/flower/tree/main/baselines/fednova
* `FedProx`: https://github.com/adap/flower/tree/main/baselines/fedprox

Many more baselines are easily accessible from our docs: https://flower.dev/docs/baselines/
