### ISSUE TITLE
SSL-enabled Server and Client Example

### ISSUE THREAD

**Issue by sandracl72** [adap/flower#1139]
### Describe what the documentation is missing.

[Guide: SSL-enabled Server and Client](https://flower.dev/docs/ssl-enabled-connections.html) refers to the example  [advanced_tensorflow](https://github.com/adap/flower/tree/main/examples/advanced_tensorflow) for SSL-enabled secure Flower server: 

"A complete code example demonstrating a secure connection can be found [here](https://github.com/adap/flower/tree/main/examples/advanced_tensorflow)."

However, this example does not contain such a feature.

### Suggest your improvement.

Complete example with SSL-enabled connections or refer to the correct example.

**Comment by danieljanes** [comment]
Good catch @sandracl72, for some reason the PR hasn't been merged yet: https://github.com/adap/flower/pull/847 (it's almost ready though, CC @tanertopal)

**Comment by chongshenng** [comment]
Hi @danieljanes / @tanertopal, just wondering about the status of the PR and whether it's merge-ready? I'm interested in this documentation on the SSL-enabling. Thanks!

**Comment by danieljanes** [comment]
Thanks for reaching out @chongshenng, the PR has been merged a while ago and there's also documentation on flower.dev:
- `advanced_tensorflow` code example demonstrating SSL-enabled connections: https://github.com/adap/flower/tree/main/examples/advanced_tensorflow
- Docs: https://flower.dev/docs/ssl-enabled-connections.html
