### ISSUE TITLE
Add support for timeout

### ISSUE THREAD

**Issue by kiedanski** [adap/flower#1172]
### Describe the type of feature and its functionality.

This should allow ignoring clients that take more than X seconds to finish.

### Describe step by step what files and adjustments are you planning to include.

This should be as easy as adding a parameter that gets passed in this line: https://github.com/adap/flower/blob/4c4d6458661988f9e1e5bbcf9118a4cf7989a02e/src/py/flwr/server/server.py#L304

**Comment by WilliamLindskog** [comment]
Hi,

Thanks for raising this. Current version of flwr supports this so I will close.
