### ISSUE TITLE
Potential datatype mismatch in simulation_pytorch

### ISSUE THREAD

**Issue by VasundharaAgarwal** [adap/flower#1176]
### What is your question?

Hi,

I noticed that in the simulation_pytorch example, we pass a function with return type `CifarRayClient` as the `client_fn` parameter in the call to `start_simulation` [here](https://github.com/adap/flower/blob/main/examples/simulation_pytorch/main.py#L189). This seems at odds with the definition of `start_simulation` [here](https://github.com/adap/flower/blob/4de97cfada78e28ac4f3f1a00ce66da693d8f5b4/src/py/flwr/simulation/app.py#L57) because its `client_fn` parameter expects a function with return type `flwr.client.Client`.

I understand that this would be fine if `flwr.client.NumPyClient`, which `CifarRayClient` subclasses, was itself a subclass of `flwr.client.Client`, but [this](https://github.com/adap/flower/blob/78409ffe5947fd670fcc116d962f229b7355e9d1/src/py/flwr/client/numpy_client.py#L69) makes me believe it is not. Alternatively, had we been wrapping the returned `CifarRayClient` with `NumPyClientWrapper` [here,](https://github.com/adap/flower/blob/main/examples/simulation_pytorch/main.py#L182), it would also have made sense.

The example does seem to execute without error, but I am not sure I understand why -- I would have expected a datatype mismatch error. I was hoping you could help me figure out where my misunderstanding lies.

**Comment by adam-narozniak** [comment]
Hi!
Thanks for pointing this out. We will fix it in the upcomming release by changing it to the ClientLike type.
The reason it worked is that the ClientFunction was used in the RayClientProxy, which in `_create_client` used `to_client` method that looks like that
https://github.com/adap/flower/blob/57a4365f24727ecf7f0887bdaab9438c4b0142c8/src/py/flwr/client/app.py#L249-L253

**Comment by tanertopal** [comment]
I am closing this as @adam-narozniak replied and the PR is merged. @VasundharaAgarwal feel free to re-open the issue if you have more questions/comments.
