### ISSUE TITLE
Running server and clients in GNU Screen terminals works unpredictably

### ISSUE THREAD

**Issue by Spraitazz** [adap/flower#1182]
### Describe the bug

Hi, I am running flwr 0.18.0 from pip on Ubuntu 20.04.4 LTS. I can sometimes get flwr to work, running the server on one GNU Screen terminal and 3 clients on other 3 terminals. 

I am using the basic setup, running the server with 
fl.server.start_server(config={"num_rounds": 100}

and the clients with
fl.client.start_numpy_client("[::]:8080", client=cl)

if I kill the server (ctrl + c), not all of the clients return the "status = StatusCode.UNAVAILABLE details = "Socket closed" message.

This is an issue only with GNU Screen, it does not happen using normally launched separate terminals.

### Steps/Code to Reproduce

I am using the basic setup, running the server with 
fl.server.start_server(config={"num_rounds": 100}

and the clients with
fl.client.start_numpy_client("[::]:8080", client=cl)

### Expected Results

Not sure if there should be a difference between using GNU Screen and not.

### Actual Results

FL does not start, not enough clients (not all 3) connect succesfully, even though the clients ALL log the following:

INFO flower 2022-04-13 15:02:46,474 | connection.py:102 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flower 2022-04-13 15:02:46,475 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flower 2022-04-13 15:02:46,475 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flower 2022-04-13 15:02:46,476 | connection.py:39 | ChannelConnectivity.READY

**Comment by WilliamLindskog** [comment]
@Spraitazz is this still an issue that you are encountering?

**Comment by WilliamLindskog** [comment]
Closing this issue as the metioned flwr version is no longer supported.
