### ISSUE TITLE
How to measure Energy Consumption(kJ) for Android devices in Federated Training? 

### ISSUE THREAD

**Issue by pratik98** [adap/flower#1203]
### What is your question?

In one of the flower summit [talks ](https://www.youtube.com/watch?v=QJEX5c0y1I8), @akhilmathurs presents a slide which has details about energy consumption (kJ) of Android devices, I have gone through the Android Example source code but could not figure out how to get these energy consumption metrics. Is there any specific android app or utility which is being used to measure this when device is in training?

**Comment by akhilmathurs** [comment]
@pratik98, sorry for the late reply. The energy consumption was measured with a Monsoon Power Monitor. If you prefer to do it in software, please look at the BatteryManager API https://developer.android.com/reference/android/os/BatteryManager. 

For the Nvidia Jetson devices, you can refer to the power monitoring code here: https://embeddeddl.wordpress.com/2018/04/25/convenient-power-measurements-on-the-jetson-tx2-tegra-x2-board/.  We adapted the same code and integrated into our FL pipeline.
