### ISSUE TITLE
Increasing number of clients during FL simulation 

### ISSUE THREAD

**Issue by ceylanmesut** [adap/flower#1207]
### What is your question?

Hi everyone,

I am wondering whether including more clients on top of the initial client amount during FL simulation is possible with the Flower framework. Currently, I initialize FL with 5 clients and I would like to add another 5 clients in the middle of total communication rounds. 

It would be great to receive your comments on this case.
Thanks in advance!

**Comment by WilliamLindskog** [comment]
Hi @ceylanmesut 

Thanks for raising this. Are you still experiencing this issue?

**Comment by WilliamLindskog** [comment]
With new flwr versions you can implement the client sample logic, and modify it to include additional clients starting from a specific round. This can be done through using a custom `ClientManager` or adapt the strategy to handle dynamic addition of clients.

Closing this issue for now.
