### ISSUE TITLE
SIGABRT issue

### ISSUE THREAD

**Issue by ThinhOn** [adap/flower#1211]
### What is your question?

I was trying to train a model with varying number of clients in each round. I got this error, I'm not an expert at C++ so I am not sure what that is. Could you please take a look and help me figure out the issues? I greatly appreciate it.

### Error snippet:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** SIGABRT received at time=1652240059 on cpu 7 ***
PC: @     0x2b9415ecb387  (unknown)  raise
    @     0x2b9415c88630  (unknown)  (unknown)
[2022-05-10 23:34:19,891 E 36453 56643] logging.cc:317: *** SIGABRT received at time=1652240059 on cpu 7 ***
[2022-05-10 23:34:19,891 E 36453 56643] logging.cc:317: PC: @     0x2b9415ecb387  (unknown)  raise
[2022-05-10 23:34:19,891 E 36453 56643] logging.cc:317:     @     0x2b9415c88630  (unknown)  (unknown)
Aborted

**Comment by WilliamLindskog** [comment]
Hi @ThinhOn 

Thanks for raising this. Is this an issue that you are still experiencing? If so, could you provide more details on you implementation?

**Comment by WilliamLindskog** [comment]
Hi again, 

I'm closing this issue as the flwr version used is outdated and the new example can be used to configure the client logic using custom strategies and `ClientManager` logic implementation.
