### ISSUE TITLE
gRPC connection handling 

### ISSUE THREAD

**Issue by jimazikerlan** [adap/flower#1234]
### What is your question?

I am trying to implement a real use case and I have been making some trials. Once the training process starts, if a new client asks for training to the server, the server collapses and stops the training without finishing the process. Is there any way of handling this? I found the following in the GRPC documentation:
[https://github.com/grpc/grpc/tree/master/examples/python/async_streaming](https://github.com/grpc/grpc/tree/master/examples/python/async_streaming)

**Comment by danieljanes** [comment]
Thanks for reaching out @jimazikerlan, what you're describing sounds like a bug. Could you provide a minimal code example that we can use to reproduce the issue you're describing?

Clients are able to join and leave the server at any point in time. If a new client joins, it'll have to wait until the current round is finished, and it might then be selected to receive a task during the next round of training or evaluation.

**Comment by WilliamLindskog** [comment]
Hi @jimazikerlan, 

are you still encountering this issue? If so, could you please provide code for us to reproduce?

**Comment by WilliamLindskog** [comment]
Hi, 

closing this issue as newer versions of flwr can handle this: https://flower.ai/docs/framework/how-to-configure-clients.html
