### ISSUE TITLE
Connection Issue using TF 

### ISSUE THREAD

**Issue by zithasasindran** [adap/flower#1239]
### What is your question?

Hi there,

I am encountering the following error every time running the TensorFlow quickstart code, even after trying a few hacks explained in the issues posted in https://github.com/adap/flower/issues/648 & https://github.com/adap/flower/issues/537

grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"

I tried changing the port values but nothing worked for me. Is there anything else I can do?

My setup:
Ubuntu 20.04 with python virtual environment, Flower  - 0.19.0, Tensorflow - 2.9.1.

**Comment by WilliamLindskog** [comment]
Hi @zithasasindran, 

Is this still an issue that you are encountering?

**Comment by WilliamLindskog** [comment]
Older flwr version is no longer supported and new TF quickstart should run. 

Closing this issue.
