### ISSUE TITLE
Whether server sends updated weights at each round to client or not?.

### ISSUE THREAD

**Issue by sjayarammtech** [adap/flower#1245]
### What is your question?

Hi,
I am using sklearn FL server-clients connection.
Using 3 clients.
Number of rounds =10
My doubt is,
1) Whether server get weights from all clients at each round, then aggregating the weights using FedAvg, then send the updated weights to all clients at end of that current round (say, round 1).
or
2) Server is waiting for all round to finish ,then send the aggregated weight using FedAvg to the clients. 

So simply, weather clients get weight update at each round from server or only at final round .

Is the same mechanism used for tensorflow,pytorch models?.

Thanks,
S.Jayaram

**Comment by adam-narozniak** [comment]
Hi!
The server sends a new set of weights updates at the end of each training round.
Let me be more precise. After each local client trains (the fit method call), it returns its weights, then the aggregate_fit is called, and we have new weights on a global model. Then an optional centralized evaluation is performed. And then, local evaluation is performed, and a new set of weights is sent to do so. So if we call both fit and evaluate as a single federated round, the new set of weights is even sent in the current round after the training. And the new weights are also sent to the new set of clients at the beginning of the new round.
Here is a nice graphic that shows each step: https://flower.dev/docs/implementing-strategies.html
Here is a more detailed explanation of federated learning with all the steps performed along the way: https://flower.dev/docs/tutorial/Flower-0-What-is-FL.html
I hope that answers your question.

**Comment by tanertopal** [comment]
@sjayarammtech, as there was no further comment on this for three weeks and @adam-narozniak has answered the question, I am closing the ticket. @sjayarammtech feel free to open it again if any other questions should arise.
