### ISSUE TITLE
how to support Paddle?

### ISSUE THREAD

**Issue by ziyoujiyi** [adap/flower#1247]
### What is your question?

https://github.com/PaddlePaddle/Paddle
hope for response  thanks

**Comment by danieljanes** [comment]
Thanks for reaching out @ziyoujiyi ! Great question, we should at least add a quickstart code example (incl. documentation). Would you be willing to contribute? If we have someone who's used Paddle before then I'm optimistic that we can make it work without too much effort.

**Comment by WilliamLindskog** [comment]
Seeing that the Paddle framework hasn't been updated in years, I will close this issue.
