### ISSUE TITLE
Sklearn examples parameters initial problem

### ISSUE THREAD

**Issue by Niclouge** [adap/flower#1262]
### What is your question?

Hi, everyone~
I'm a newer in flower.
When I run the sklearn example, I got a initial parameters problem.
The traceback show the problem is "ValueError: Found array with 0 sample(s) (shape=(0, 4)) while a minimum of 1 is required."
![image](https://user-images.githubusercontent.com/44387768/174550589-75d37334-3b54-4c4f-a23a-1f949922c4c7.png)

When I debug the code, I found that the problem came from the initial parameters phase, as shown blew
![image](https://user-images.githubusercontent.com/44387768/174550993-64548969-5b97-4c59-ac83-0404fd38be98.png)

Finally, I located the line 121 of the flwr/server/server.py file, I have not made any changes to the file, why does this happen and how to solve it?

Thank you ~

**Comment by Niclouge** [comment]
![image](https://user-images.githubusercontent.com/44387768/174551984-c2d09a3d-e052-425a-9fd1-ec87d123ff1e.png)
It's the line of code in the picture, I can't find the reason, self.parameters is a binary value, I don't know if the problem is here
![image](https://user-images.githubusercontent.com/44387768/174552487-55a1f582-e040-460b-8ee2-ea07d1486b27.png)

**Comment by WilliamLindskog** [comment]
Hi,

thanks for raising this issue. I'm closing it as the new sklearn example runs and the discussed version of flwr is not supported anymore.
