### ISSUE TITLE
Tree-based Models - Example

### ISSUE THREAD

**Issue by koo-ec** [adap/flower#1269]
### Describe the type of feature and its functionality.

Could ypu please provide a starting point code for tree-based classifiers (such as random forest)?

### Describe step by step what files and adjustments are you planning to include.

I have seen the logistic regression example from sk-learn, however, as trees do not use gradients and the parameters are different. A starting point notebook is much appreciated. 
Thanks

**Comment by Nobre-Lucas** [comment]
I'm having the same issue right now. I really would appreciate some help, but for now I'm trying my best. If something comes to my mind, I'll share it here.

**Comment by WilliamLindskog** [comment]
Hi @koo-ec, @Nobre-Lucas,

Have you tried out XGBoost examples? They might fit you projects if still relevant. https://github.com/adap/flower/tree/968fc774156e3371ad0c58c5f2638c04e3ab0144/examples/xgboost-quickstart
https://github.com/adap/flower/tree/968fc774156e3371ad0c58c5f2638c04e3ab0144/examples/xgboost-comprehensive

**Comment by WilliamLindskog** [comment]
Hi again, 

Closing this issue as XGBoost is supported.
