### ISSUE TITLE
Unable to Implement sklearn models other than LogRegression

### ISSUE THREAD

**Issue by its-arsalan** [adap/flower#1270]
### What is your question?

I have seen an example of implementing Logistic Regression and successfully implemented it as well. But now I want to implement other sklearn models, for example, Decision tree, XGBoost etc but unable to do so. 

Any suggestion or help would be much appreciated.

**Comment by weeebdev** [comment]
Did you find any answers?

**Comment by WilliamLindskog** [comment]
Hi @its-arsalan, @weeebdev,

Have you tried out XGBoost examples? They might fit you projects if still relevant. https://github.com/adap/flower/tree/968fc774156e3371ad0c58c5f2638c04e3ab0144/examples/xgboost-quickstart
https://github.com/adap/flower/tree/968fc774156e3371ad0c58c5f2638c04e3ab0144/examples/xgboost-comprehensive

**Comment by WilliamLindskog** [comment]
Closing this as it refers to older version of flwr.
