### ISSUE TITLE
How to set server IP and server port in android?

### ISSUE THREAD

**Issue by Nawrin14** [adap/flower#1287]
### What is your question?

Hi. Can I get some guidelines for setting the server IP and port in the android app? The server is running on my laptop and the app is running on my android device. But I can't set a connection between them. Is it possible to provide some step-by-step instructions like, 1. change the server address in server.py 2. test the connection, etc. Any help is appreciated!

**Comment by tanertopal** [comment]
@Nawrin14 

1. Use as server address the same as in all examples: `0.0.0.0:8080`, which tells the server to listen on all interfaces / for all hosts
2. Ensure your router in your WIFI network allows communication between devices (check your router settings)
3. Ensure your Phone can reach your server on port 8080, e.g. test by starting a file server first and see if you can reach a website from your smartphone which resides on your server
4. Start the flower server
5. Connect to the flower server from the android device

I hope this helps.

**Comment by Nawrin14** [comment]
Thanks a lot!

**Comment by WilliamLindskog** [comment]
Closing this issue as it seems to be resolved.
