### ISSUE TITLE
TypeError: start_numpy_client() takes 0 positional arguments but 1 positional argument (and 1 keyword-only argument) were given

### ISSUE THREAD

**Issue by ajana1989** [adap/flower#1366]
### Describe the bug

I am trying the quickstart_tensorflow  part. The server.py is working fine with the command 'poetry run python3 server.py' .
But when i try to run client in another terminal using 'poetry run python3 client.py' , it shows the following error-

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 19s 0us/step
Traceback (most recent call last):
  File "client.py", line 32, in <module>
    fl.client.start_numpy_client("127.0.0.1:8080", client=CifarClient())
**TypeError: start_numpy_client() takes 0 positional arguments but 1 positional argument (and 1 keyword-only argument) were given**..

Any clue/lead would be helpful. Thanks in advance!

### Steps/Code to Reproduce

'poetry run python3 client.py'

### Expected Results

client should run

### Actual Results

Traceback (most recent call last):
  File "client.py", line 32, in <module>
    fl.client.start_numpy_client("127.0.0.1:8080", client=CifarClient())
**TypeError: start_numpy_client() takes 0 positional arguments but 1 positional argument (and 1 keyword-only argument) were given**..

**Comment by danieljanes** [comment]
Thanks for the report @ajana1989. This is an error in the code example, I've opened a PR that'll fix it: https://github.com/adap/flower/pull/1367

You can do this to fix the code manually:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/1245515/183865329-dd1ed456-2463-4636-9f07-ae6deb8ef902.png">

**Comment by danieljanes** [comment]
@ajana1989 the PR is now merged, you can also check out the latest version of the code example.

**Comment by ajana1989** [comment]
Thanks a lot for the quick response!  I really appreciate that! :)
