### ISSUE TITLE
"failed to connect to all addresses" but with more details provided

### ISSUE THREAD

**Issue by submartingales** [adap/flower#1374]
### Describe the bug

Similar to other users' problems 

```
Traceback (most recent call last):
  File "client.py", line 106, in <module>
    fl.client.start_numpy_client(server_address="[::]:8081", client=FlowerClient())
  File "/opt/conda/envs/ml-federated-3.7.12/lib/python3.7/site-packages/flwr/client/app.py", line 115, in start_numpy_client
    grpc_max_message_length=grpc_max_message_length,
  File "/opt/conda/envs/ml-federated-3.7.12/lib/python3.7/site-packages/flwr/client/app.py", line 64, in start_client
    server_message = receive()
  File "/opt/conda/envs/ml-federated-3.7.12/lib/python3.7/site-packages/flwr/client/grpc_client/connection.py", line 60, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/opt/conda/envs/ml-federated-3.7.12/lib/python3.7/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/opt/conda/envs/ml-federated-3.7.12/lib/python3.7/site-packages/grpc/_channel.py", line 809, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1652340915.644527504","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3128,"referenced_errors":[{"created":"@1652340915.644526921","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
```

More technical details I observe are when I checked the listening ports after

```
python3 server.py
```

The port specified in `server.py` was not listened even for the root user.

### Steps/Code to Reproduce

```
python3 server.py
```

or even 

```
sudo python3 server.py
```

### Expected Results

Port specified in code will be listened.

### Actual Results

Otherwise

**Comment by submartingales** [comment]
I hope this issue can be resolved by the dev team as soon as possible or at least provide a stable workaround for me.

**Comment by shashankc28** [comment]
Hi I am getting same issue . any new on this topic ?

**Comment by sandeepnmenon** [comment]
+1 
I am facing same issue while running this on cloud servers.

**Comment by danieljanes** [comment]
cc @tanertopal

**Comment by tanertopal** [comment]
@submartingales, could you please provide some code? My guess would be your server is not running and therefore the client can not connect.

**Comment by submartingales** [comment]
> @submartingales, could you please provide some code? My guess would be your server is not running (on port 8081 as specified in your client code) and therefore the client can not connect.

After months I found some clues on why these things happen, server not listening maybe just a special issue on the server I used then caused by some kind of configurations. But later I encounter the same problem on various environments and platforms which reported errors  therefore I believe it is still a common problem
```
status = StatusCode.UNAVAILABLE
details = "failed to connect to all addresses"
```
What I have found is that the connection problem is probably caused by the security feature provided by higher version of `grpc`.

**Comment by submartingales** [comment]
As far as I know, latest version of `grpc` enforce strict security policy to make sure all connections to be secure and encrypted, and *there are no easy ways to override that restriction* except downgrading the `grpc` version.

**Comment by submartingales** [comment]
@tanertopal @danieljanes In the meantime, some part of `grpc` 's functionality is provided as binary packages in different linux distros and installed by the system package managers, which makes the downgrading procedure even harder. As far as I know,  platforms using`20.04 LTS` and `22.04 LTS` may have a much higher probability of the connection issue than on `18.04 LTS` and `16.04 LTS` . There seems no way to easily enable the secure `grpc` connection without modifying `flower`'s source code. Maybe, making secure `grpc` as the default communication  manner or at least provide interfaces for users' manual configurations can resolve this problem.

**Comment by submartingales** [comment]
I hope these problems can be resolved as soon as possible.

**Comment by submartingales** [comment]
I really appreciate your efforts to make a research friendly framework but I think many of us may still have concerns on writing our code based on `flower` entirely if this issue can not be resolved.

**Comment by WilliamLindskog** [comment]
Hi @submartingales 

Thanks for raising this. Is this an issue that you are still experiencing?

**Comment by WilliamLindskog** [comment]
Hi again, 

closing this issue as it seems to have been resolved through new `flwr` versions.
