### ISSUE TITLE
Federated HuggingFace Transformers using Flower and PyTorch with Colab

### ISSUE THREAD

**Issue by kareemgamalmahmoud** [adap/flower#1392]
### Describe what the documentation is missing.

[Federated HuggingFace Transformers using Flower and PyTorch](https://github.com/adap/flower/tree/main/examples/quickstart_huggingface) : 
I tried converting this repo several times to use it with colab, but I always run into limited ram resources.

### Suggest your improvement.

So can anyone help me and show me how to use flower simulator with colab for huggingface!

**Comment by danieljanes** [comment]
Thanks for reaching out @kareemgamalmahmoud. Did you build the Colab version using the Edge Client Engine (`start_server` & `start_client`) or the Virtual Client Engine (`start_simulation`)?

**Comment by WilliamLindskog** [comment]
Hi again, 

The mentioned flwr version is no longer supported. I tried to reproduce the code in colab and it works with the new examples. I advice you to take a look at them if it is still of interest. 

Closing this for now.
