### ISSUE TITLE
How to change max_message_length in function start_simulation()?

### ISSUE THREAD

**Issue by Luoyang144** [adap/flower#1399]
### What is your question?

Hello, I'm tring to do simulation experiment, which need transport about 1~2G or larger model parameters, but the fefault config is 512M, how can I change this config?

**Comment by WilliamLindskog** [comment]
Hi @Luoyang144,

Thanks for raising this. Is this still an issue that you are experiencing?

**Comment by WilliamLindskog** [comment]
Hi again, 

this is supported by newer flwr versions in which you can specify the max message length when starting clients and server. https://github.com/search?q=repo:adap/flower%20grpc_max&type=code 

Closing this for now.
