### ISSUE TITLE
How can I get the error type when occur failure in simulation fit round?

### ISSUE THREAD

**Issue by Luoyang144** [adap/flower#1400]
### What is your question?

Hello, I'm tring to do simulation experiment and get output like this:
![image](https://user-images.githubusercontent.com/63402979/187898959-007d5653-5af5-428f-b1bc-25f2d0b8e324.png)
I want to get the error log of client, how can I get it?

**Comment by edogab33** [comment]
If there is an error in your code it shows up in the output, but somethimes I also get failures without any apparent error so I am also interest in that

**Comment by Mirian-Hipolito** [comment]
I'm facing the same issue .. it's apparently training but all the logs show that during each round, all clients are failures.

![image](https://user-images.githubusercontent.com/94491775/188951141-3fa3e41b-22b9-4d8c-9c52-c4178f1e4b04.png)

**Comment by edogab33** [comment]
Maybe you already tried it, but try to print the failures list passed as argument in the aggregate_fit() method of the strategy that you're using

**Comment by wizard1203** [comment]
I met the same problems when using simulation... There are always failures during each round.

**Comment by wizard1203** [comment]
![image](https://user-images.githubusercontent.com/22996426/189470503-ce2e1fe5-8086-464a-a818-db504ad14119.png)
I apparently raise RuntimeError in the function fit(). But there is only the print of 5 failures without the error log.
![image](https://user-images.githubusercontent.com/22996426/189470549-e6917a30-b5e5-4f32-b21c-20d0e4e29975.png)

**Comment by Mirian-Hipolito** [comment]
@wizard1203 try to update the ray version, that solved my problem with the basic example in the repo.

**Comment by Luoyang144** [comment]
@Mirian-Hipolito Hello, did you meet this problem? I use `pip install --upgrade ray` to upgrade ray but get this error.
![image](https://user-images.githubusercontent.com/63402979/189861678-586bf4cd-7f81-4ea2-84ef-a0d0127dc544.png)

**Comment by WilliamLindskog** [comment]
Closing this as more comprehensive error logs are included and updated ray versions throw error messages.
