### ISSUE TITLE
Does Flower support vertical federated learning? 

### ISSUE THREAD

**Issue by amyseoj1** [adap/flower#1402]
### What is your question?

Does Flower support vertical federated learning? Is there any example available ?

**Comment by Wanghaoyu920** [comment]
Hello, I have the same question, but Flower doesn't seem to support it. Because the model parameters uploaded by each client must be consistent, but for vertical federated learning, the number of features or features of each client model is different.

**Comment by WilliamLindskog** [comment]
Currently supports VFL: https://github.com/adap/flower/tree/main/examples/vertical-fl. Closing this issue.
