### ISSUE TITLE
Implement Krum, MultiKrum and FedMedian

### ISSUE THREAD

**Issue by edogab33** [adap/flower#1405]
### Describe the type of feature and its functionality.

I am working on Federated Learning in adversarial settings, where clients can perform model poisoning in order to degrade the aggregated model performances. To mitigate the effect of model poisoning attacks I have implemented Krum, MultiKrum and FedMedian as strategies. 

Would you be interested to include them in the main repository?

### Describe step by step what files and adjustments are you planning to include.

I am planning to create three new files in the strategy directory: krum.py, multikrum.py and fedmedian.py.

### Is there something else you want to add?

Krum and MultiKrum are described [here](https://proceedings.neurips.cc/paper/2017/file/f4b9ec30ad9f68f89b29639786cb62ef-Paper.pdf).

**Comment by danieljanes** [comment]
@edogab33 sounds great, yes, we'd be interested in adding them!

I'd recomend creating three separate PR's, this will make it easier to review and merge them one by one.

**Comment by danieljanes** [comment]
Reopening, `FedMedian` has been merged, but Krum and MultiKrum are still outstanding. We could also created separate issues for them, wdyt @edogab33 ?

**Comment by edogab33** [comment]
> 



> Reopening, `FedMedian` has been merged, but Krum and MultiKrum are still outstanding. We could also created separate issues for them, wdyt @edogab33 ?

Alright!
