### ISSUE TITLE
How to implement quickstart_pytorch_lightning  with google colab  ?

### ISSUE THREAD

**Issue by kareemgamalmahmoud** [adap/flower#1414]
### Describe the bug

I was trying to implement [quickstart_pytorch_lightning](https://github.com/adap/flower/tree/main/examples/quickstart_pytorch_lightning)  on google colab with flwr simulator , but for each round I received no results.

[Colab link](https://colab.research.google.com/drive/1vtUAy4uoxYPcnppDaXlaEC3my9DRf4rq?usp=sharing) : https://colab.research.google.com/drive/1vtUAy4uoxYPcnppDaXlaEC3my9DRf4rq?usp=sharing

### Steps/Code to Reproduce

I just added "mnist.py" then "client.py"  files in separate cells

### Expected Results

I was expecting any results, but i got nothing.

### Actual Results

DEBUG flower 2022-09-07 01:07:11,701 | server.py:184 | evaluate_round 5 received 0 results and 5 failures
DEBUG:flower:evaluate_round 5 received 0 results and 5 failures

**Comment by edogab33** [comment]
Personally I did not find a way to work with Lightning and FLower together. See here: https://github.com/adap/flower/discussions/1397

**Comment by WilliamLindskog** [comment]
Hi @edogab33, @kareemgamalmahmoud 

Thanks for raising this. The version of flwr used is no longer supported. Have you tried this example? https://github.com/adap/flower/tree/main/examples/quickstart-pytorch-lightning

**Comment by WilliamLindskog** [comment]
Hi again, 

I configured the example previously mentioned to fit colab. It runs fine from what I can see so I'll close this issue.
