### ISSUE TITLE
Continuous JSON DecodeError in simulation

### ISSUE THREAD

**Issue by Mirian-Hipolito** [adap/flower#1418]
### What is your question?

Hello! I'm implementing a new model + dataset in the simulation example. However, once it's running I receive in some rounds a couple client's failures that don't seem clear to interpret.  This is the list of failures passed to aggregate_fit()

![image](https://user-images.githubusercontent.com/94491775/189393885-3f9f8413-67e9-41e0-a872-560967a971c7.png)

Is there any way I can debug better what was the issue with this client? It might be related to the dataset but I'm not sure how can I access to the specific traceback.

Thanks! :)

**Comment by danieljanes** [comment]
Hi @Mirian-Hipolito , thanks for the report! Could you try this again with Flower 1.1 (released two days ago)? There are quite a few improvements in the simulation stack, including better error messages.

**Comment by WilliamLindskog** [comment]
Hi @Mirian-Hipolito,

Is this an issue that you are still encountering?

**Comment by WilliamLindskog** [comment]
Closing this issue as newer flwr versions include better simulation error output.
