### ISSUE TITLE
Mermaid graph in implementing-strategies is not rendered

### ISSUE THREAD

**Issue by kantale** [adap/flower#1433]
### Describe what the documentation is missing.

The graph in the documentation chapter regarding [implementing strategies](https://flower.dev/docs/implementing-strategies.html) is not rendered. Instead the raw code of the mermaid graph is shown.

Screenshot:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/1254711/192465552-300f860a-026d-4b20-b562-761d8bd38e49.png">

Tested on: Firefox, Chrome

**Comment by danieljanes** [comment]
Thanks for the report @kantale , this has been fixed now
