### ISSUE TITLE
ValueError: Cannot invoke RPC on closed channel!

### ISSUE THREAD

**Issue by faustinaSelvadeepa** [adap/flower#1438]
### What is your question?

The flower server closes before the client finishes running and throws the following error.
please let me know how to resolve it.
![image](https://user-images.githubusercontent.com/36688776/193572523-17edf766-a43a-4f09-9158-bc3872bd0a65.png)

**Comment by danieljanes** [comment]
Thanks for the report @faustinaSelvadeepa , how long does the channel stay open?

**Comment by faustinaSelvadeepa** [comment]
It says FL finished in 41.68
![image](https://user-images.githubusercontent.com/36688776/193729167-6142b5e5-fcc2-4b1f-88a6-c97bdf85b37d.png)

**Comment by sobolak** [comment]
Same error in my issue

**Comment by danieljanes** [comment]
@faustinaSelvadeepa / @sobolak could you share the logs for both the server and the two clients please?

The server log looks perfectly normal. Can you perhaps provide a minimal reproducible code example that we can use to investigate?

**Comment by WilliamLindskog** [comment]
Hi @sobolak, @faustinaSelvadeepa,

is this an issue that you are still encountering?

**Comment by WilliamLindskog** [comment]
Hi, 

I am closing this as the flwr version mentioned is not supported anymore and the logs look like normal output.
