### ISSUE TITLE
Add simulation of resource-constrained scenarios

### ISSUE THREAD

**Issue by MuleiOnline** [adap/flower#1484]
### What is your question?

Thanks for the excellent code, I have the following questions:

Where should I contribute (add) my code if I want to implement federated learning with limited resources. For example, I need to simulate the delay and energy consumption of weight upload, as well as the distribution of data in each edge node, training delay and energy consumption, etc. In order to achieve the above, I need to add functions, such as increasing the heterogeneity settings of clients, or realizing the bandwidth and network gain of transmission links.

Unfortunately, I don't see a way to do it in the existing code, and it seems that the above simulation is difficult to achieve. How should I insert it?

**Comment by WilliamLindskog** [comment]
Hi 

To achieve these, you can start by modifying the `Client` class to introduce heterogeneity in training capabilities, such as available memory (can be specified in `pyproject.toml`. You can explore the examples/ directory to see how custom client logic is implemented and extend from there. For modeling network delays and bandwidth, you could integrate these features by modifying the `ClientManager` to simulate delays during communication. Bandwidth and network gain can be visualized using code as in examples using either Weights and Biases or [here](https://github.com/adap/flower/tree/main/examples/flower-via-docker-compose). 

For contributing, we recommend implementing these changes in a separate branch within your fork of Flower. Adding an example in the examples/ folder to showcase the new functionality would also be very helpful. You can open a Pull Request and I'd be happy to check on it. 

Closing this issue for now.
