### ISSUE TITLE
How to create connection and set “”server_address” (IP) between Client and server between 2 (different ) machines.

### ISSUE THREAD

**Issue by KawhiHeisenberg631** [adap/flower#1499]
### What is your question?

The server certificate is downloaded by this example: https://flower.dev/docs/ssl-enabled-connections.html and https://github.com/adap/flower/tree/main/examples/advanced_tensorflow. Machines A and B use the same certificate, and they are on the same LAN.

1. machine A
![image](https://user-images.githubusercontent.com/71743851/205835778-08a497e4-3efe-4f61-adb8-35474584d56c.png)
2. machine B
![image](https://user-images.githubusercontent.com/71743851/205836768-71974333-7c34-4806-b3b1-b7202ec64649.png)
in which sever_address is my server's (machine A) ipv4 address. Only in this way, the server edge shows the results like this: 
"E1206 14:07:45.082000000  5876 src/core/tsi/ssl_transport_security.cc:1910] No match found for server name: 10.188.141.42.".

In machine B (client edge), I have tried "fl.client.start_numpy_client(server_address="240e:381:532:710:8b99:a9f2:251a:6f7e:8080",..), i.e. my ipv6 address. But showing this result:
![image](https://user-images.githubusercontent.com/71743851/205837249-d25b6a51-cc76-4377-9b12-45f639eb64fc.png)
Now， the server had no result like this "E1206 14:07:45.082000000  5876 src/core/tsi/ssl_transport_security.cc:1910] No match found for server name: 10.188.141.42."

and tried "fl.client.start_numpy_client(server_address="localhost:8080",..), and the result is as follows: 
![image](https://user-images.githubusercontent.com/71743851/205837483-65f6e95a-a2f2-40c9-b0ad-c609b311b306.png)
Now， the server had no result like this "E1206 14:07:45.082000000  5876 src/core/tsi/ssl_transport_security.cc:1910] No match found for server name: 10.188.141.42."

My router in my WIFI network allows communication between machines A and B:
![image](https://user-images.githubusercontent.com/71743851/205849442-93ed0213-2cae-4411-a407-05c1786d536d.png)

I have tried my best to achieve communication between machines A and B, but the result is not satisfactory. 

Hope some big guy can help me out!!!

**Comment by X-Omil** [comment]
> @tanertopal  请问后来你解决了你的问题了吗？

**Comment by WilliamLindskog** [comment]
Hi @X-Omil,

Is this an issue that you are still encountering?

**Comment by WilliamLindskog** [comment]
Hi again ,

this can be done in newer flwr versions, check pytorch-app example for some reference. 

Closing this for now.
