### ISSUE TITLE
Custom Flower Client custom class properties not updating.

### ISSUE THREAD

**Issue by Pedja-Djape** [adap/flower#1530]
### Describe the bug

Hi all. 

Using the FL tutorials provided for PyTorch, I have defined my own class _FlowerClient_ that subclasses the _NumPyClient_ provided by flower. In my Client's `__init__(...)` function I initialize some custom class property. However, changing the initial value in the `fit` function only causes the value of the property to get updated until `fit` returns; for instance, after `fit` runs, the value of the property remains as the initial one (set in `__init__`). 

### Steps/Code to Reproduce

Define 
```
class FlowerClient(fl.client.NumPyClient): 
    def __init__(self,net,trainloader,valloader,epochs):
        super().__init__()
        ...
        self.custom_property = None
```
Then in my `fit` function, I change this value as such:
```
def fit(self, parameters,config):
        self.set_parameters(parameters)
        train(
            model=self.net,
            trainloader=self.trainloader,
            epochs=self.epochs
        )
        self.custom_property = 5
        print(f"\n\n\n{self.custom_property}\n\n\n")
        return self.get_parameters(config={}),len(self.trainloader.dataset),{}
```
However, when trying to access `self.custom_property` in my `evaluate` function, say via `print(self.custom_property)`, it prints `None` in any federated loop.
```
def evaluate(self, parameters, config):
        print(f"\n\n\n{self.custom_property}\n\n\n")
        self.set_parameters(parameters)
        loss,accuracy = test(self.net,self.valloader)
        return loss,len(self.valloader.dataset), {'accuracy': accuracy}
```

 

### Expected Results

When printing the value of `self.custom_property` in both `fit` and `evaluate` I expect for the logs to show the following:
```
(launch_and_fit pid=X) 5
(launch_and_evaluate pid=X) 5
```

### Actual Results

When printing the value of `self.custom_property` in both `fit` and `evaluate` I expect for the logs to show the following:
```
(launch_and_fit pid=X) 5
(launch_and_evaluate pid=X) None
```

**Comment by Pedja-Djape** [comment]
Note that I am using the simulated version of training and that this issue doesn't occur when not in simulation mode. ANyone know how I can prevent this behavior in simulated mode?

**Comment by pengrui01** [comment]
Has it been resolved? I also don’t update the parameters in the fit function.

**Comment by WilliamLindskog** [comment]
Hi @Pedja-Djape, @pengrui01 

Thanks for raising this. This seems to have to do with stateless clients, meaning that they are "re-created" as initially specified. We have documentation on [how to design stateful clients](https://github.com/adap/flower/blob/main/doc/source/how-to-design-stateful-clients.rst) which I think will help here. Please let me know if this helps and if we can close this issue.

**Comment by WilliamLindskog** [comment]
Closing this issue as one can design stateful clients using above documentation.
