### ISSUE TITLE
flwr.simulation.start_simulation not working (1.1.0)

### ISSUE THREAD

**Issue by leebs0521** [adap/flower#1561]
### Describe the bug

Hi, I am trying to use the flwr simulation in the version 1.1.0 with Python 3.7 However, when I start the simulation with fl.simulation.start_simulation, it presents the following:

ray version is 1.11.1
please help..
![image](https://user-images.githubusercontent.com/86824224/212001895-06f82ba5-de49-474a-a64a-2cf83a6938bb.png)

### Steps/Code to Reproduce

![image](https://user-images.githubusercontent.com/86824224/212002197-5508b01a-ebbb-45bf-a61d-701d99e53845.png)

### Expected Results

possible

### Actual Results

not possible

**Comment by leebs0521** [comment]
> ### Describe the bug
> Hi, I am trying to use the flwr simulation in the version 1.1.0 with Python 3.7 However, when I start the simulation with fl.simulation.start_simulation, it presents the following:
> 
> ray version is 1.11.1 please help.. ![image](https://user-images.githubusercontent.com/86824224/212001895-06f82ba5-de49-474a-a64a-2cf83a6938bb.png)
> 
> ### Steps/Code to Reproduce
> ![image](https://user-images.githubusercontent.com/86824224/212002197-5508b01a-ebbb-45bf-a61d-701d99e53845.png)
> 
> ### Expected Results
> possible
> 
> ### Actual Results
> not possible

**Comment by leebs0521** [comment]
It was resolved by changing to Python 3.7.10.

**Comment by tanertopal** [comment]
@leebs0521 could you share with us which exact Python version you were using previously?

**Comment by leebs0521** [comment]
@tanertopal  I used Python 3.7.0.

**Comment by danieljanes** [comment]
@leebs0521 could you please try this again with Flower 1.3?

**Comment by WilliamLindskog** [comment]
Closing this as the versions of flwr are outdated.
