### ISSUE TITLE
Return Custom Variable

### ISSUE THREAD

**Issue by fionavictoria** [adap/flower#1606]
### What is your question?

I have been trying to return a custom variable from fit() function that can be used in the evaluate() function of the flowerclient. Is it possible currently?

**Comment by tanertopal** [comment]
@fionavictoria could explain the specific use case? Is it supposed to be used with the same client? Are you using `start_simulation` or `start_server `?

**Comment by charlesbvll** [comment]
@fionavictoria What you might be able to do is to create a class attribute for your `test_variable`, update it in `fit()` and print it in `evaluate()`, like so:

```
def __init__(self, model, trainloader, cid, timesteps, epochs, device):
    self.model = model
    self.trainloader = trainloader
    self.cid = cid
    self.timesteps = timesteps
    self.epochs = epochs
    self.device = device
    
def set_parameters(self, parameters):
    params_dict = zip(self.model.state_dict().keys(), parameters)
    state_dict = OrderedDict({k: torch.tensor(v) for k, v in params_dict})
    self.model.load_state_dict(state_dict, strict=True)
    
def get_parameters(self, config): 
    return [val.cpu().numpy() for _, val in self.model.state_dict().items()]

def fit(self, parameters, config):
    # Update local model parameters
    self.set_parameters(parameters)        
    # Read values from config
    server_round = config["server_round"]
    train(self.model, self.trainloader, self.cid, server_round, self.epochs, self.timesteps)
    self.test_variable = 10
    return get_parameters(self.model), len(self.trainloader), {}

def evaluate(self, parameters, config):  
    # Update local model parameters
    self.set_parameters(parameters)
    print(self.test_variable)
    server_round = config["server_round"]
    validate(self.model, self.cid, server_round, self.timesteps, self.device)
```

I don't know if this works for your use case, but this way each client will store its own version of the `test_variable`, accessible by both `fit()` and `evaluate()`.

Note that you can also give it an initial value in `__init__()`.

Hope this helps!

**Comment by WilliamLindskog** [comment]
Hi, 

this seems to be resolved. Closing this as the mentioned flwr version is no longer supported.
