### ISSUE TITLE
Implement a new strategy: TrimmedMean

### ISSUE THREAD

**Issue by edogab33** [adap/flower#1610]
### Describe the type of feature and its functionality.

I propose to add TrimmedMean as a new strategy robust against poisoning attacks.

It works by removing the largest and smallest `beta` parameters from the local models received by the server and finally average their values to make the new global model.

Trimmed Mean: https://arxiv.org/pdf/1803.01498.pdf

### Describe step by step what files and adjustments are you planning to include.

I am planning to add a new strategy `trimmedmean.py` and its tests in `trimmedmean_test.py`.

**Comment by danieljanes** [comment]
@edogab33 good idea

**Comment by edogab33** [comment]
Can we close this issue?

@danieljanes @adam-narozniak
