### ISSUE TITLE
Implement a new strategy: Bulyan

### ISSUE THREAD

**Issue by edogab33** [adap/flower#1612]
### Describe the type of feature and its functionality.

Finally, I propose to add Bulyan as a new strategy robust against poisoning attacks.

Bulyan works by first applying Krum (or any other robust aggregation function actually, but we can expand it later on) `theta` times from the set of received local models (without replacement) and putting these models into the set _S_, then it computes the median of the models in _S_ and finally, it applies MeaMed on them.

Bulyan: https://arxiv.org/pdf/1802.07927.pdf

### Describe step by step what files and adjustments are you planning to include.

I am planning to add a new strategy bulyan.py and its tests in bulyan.py.

### Is there something else you want to add?

After that, I will have implemented almost every strategy I've done so far.

I also have the code for FLTrust (https://arxiv.org/pdf/2012.13995.pdf), but it changes the FL protocol a little bit (in a nutshell, the server acts as a client), so I postpone its integration in Flower to a remote future.

Finally, after its publication, I would like to add my strategy developed in the last months. It would be great for us to have it integrated into Flower.

**Comment by danieljanes** [comment]
@edogab33 good idea

**Comment by kamathhrishi** [comment]
Hi, I see this issue is implemented. Shouldn't this be closed? Thank you.
