### ISSUE TITLE
Connection Frozen

### ISSUE THREAD

**Issue by mhmhmd96** [adap/flower#1661]
### What is your question?

When I am running my scenario with a remote server and multiple clients in GNS3. Sometimes the connection for one client is frozen waiting the server while others start their local training. Anyone has anu idea to solve this problem?

**Comment by WilliamLindskog** [comment]
Hi @mhmhmd96,

Is this an issue that you are still experiencing?

**Comment by WilliamLindskog** [comment]
Could you provide more details on this issue if you are still experiencing this? @mhmhmd96

**Comment by WilliamLindskog** [comment]
Closing this issue for now.
