### ISSUE TITLE
Do you have a plan to support vertical federated ML?

### ISSUE THREAD

**Issue by happynoom** [adap/flower#1701]
### What is your question?

Do you have a plan to support vertical federated ML?

**Comment by danieljanes** [comment]
Thanks for reaching out @happynoom - yes, definitely. It has become a lot easier to implement with the new (still experimental) Driver API. We'd be happy to help users who want to contribute a code example.

**Comment by leonharetd** [comment]
I need this feature. what can I do for this？

**Comment by WilliamLindskog** [comment]
Closing this issue as it is currently supported: https://github.com/adap/flower/tree/968fc774156e3371ad0c58c5f2638c04e3ab0144/examples/vertical-fl
