### ISSUE TITLE
How does Flower server store model weights from different clients ? What serialization method does Flower use ? 

### ISSUE THREAD

**Issue by egegulerr** [adap/flower#1704]
### What is your question?

Hello, I am new to Federated Learning. I am trying to create an application in which I can control the serialization methods for model weights and the communication protocols between the client and server.  For  HTTP communication I am using FastAPI to send the serialized (JSON) client weights to the server.  In order to store weights in a global variable to use FedAvg in server. (weights data are lost between different workers of FastAPI), I have to store the weights in Cache using REDIS or Memcached).  

For the gRPC communication and protobuffer serialization, I am using the Flower. I am really impressed by how well everything works. So my question is how does Flower manage to store these weights from different clients? Let's assume I have 2 clients `client.1.py`, `client2.py`. 

Or did I understand the whole process totally wrong ?.

**Comment by WilliamLindskog** [comment]
Hi @egegulerr 

Welcome to Federated Learning! Your application setup sounds great. 

Regarding your question, Flower manages client weights in memory on the server during each federated learning round. When clients send their model weights back, the server’s strategy (e.g., FedAvg) aggregates them in memory, computes a new global model, and sends it back to the clients for the next round. These weights are not persisted unless explicitly configured. 

You could store weights across FastAPI workers, but Flower simplifies this by keeping everything in a single server process. If this helps, feel free to close this issue.
