### ISSUE TITLE
Time series anamoly detector Android 

### ISSUE THREAD

**Issue by Deepakpy** [adap/flower#1746]
## Android implementation of time series Autoencoder 
Hello everyone i am trying to implement this time series anamoly detector autoencoder example from keras https://keras.io/examples/timeseries/timeseries_anomaly_detection/
In flower.

When i am trying to build Android app for the federated training using this ad reference https://flower.dev/blog/2021-12-15-federated-learning-on-android-devices-with-flower/.

I was successful in creating the tflite files by using the tfliteconvertor .

The problem i face is that the TransferLearningModelWrapper.java has the customized code for the cifar code example which specifies the output class names in it such as the 10 classes cat, car etc. I don't know how to change that to the autoencoder related output features as in autoencoders both the input features and the output features are same. Meaning the x_train and the y_train will be same. 

TransferLearningModelWrapper(Context context) {
        model =
                new TransferLearningModel(
                        new AssetModelLoader(context, "model"),
                        Arrays.asList("cat", "dog", "truck", "bird",
                                "airplane", "ship", "frog", "horse", "deer",
                                "automobile"));
        this.context = context;
    }. 
Can someone guide how to modify it for timeseries data and what goes into this AssetModelLoader for an Autoencoder

**Comment by WilliamLindskog** [comment]
Hi @Deepakpy 

Thanks for raising this. Is this still an issue that you are experiencing? If so, have you tried the updated version: https://github.com/adap/flower/tree/main/examples/android

The example code that you are referring to is nowadays not longer supported.

**Comment by WilliamLindskog** [comment]
Closing this as the mentioned code is no longer supported.
