### ISSUE TITLE
Drop Clients based on performance

### ISSUE THREAD

**Issue by fionavictoria** [adap/flower#1756]
### Describe the type of feature and its functionality.

A feature to drop clients based on the individual performance that is sent back to the server. By doing this, those specific clients don't participate in the upcoming server rounds.

### Describe step by step what files and adjustments are you planning to include.

-

**Comment by adam-narozniak** [comment]
Hi!
It is currently possible. This is how I would approach it. I'd implement a custom strategy by subclassing some of the currently existing strategies e.g., FedAvg, and collect their history of performance in a map cid to performance history (probably a good idea for that would be to have a centralized dataset so the results can be directly comparable) this can be implemented in the `aggregate_fit` method. And now, after checking the history to know which client to drop, I think there are two choices. One would be to unregister a client using the client manager. Another would be to update a criterion used for client sampling, which can be as simple as checking if a cid is in the dropped clients list.

I hope that helps. Let me know if you need further help with implementing this. If so, we will create a strategy with such functionality. (However, I do not think we are planning to create any callback or things of such a manner if that was your question).

**Comment by worshipone** [comment]
I also have such a need.

**Comment by WilliamLindskog** [comment]
Hi @fionavictoria, @worshipone,

Is this an issue that you are still experiencing?

**Comment by WilliamLindskog** [comment]
Using the newer flower versions, you could call the class object `client_manager` within the `aggregated_evaluate` function in the strategy document and filter/drop clients that do not meet certain criteria based on the metrics/values that you pass from client to server. 

I am closing this issue for now.
