### ISSUE TITLE
Add documentation on how to control logging

### ISSUE THREAD

**Issue by kantale** [adap/flower#1765]
### Describe what the documentation is missing.

I had to search the source code in order to find a way to control logging. Perhaps it should be added to the documentation. 

### Suggest your improvement.

It should be added information regarding logging. The way I did it is was with the following snippet:

```python

import logging
from flwr.common import logger

logger.logger.setLevel(logging.ERROR)
```

**Comment by gfmota** [comment]
There is already a doc for configuring logger https://flower.dev/docs/framework/how-to-configure-logging.html
