### ISSUE TITLE
kubernetes support?

### ISSUE THREAD

**Issue by wardnath** [adap/flower#1778]
### Describe the type of feature and its functionality.

any plans to add support for kubernetes cluster deployments via helm install or k8s operator?

### Describe step by step what files and adjustments are you planning to include.

helm files, kustomize templates, k8s manifests, etc.

**Comment by WilliamLindskog** [comment]
Hi @wardnath 

Thanks for raising this. Docker-Compose files can be converted to Kubernetes manifests. While the effectiveness may vary, tools like [Kompose](https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/) provide this functionality. We provide a [docker compose example](https://github.com/adap/flower/tree/main/examples/flower-via-docker-compose) that can be converted. 

For now I will close this issue.
