### ISSUE TITLE
client has a question about grpc._channel._MultiThreadedRendezvous

### ISSUE THREAD

**Issue by zzzhhhlll** [adap/flower#1782]
### What is your question?

* is unimportant content.
there is a client,which has a bug as follows;
this is a tensorflow_example;

INFO flwr    ** | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr  **| connection.py:38 | ChannelConnectivity.IDLE
DEBUG flwr  **| connection.py:38 | ChannelConnectivity.CONNECTING
DEBUG flwr  **| connection.py:38 | ChannelConnectivity.TRANSIENT_FAILURE
DEBUG flwr  **| connection.py:109 | gRPC channel closed
Traceback (most recent call last):
  File "******\venv_flower\tensorflow_example\client.py", line 20, in <module>
    fl.client.start_numpy_client(server_address="[::]:8080", client=CifarClient())
  File "*******\venv_flower\lib\site-packages\flwr\client\app.py", line 214, in start_numpy_client
    start_client(
  File "*****\venv_flower\lib\site-packages\flwr\client\app.py", line 145, in start_client
    server_message = receive()
  File “******\venv_flower\lib\site-packages\flwr\client\grpc_client\connection.py", line 101, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "******\venv_flower\lib\site-packages\grpc\_channel.py", line 475, in __next__
    return self._next()
  File "*****\venv_flower\lib\site-packages\grpc\_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv6:  *****8080: WSA Error"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv6:*****:8080: WSA Error {grpc_status:14, created_time:""}"
>

Process finished with exit code 1

**Comment by noobyzy** [comment]
The messages convey that the client cannot connect to `[::]:8080`.
Try to replace `[::]:8080` with `127.0.0.1:8080` or `0.0.0.0:8080` or `localhost:8080` if your server and client are on the same machine. See [Link](https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost) for explanation.
If they are on different machines, check the server IP, and correct your `[::]:8080` on client to server IP (and port).

**Comment by WilliamLindskog** [comment]
Hi @zzzhhhlll, 

is this still an issue that you are experiencing? If not, we could consider closing this issue.

**Comment by WilliamLindskog** [comment]
Closing this issue as it seems to have been resolved.
