### ISSUE TITLE
Inference of a federated learnt transformer

### ISSUE THREAD

**Issue by sauravtii** [adap/flower#1796]
### What is your question?

In this [tutorial](https://flower.dev/docs/quickstart-huggingface.html), how can I use the transformer which was trained in a federated manner on IMDB dataset, for inference?

**Comment by tanertopal** [comment]
@sauravtii not sure I understand the question. Can you elaborate further?

**Comment by sauravtii** [comment]
Sure @tanertopal. So my question is, in [this](https://flower.dev/docs/quickstart-huggingface.html) tutorial we are fine-tuning a transformer model (distill-bert) on IMDB dataset. So, after fine-tuning is complete, how can I use the model for inference or how can I use the fine-tuned model for performing predictions?

Also, where does the fine-tuned model gets saved?

**Comment by mnabihali** [comment]
Did you find a solution for this issue?

**Comment by WilliamLindskog** [comment]
Closing this as model can be loaded using checkpoints, description in previous comment.
