### ISSUE TITLE
why do you remove and rename the column?

### ISSUE THREAD

**Issue by sauravtii** [adap/flower#1823]
### What is your question?

In this [script](https://github.com/adap/flower/blob/32912119cd1f1376234c58c3bf8f9fb9c213e706/examples/quickstart_huggingface/client.py#L43), why do you remove the `text` column and rename the `label` column?

@tanertopal

**Comment by WilliamLindskog** [comment]
Hi @sauravtii 

Thanks for raising your question. In this script, the `text` column is removed after tokenization to avoid redundancy and save memory, as the raw text is no longer needed. The `label` column is renamed to `labels` to match the format expected by the Hugging Face transformers library, ensuring the model correctly identifies it as the target variable for computing loss during training and evaluation. These adjustments streamline compatibility with the model.

Closing this issue.
