### ISSUE TITLE
accuracy not increasing

### ISSUE THREAD

**Issue by sauravtii** [adap/flower#1825]
### What is your question?

I am trying out this [tutorial](https://flower.dev/docs/quickstart-huggingface.html) but even after training it for long period of time, the accuracy doesn't seem to increase. Also, I have removed the population part therefore I am using the complete dataset even then the accuracy doesn't seem to increase.

@tanertopal @niclane7

**Comment by WilliamLindskog** [comment]
Hi

using the new example https://github.com/adap/flower/tree/main/examples/quickstart-huggingface, the loss is decreasing, might have been an older implementation. Are you still experiencing this issue? I'd recommend trying out the above example with the newest version of flwr. 

Closing this issue for now.
