### ISSUE TITLE
Is the intellectual property of the algorithms protected in flower?

### ISSUE THREAD

**Issue by Sreyashi-Bhattacharjee** [adap/flower#1840]
### Is the intellectual property of the algorithms protected in flower?

Hi, if we want to implement our custom algorithms or variation of an existing one, is the intellectual property (IP) of the algorithm protected?

**Comment by WilliamLindskog** [comment]
Hi @Sreyashi-Bhattacharjee, 

thank you for your question. Are you referring to general machine learning models or federated (aggregation) algorithms?

**Comment by WilliamLindskog** [comment]
Hi again, 

the only license that you need to consider is Apache License 2.0 that Flower is under.
