### ISSUE TITLE
Giving weights to the contribution of each client

### ISSUE THREAD

**Issue by ArminCod3r** [adap/flower#1871]
Hi,

How can the effect of each client on the global model be set? (in heterogeneous environment)
For example:
`weights = {"client1": 0.4, "client2": 0.3, "client3": 0.3}`

Thanks

**Comment by urwithajit9** [comment]
Hi,
For theoretical understanding, you can look into the following paper, "Weighted Averaging Federated Learning Based on Example Forgetting Events in Label Imbalanced Non-IID ". 

To adopt weight in averaging, you need to 1) modify the strategy, say FedAvg, and get and get parameters() method to collect weight from the client. There are good tutorials on this topic in the Flower document. 

Let me know if you need more help.

**Comment by WilliamLindskog** [comment]
Closing this as it seems to have been resolved.
