### ISSUE TITLE
How to filter illegal clients by customized cid?

### ISSUE THREAD

**Issue by wilile26811249** [adap/flower#1904]
### What is your question?

Thank you for your wonderful work.

I would like to ask some questions, but due to information security factors, it is necessary to filter out clients with illegal connections. Therefore, I hope to block them through the CID in the ClientProxy register to prevent any harm to the service.

Currently, the self.cid variable is given to the customized Client class. However, the CID obtained by the ClientManager on the server side is the IP location (e.g., ipv4:127.0.0.1:port). How can I customize the CID? Thank you.

Related questions: https://github.com/orgs/adap/discussions/1624

**Comment by WilliamLindskog** [comment]
Hi @wilile26811249 

Thanks for raising this. Is this still an issue that you are experiencing?

**Comment by WilliamLindskog** [comment]
Using the [Flower Authentication example](https://github.com/adap/flower/tree/main/examples/flower-authentication) is a great way to address this requirement. It provides a robust framework for verifying clients before they can register or interact with the server.

In this example, you can implement client authentication using secure tokens or certificates, which effectively ensures that only trusted clients can connect. The authentication logic can be extended to filter clients based on their CID, rejecting any that don’t meet your security criteria. 

I recommend starting with this example and adapting it to your specific needs for CID-based filtering. Closing this issue for now.
