### ISSUE TITLE
Are client ids synchronized across federated training rounds?

### ISSUE THREAD

**Issue by aqibsaeed** [adap/flower#1910]
### What is your question?

Hi,

Could you please confirm whether client ids, i.e., `self.cid` are synchronized across federated rounds? I want to make sure that the client that has been assigned id = 1 in the first round is the same client in the next round.

```
class FlowerClient(fl.client.NumPyClient):
    def __init__(self, cid, net, trainloader, valloader):
        self.cid = cid
```

Thanks in advance.

**Comment by noah822** [comment]
Kind of hard to define the wording ''synchronized'' in the context of ``flwr``. To my best knowledge, at each global round, ``client_fn(cid)`` will gets invoked, if you are using ``simulation`` mode, which is saying that new ``Client`` instance will be created at each round. You can not rely on ``flwr`` to store stateful data associated with each ``Client``, which is not guaranteed, instead you need to handle that by yourself, for example write/read to/from files. Please check [official doc](https://flower.dev/docs/apiref-flwr.html#flwr.simulation.start_simulation) for further detail, see specification for ``client_fn``. 
Those are just my personal understanding for your question.
