### ISSUE TITLE
differential-privacy_server_adaptive_clipping

### ISSUE THREAD

**Issue by HsinYaoHsu** [adap/flower#1915]
### Describe the bug

Hi there, I would want to ask the dp_norm_bit didn't get by client_proxy.cid in ipv4, I didn't know whats wrong from this issue. Is anyone can give advice and fixed it. Thanks

### Steps/Code to Reproduce

strategy_avg = fl.server.strategy.FedAvg(
    fraction_fit=1,
    fraction_evaluate=1,
    min_fit_clients=3,
    min_evaluate_clients=3,
    min_available_clients=3,evaluate_metrics_aggregation_fn=weighted_average,on_fit_config_fn=get_on_fit_config_fn()
)

strategy_dpfixed = fl.server.strategy.DPFedAvgFixed(strategy_avg, 3, clip_norm = 0.5, noise_multiplier = 0.01, server_side_noising = True)

strategy = fl.server.strategy.DPFedAvgAdaptive(strategy_dpfixed, 3, noise_multiplier = 0.01, server_side_noising = True)

fl.server.start_server(
        server_address="localhost:8080",
        config=fl.server.ServerConfig(num_rounds=10),
        grpc_max_message_length = 1024*1024*1024,
        strategy=strategy,
    )

Exception                                 Traceback (most recent call last)
/tmp/ipykernel_4198/2943627375.py in <module>
     45         config=fl.server.ServerConfig(num_rounds=10),
     46         grpc_max_message_length = 1024*1024*1024,
---> 47         strategy=strategy,
     48     )

~/anaconda3/envs/nilm_project/lib/python3.7/site-packages/flwr/server/app.py in start_server(server_address, server, config, strategy, client_manager, grpc_max_message_length, certificates)
    176     hist = _fl(
    177         server=initialized_server,
--> 178         config=initialized_config,
    179     )
    180 

~/anaconda3/envs/nilm_project/lib/python3.7/site-packages/flwr/server/app.py in _fl(server, config)
    215 ) -> History:
    216     # Fit model
--> 217     hist = server.fit(num_rounds=config.num_rounds, timeout=config.round_timeout)
    218     log(INFO, "app_fit: losses_distributed %s", str(hist.losses_distributed))
    219     log(INFO, "app_fit: metrics_distributed_fit %s", str(hist.metrics_distributed_fit))

~/anaconda3/envs/nilm_project/lib/python3.7/site-packages/flwr/server/server.py in fit(self, num_rounds, timeout)
    104         for current_round in range(1, num_rounds + 1):
    105             # Train model and replace previous global model
--> 106             res_fit = self.fit_round(server_round=current_round, timeout=timeout)
    107             if res_fit:
    108                 parameters_prime, fit_metrics, _ = res_fit  # fit_metrics_aggregated

~/anaconda3/envs/nilm_project/lib/python3.7/site-packages/flwr/server/server.py in fit_round(self, server_round, timeout)
    242             Optional[Parameters],
    243             Dict[str, Scalar],
--> 244         ] = self.strategy.aggregate_fit(server_round, results, failures)
    245 
    246         parameters_aggregated, metrics_aggregated = aggregated_result

~/anaconda3/envs/nilm_project/lib/python3.7/site-packages/flwr/server/strategy/dpfedavg_adaptive.py in aggregate_fit(self, server_round, results, failures)
    117             return None, {}
    118         new_global_model = super().aggregate_fit(server_round, results, failures)
--> 119         self._update_clip_norm(results)
    120         return new_global_model

~/anaconda3/envs/nilm_project/lib/python3.7/site-packages/flwr/server/strategy/dpfedavg_adaptive.py in _update_clip_norm(self, results)
     92             if "dpfedavg_norm_bit" not in fit_res.metrics:
     93                 raise Exception(
---> 94                     f"Indicator bit not returned by client with id {client_proxy.cid}."
     95                 )
     96             if fit_res.metrics["dpfedavg_norm_bit"]:

Exception: Indicator bit not returned by client with id ipv4:127.0.0.1:58250.

### Expected Results

should connect successful

### Actual Results

It doesn't work for connecting

**Comment by WilliamLindskog** [comment]
The server is unable to find `dpfedavg_norm_bit` because the client does not include it in the metrics dictionary during the fit phase. You can modify the client implementation to compute and return this metric to resolve the issue. 

However, the current [differential privacy example](https://github.com/adap/flower/tree/main/examples/fl-dp-sa) uses similar code. I tested it and it doesn't throw such error. Please consider using this example to tweak your code. 

Closing this issue for now.
