### ISSUE TITLE
GPU OOM problem. GPU memory not cleared after each of the client finishes training even after one simulation round ends

### ISSUE THREAD

**Issue by noah822** [adap/flower#1942]
### What is your question?

I am running my flower instance with 10 clients, models of which are written in PyTorch and one CUDA card with round 24GB RAM.
When monitoring my dashboard,  I found that the memory used by each of client can not be properly released, double-checked by ``nvidia-smi``. The framework will terminate after running for a while because GPU hits its memory budget. There are two major problems

- In one simulation round, the memory used by each of the client cannot be released after they finish their local training. For my setting, each client roughly occupies 2G RAM. I've tried to tune the ``client_resources`` passed to ``start_simulation`` function to see what happens if I fit each of the client sequentially into my GPU, specifically I set ``{"num_gpus : 1"}``. It turns out that when the second client starts training, RAM used by the first will not be released. Therefore, the memory consumption scales linearly as the number of clients involved increases.  I notice that there is an intentional design enforced by the ``ray`` backend, at least in ``ray==2.5.0``, which set ``max_calls=1`` by default when using ``@ray.remote`` with GPU. It intentionally disables actor reuse for GPU memory release purpose, so that GPU resources can be released after the task process finishes. For more detail, please refer to [ray's document](https://docs.ray.io/en/latest/ray-core/tasks/using-ray-with-gpus.html). It should be the case that when ``launch_and_fit`` finishes, GPU memory gets cleared. But I have no idea why it does not work on my machine.
 
- Another even more weird problem is, after one simulation round ends, the RAM used can not be collected. Therefore, my framework will be forced to terminate because GPU OOM after running a couple of rounds.

**Comment by noah822** [comment]
I am using ``python==3.8.10`` ,``flwr==1.4.0``, ``ray==2.5.0``
<img width="1299" alt="launch_and_fit" src="https://github.com/adap/flower/assets/103807711/970bcd1c-8932-4499-be65-0df6f9a83801">
On my ray dashboard, I noticed that there is no GPU resource/memory allocated to ``ray::launch_and_fit`` actor, which is launched by flwr, though I have passed ``client_resources={num_gpus:1}`` to ``start_simulation``. I am kind of new to ray. I would expect that ``ray::launch_and_fit`` holds the resources specified in ``client_resources`` parameter, then after client finishes its local training, this process can properly release the resources it previously occupies.

**Comment by noah822** [comment]
After further inspection, I found that ``ray::launch_and_fit`` process is indeed created when client starts to train and gets deleted after they finish their local training. I check this by monitoring the process running on my machine. However, the GPU memory is still not released. What might be the problem here? :(

**Comment by noah822** [comment]
[Some updates](https://discuss.ray.io/t/behavior-of-max-calls-of-ray-remote-by-default/11088) from the ray team. They said after decorating function with ``@ray.remote``, you can no longer overwrite ``max_calls`` parameter in ``.options()`` , which is exactly what I am saying in possibility 1 of my previous post. 

Therefore, to accommodate GPU configuration, a dynamic ``@ray.remote`` with ``max_calls=1`` specified is probably what you need.  I suggest use another layer of function wrapper to dynamically generate ray actors used in ``flwr``, for example ``launch_and_fit()``.

Statically setting ``max_calls=1`` for every decorator is probably not the best option, because it might drastically affect the performance of other settings, for example on cpu.

**Comment by WilliamLindskog** [comment]
Hi @noah822 

Thanks for raising this. Has this issue been resolved?

**Comment by WilliamLindskog** [comment]
Hi again, 

this seems to have been resolved by https://github.com/adap/flower/pull/1969, thus I will close this for now.
