### ISSUE TITLE
the detail in evaluation

### ISSUE THREAD

**Issue by w-sunmoon** [adap/flower#1944]
### What is your question?

I'm new to learn federated learning and I'm not clear about the evaluation operation. Are the return values the average of all clients during each round when implementing federated evaluation?

**Comment by WilliamLindskog** [comment]
Hi @w-sunmoon,

Welcome to learning federated learning with Flower!

To answer your question: during federated evaluation in Flower, the return values from each round are not necessarily the simple average of all clients’ results. Instead, Flower computes a weighted average of the evaluation metrics returned by each client, where the weights are typically based on the size of the evaluation dataset for each client.

This approach ensures that clients with larger datasets have a proportionate influence on the aggregated evaluation results, aligning with the principles of federated learning.

If you’d like to customize this behavior or better understand how it’s implemented, you can refer to the [federated evaluation](https://flower.ai/docs/framework/explanation-federated-evaluation.html). Flower allows you to modify the aggregation logic to suit your specific needs.

Closing this issue.
