### ISSUE TITLE
requirement

### ISSUE THREAD

**Issue by AomineKKL** [adap/flower#1959]
### What is your question?

ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 3), numpy~=1.21.1 and pandas==2.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy~=1.21.1
    flwr 1.4.0 depends on numpy<2.0.0 and >=1.21.0
    pandas 2.0.2 depends on numpy>=1.21.0; python_version >= "3.10"
    pandas 2.0.2 depends on numpy>=1.23.2; python_version >= "3.11"
    The user requested numpy~=1.21.1
    flwr 1.4.0 depends on numpy<2.0.0 and >=1.21.0
    pandas 2.0.1 depends on numpy>=1.21.0; python_version >= "3.10"
    pandas 2.0.1 depends on numpy>=1.23.2; python_version >= "3.11"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by WilliamLindskog** [comment]
This seems to have been resolved with new flwr versions. Closing this.

**Comment by AomineKKL** [comment]
Noted. Thank you.


On 6 Dec 2024, at 6:58 AM, William Lindskog ***@***.***> wrote:

﻿

Closed #1959<https://github.com/adap/flower/issues/1959> as completed.
