### ISSUE TITLE
Scaling fedml simulation to large models; killed due to CPU memory exhaustion  

### ISSUE THREAD

**Issue by sfarkya04** [adap/flower#1963]
### Describe the bug

Hello, 

I am trying to RUN fedml simulation on a large number of clients (about 50 in this case, but planning to go until 1000) on a relatively large model (EfficientNet) with 40 rounds of training, and 2 epochs per round. 

I have allocated 400GB memory with 79 CPU cores to run this system. My program is getting killed because of memory limitations.

### Steps/Code to Reproduce

```
import os
import math
import ray

# Make TensorFlow logs less verbose
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import pdb

stop = pdb.set_trace
import flwr as fl
import tensorflow as tf

ray.init()

NUM_CLIENTS = 50
from memory_profiler import profile


class FlwrClient(fl.client.NumPyClient):
    def __init__(self, model, x_train, y_train) -> None:
        super().__init__()
        self.model = model
        split_idx = math.floor(
            len(x_train) * 0.9
        )  # Use 10% of x_train for validation
        self.x_train, self.y_train = x_train[:split_idx], y_train[:split_idx]
        self.x_val, self.y_val = x_train[split_idx:], y_train[split_idx:]

    def get_parameters(self, config):
        return self.model.get_weights()

    def fit(self, parameters, config):
        self.model.set_weights(parameters)
        self.model.fit(self.x_train, self.y_train, epochs=2, verbose=2)
        return self.model.get_weights(), len(self.x_train), {}

    def evaluate(self, parameters, config):
        self.model.set_weights(parameters)
        loss, acc = self.model.evaluate(self.x_val, self.y_val, verbose=2)
        return loss, len(self.x_val), {"accuracy": acc}


def print_dict(var):
    _ = [print(k, ":", v.shape) for k, v in var.items()]


@profile
def client_fn(cid: str) -> fl.client.Client:
    # Load model

    model = tf.keras.applications.efficientnet.EfficientNetB7(include_top=False, input_shape=(32, 32, 3), 
                                                              classes=10, 
                                                              classifier_activation="softmax")
    model.compile(
        "adam", "sparse_categorical_crossentropy", metrics=["accuracy"]
    )

    # Load data partition (divide MNIST into NUM_CLIENTS distinct partitions)
    (x_train, y_train), _ = tf.keras.datasets.cifar10.load_data()
    partition_size = math.floor(len(x_train) / NUM_CLIENTS)
    idx_from, idx_to = (
        int(cid) * partition_size,
        (int(cid) + 1) * partition_size,
    )
    x_train_cid = x_train[idx_from:idx_to] / 255.0
    y_train_cid = y_train[idx_from:idx_to]

    # Create and return client
    return FlwrClient(model, x_train_cid, y_train_cid)

@profile
def main() -> None:
    # Start Flower simulation
    fl.simulation.start_simulation(
        client_fn=client_fn,
        num_clients=NUM_CLIENTS,
        client_resources={"num_cpus": 79},
        config=fl.server.ServerConfig(num_rounds=40),
        strategy=fl.server.strategy.FedAvg(
            fraction_fit=0.1,
            fraction_evaluate=0.1,
            min_fit_clients=NUM_CLIENTS,
            min_evaluate_clients=NUM_CLIENTS,
            min_available_clients=NUM_CLIENTS,
        ),
        ray_init_args={"include_dashboard": True},
    )


if __name__ == "__main__":
    main()

```

### Expected Results

Now if keep this running will eventually above code it will be killed without completion. The issue I am facing is that after the round, RAY should have cleared up the memory from the previous round but based on the memory logs the call stack is not cleared up and thus consumption keeps on increasing. I don't see a reason for keeping the previous data and not sure how clear it. 

Please let me know if there's a way to fix this, and be able to scale it up.

Thank you in advance! :)  

### Actual Results

I have attached memory consumption based on the memory profile for 1 round (Red line intersection). 
<img width="839" alt="Screen Shot 2023-06-22 at 6 05 53 PM" src="https://github.com/adap/flower/assets/75509659/b5625527-7daa-411f-b989-dd5559813fa4">

Also attached htop output from the system.  
![Screen Shot 2023-06-22 at 6 07 14 PM](https://github.com/adap/flower/assets/75509659/d5581d69-5671-4099-9b55-b2065fa5c969). 

Ray logs (memory / PID keeps on increasing) : 

<img width="1764" alt="Screen Shot 2023-06-22 at 6 25 19 PM" src="https://github.com/adap/flower/assets/75509659/b79f1519-c041-492d-ad60-4da27121f357">

**Comment by We1Hang** [comment]
Thank you for your reply, but I have checked that the latest version of flwr is 1.5.
Are you talking about the version of ray

**Comment by WilliamLindskog** [comment]
Hi @sfarkya04, @sfarkya04, 

Thank you for raising this. Are you still experiencing this issue?
