### ISSUE TITLE
Training doesn't start at the clients side

### ISSUE THREAD

**Issue by Abacus-web** [adap/flower#1994]
### What is your question?

I integrated flower in SDN topology with 3 controllers  ( one as a server running on port 6633 and the two others as client running on port 6634 and 6635) all in the same VM. When I launch the server and the clients, the training doesn't start at the client side and the server indefinitely request initial parameters from client.
please what can be the possible problem?
![client](https://github.com/adap/flower/assets/57025237/505177aa-160f-4c18-b906-9435c11a4283)
![server](https://github.com/adap/flower/assets/57025237/a5a11c09-9b2c-4990-a130-6f9ed1f7095a)

**Comment by WilliamLindskog** [comment]
The issue may stem from port conflicts, incorrect address configurations, or GRPC communication limits. First, ensure that the ports (6633, 6634, 6635) are open and not being used by other processes. You can check port availability using a command like `netstat -tuln` or `ss -tuln` to verify that no conflicts exist. 

Confirm that the clients are correctly configured to connect to the server’s address, such as `localhost:6633`, and that the server is properly listening on this port. Lastly, GRPC communication issues might arise if the `grpc_max_message_length` is too small to handle large initial parameter messages. You can increase the `grpc_max_message_length` in both the server and client configurations to ensure smooth communication.

Closing this issue for now.
