### ISSUE TITLE
FedPer

### ISSUE THREAD

**Issue by jafermarq** [adap/flower#2023]
# FedPer

* **Title:** Federated Learning with Personalization Layers
* **Venue:** ArXiv (highly popular)
* **Link to paper:** https://arxiv.org/abs/1912.00818

## Do you want to work on this baseline? 

> 🌻 Check everything about the `Summer of Reproducibility` on [`flower.dev/summer`](https://flower.dev/summer/)

> All available baselines are listed in the [Summer of Reproducibility Dashboard](https://github.com/orgs/adap/projects/6/) and also in the [GitHub Issues with the `summer-of-reproducibility` label](https://github.com/adap/flower/labels/summer-of-reproducibility). The content is the same.

> 📝 It is advised to complete these steps before your start working on your code. But if you can't wait to implement your baseline with Flower (we totally understand it 😄), please ensure you follow the steps on [how to contribute a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline).

What follows are the steps 1 & 2 in the Summer of Reproducibility instructions.

### 1. Join the Summer of Reproducibility program
- [x] Join the [Flower Slack](https://flower.dev/join-slack/) and say _"hi! 👋"_ in the channel `#summer-of-reproducibility`.
- [x] Pick a baseline from our curated list **<---------------------------------------- [you are doing this now]**
### 2. Define the scope of your contribution
- [x] **What are you going to reproduce?** Add a comment to your issue and tell us about your plan regarding this baseline: what experiments from the paper are you reproducing?, for which datasets ? the more details you provide us with the better !
- [x] **Check if you are eligible for a reward**. 
    > As we have to comply with US/EU regulations, we have checked that individual contributors based on these countries or territories are eligible: Australia, Austria, Belgium, Bulgaria, Canada, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Gibraltar, Greece, Hong Kong SAR China, Hungary, India, Ireland, Italy, Japan, Latvia, Liechtenstein, Lithuania, Luxembourg, Malta, Mexico, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, South Korea, Spain, Sweden, Switzerland, Thailand, United Arab emirates, United Kingdom United States.

    If where you are based is not on the list, please send us an email (`summer@flower.dev`) letting us know a bit about yourself (where are you currently based?, are you a university student? do you work at a public institution?). Please tell us the baselines you are interested in implementing (i.e. tell us your GitHub issue if you have crated one). We will reach back to you.
- [x] We will discuss with you about your contribution plan, if it sounds like a substantial enough contribution according to the Summer of Reproducibility rules (check our website [flower.dev/summer](https://flower.dev/summer/)), you'll get the OK from us to start working on your baseline!

## What happens next?

- [x] This item will be moved to the `In Progress` stage by a member of the Flower Team.

- [x] Follow the [instructions for creating a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline) which will guide you through the process step-by-step.

## Is something wrong or not clear ?
* Ask a question directly in your issue.
* Reach out to us via the [Flower Slack](https://flower.dev/join-slack/) and ask your question in the #summer-of-reproducibility channel
* Check all the details (including FAQ) in the Summer of Reproducibility website: flower.dev/summer

**Comment by WilliamLindskog** [comment]
Hi there! 

I'd like to work on FedPer as a baseline. My idea is to use the same datasets (CIFAR-10/100 and FLICKER-AES, and the same models implemented (MobileNet-v1 and ResNet-34). The data partitions, hyperparameters and number of base vs. personalization layers will be replicated. 

My plan is to gather the data, look at their code and see how I can implement in for Flower, and thereafter add experiment set-up and configuration. 

/W

**Comment by jafermarq** [comment]
Hi @WilliamLindskog, It's nice to see you want to work on `FedPer`! One question about your contribution plan: could you point us to the Figures you plan to replicate? One idea would be to focus on Figure 2, 4 and 7 (including also the `FedAvg` results -- the  point of reference in the results for `FedPer`)

**Comment by WilliamLindskog** [comment]
Hi @jafermarq, I think you're right. I intend to replicate figures 2, 4, 7, 8. The other ones are somewhat difficult to interpret (e.g. Figure 3) and the graphs in which linear layers are included seem quite messy. I would mainly replicate `FedPer`'s results for these figures and use `FedAvg` as baseline. For `FedPer`, I will include results as in for example Figure 4a in which they include results from a varying amount of personalization layers etc.

**Comment by jafermarq** [comment]
Hi @WilliamLindskog, thanks for the details. This sounds like a good plan. Now regarding the second point in Step 2 above, I assume you are based in one of the countries shown in the list? , i.e., making you eligible for a reward once all steps for `FedPer` are successfully completed. Could you please confirm? Then, i'll make you the _assignee_ of this issue and you'd be good to go onto step 3 🙌

**Comment by WilliamLindskog** [comment]
Hi @jafermarq, yes. I am based in Germany 👍🏽

**Comment by jafermarq** [comment]
@WilliamLindskog , amazing! The you are all set. I've ✅ all the points related to Step 1 and Step 2 above and now you are the _assignee_ for `FedPer`. I've moved this item to "In Progress" status. Please take a look into the steps following the link shown in _What Happens Next ?_ section above in the description of this GitHub issue.

Looking forward to see `FedPer` in action! Don't hesitate to reach back to me if you have some doubts about the process or technical doubts regarding Flower. I'm easily reachable in the Flower Slack.

**Comment by jafermarq** [comment]
Congratulations @WilliamLindskog your baseline has been merged. We'll follow up with you soon to complete your _Summer of Reproducibility_ journey 😄 !
