### ISSUE TITLE
FedPara

### ISSUE THREAD

**Issue by jafermarq** [adap/flower#2031]
# FedPara

* **Title:** FedPara: Low-rank Hadamard Product for Communication-Efficient Federated Learning
* **Venue:** ICLR 2022
* **Link to paper:** https://openreview.net/forum?id=d71n4ftoCBy

## Do you want to work on this baseline? 

> 🌻 Check everything about the `Summer of Reproducibility` on [`flower.dev/summer`](https://flower.dev/summer/)

> All available baselines are listed in the [Summer of Reproducibility Dashboard](https://github.com/orgs/adap/projects/6/) and also in the [GitHub Issues with the `summer-of-reproducibility` label](https://github.com/adap/flower/labels/summer-of-reproducibility). The content is the same.

> 📝 It is advised to complete these steps before your start working on your code. But if you can't wait to implement your baseline with Flower (we totally understand it 😄), please ensure you follow the steps on [how to contribute a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline).

What follows are the steps 1 & 2 in the Summer of Reproducibility instructions.

### 1. Join the Summer of Reproducibility program
- [x] Join the [Flower Slack](https://flower.dev/join-slack/) and say _"hi! 👋"_ in the channel `#summer-of-reproducibility`.
- [x] Pick a baseline from our curated list **<---------------------------------------- [you are doing this now]**
### 2. Define the scope of your contribution
- [x] **What are you going to reproduce?** Add a comment to your issue and tell us about your plan regarding this baseline: what experiments from the paper are you reproducing?, for which datasets ? the more details you provide us with the better !
- [x] **Check if you are eligible for a reward**. 
    > As we have to comply with US/EU regulations, we have checked that individual contributors based on these countries or territories are eligible: Australia, Austria, Belgium, Bulgaria, Canada, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Gibraltar, Greece, Hong Kong SAR China, Hungary, India, Ireland, Italy, Japan, Latvia, Liechtenstein, Lithuania, Luxembourg, Malta, Mexico, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, South Korea, Spain, Sweden, Switzerland, Thailand, United Arab emirates, United Kingdom United States.

    If where you are based is not on the list, please send us an email (`summer@flower.dev`) letting us know a bit about yourself (where are you currently based?, are you a university student? do you work at a public institution?). Please tell us the baselines you are interested in implementing (i.e. tell us your GitHub issue if you have crated one). We will reach back to you.
- [x] We will discuss with you about your contribution plan, if it sounds like a substantial enough contribution according to the Summer of Reproducibility rules (check our website [flower.dev/summer](https://flower.dev/summer/)), you'll get the OK from us to start working on your baseline!

## What happens next?

- [x] This item will be moved to the `In Progress` stage by a member of the Flower Team.

- [x] Follow the [instructions for creating a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline) which will guide you through the process step-by-step.

## Is something wrong or not clear ?
* Ask a question directly in your issue.
* Reach out to us via the [Flower Slack](https://flower.dev/join-slack/) and ask your question in the #summer-of-reproducibility channel
* Check all the details (including FAQ) in the Summer of Reproducibility website: flower.dev/summer

**Comment by yehias21** [comment]
Hi @jafermarq I am Yahia Shaaban, a cs graduate passionate about Machine learning research. I have worked in machine learning research in medical, 5G, knowledge graph and control systems. Recently, I have worked on inerating secure aggreagation and personalization scheme in federated recommended systems. 
I am keen on implementing/integrating FedPara specifically cifar 10, 100 and minst dataset and vgg16 as model.( table 2-a and figure 5 scenario 3
)
Unfortunately, I am not in the listed countries. I am aiming at teaming up with @omarmoo5

**Comment by jafermarq** [comment]
hi @yehias21, we have recently (yesterday!!) updated the list of countries to over 100. please take a look at our FAQ: https://flower.dev/summer/#faq

**Comment by yehias21** [comment]
That's fantastic. I am eligible then :)

**Comment by jafermarq** [comment]
Great! @yehias21, When reproducing the CIFAR-10/100 for Table 2-a, would it make sense to also save per-round information so to generate the corresponding plots in Figure 3? (i.e. line plots and the bar plots for CIFAR-10/100 iid/non-iid -- I believe these do not require running any additional experiments). For Figure 5, how about also including scenario a? That uses the standard FEMNIST dataset and more evidently shows the superiority of `FedPara` over `FedPer` than scenario c.

Let me know what your thoughts are!

**Comment by yehias21** [comment]
Agreed! Okay will add then to my plan

**Comment by jafermarq** [comment]
Great! Then `FedPara` is all yours to implement with Flower. I have now ✅ all points above in Step 1 and 2, added you as the _assignee_ of this issue, and moved this baseline to _In Progress_ status. Following the link in the _What happens Next?_ section above you'll find a guide on how to start with your contribution. Feel free to reach out to me and the other contributors via the Flower slack. As a short reminder, the Flower _Summer of Reproducibility_ runs until the end of September. 

Looking forward to see `FedPara` in action! 🚀

**Comment by jafermarq** [comment]
Hi @yehias21,

This is just a gentle reminder that the Flower *Summer of Reproducibility* is ending at the end of the month. With just a little more than 3 weeks to go, we are excited to see quite a few baselines well ahead in the process with [their respective PRs close to ready.](https://github.com/adap/flower/pulls?q=is%3Apr+is%3Aopen+label%3Asummer-of-reproducibility) If your PR is already on the list, great !! Please make sure the PR is linked to this issue (you just need to copy the URL of this issue somewhere in the main message of your PR). Ping me when you'd like me to take a look.

Also, make sure you keep an eye:eyes: on the **#summer-of-reproducibility** channel in the Flower Slack. I’ll announce very soon a new (the third!) round of 1:1 ask-me-anything sessions to help _Summer of Reproducibility_ contributors like yourself to meet the deadline. Please consider booking a time slot if you want to chat with me about your baseline, potential issues you have making your code run, how to open a PR, doubts about what to include in your readme, how to use Hydra configs more effective, etc … all questions are welcome!!

**Comment by yehias21** [comment]
Hello Javier, I have finalized the implementation of fedpara and tested on cifar 10 and cifar 100 datasets for IID and non-iid schemes.
Regarding the pFedpara I want to ask which scenario to implement.

**Comment by jafermarq** [comment]
Congratulations @yehias21 your baseline has been merged!! We'll follow up with you soon to complete your _Summer of Reproducibility_ journey 😄 !
