### ISSUE TITLE
DepthFL

### ISSUE THREAD

**Issue by jafermarq** [adap/flower#2038]
# DepthFL

* **Title:** DepthFL : Depthwise Federated Learning for Heterogeneous Clients
* **Venue:** ICLR 2023
* **Link to paper:** https://openreview.net/forum?id=pf8RIZTMU58

## Do you want to work on this baseline? 

> 🌻 Check everything about the `Summer of Reproducibility` on [`flower.dev/summer`](https://flower.dev/summer/)

> All available baselines are listed in the [Summer of Reproducibility Dashboard](https://github.com/orgs/adap/projects/6/) and also in the [GitHub Issues with the `summer-of-reproducibility` label](https://github.com/adap/flower/labels/summer-of-reproducibility). The content is the same.

> 📝 It is advised to complete these steps before your start working on your code. But if you can't wait to implement your baseline with Flower (we totally understand it 😄), please ensure you follow the steps on [how to contribute a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline).

What follows are the steps 1 & 2 in the Summer of Reproducibility instructions.

### 1. Join the Summer of Reproducibility program
- [x] Join the [Flower Slack](https://flower.dev/join-slack/) and say _"hi! 👋"_ in the channel `#summer-of-reproducibility`.
- [x] Pick a baseline from our curated list **<---------------------------------------- [you are doing this now]**
### 2. Define the scope of your contribution
- [x] **What are you going to reproduce?** Add a comment to your issue and tell us about your plan regarding this baseline: what experiments from the paper are you reproducing?, for which datasets ? the more details you provide us with the better !
- [x] **Check if you are eligible for a reward**. 
    > As we have to comply with US/EU regulations, we have checked that individual contributors based on these countries or territories are eligible: Australia, Austria, Belgium, Bulgaria, Canada, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Gibraltar, Greece, Hong Kong SAR China, Hungary, India, Ireland, Italy, Japan, Latvia, Liechtenstein, Lithuania, Luxembourg, Malta, Mexico, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, South Korea, Spain, Sweden, Switzerland, Thailand, United Arab emirates, United Kingdom United States.

    If where you are based is not on the list, please send us an email (`summer@flower.dev`) letting us know a bit about yourself (where are you currently based?, are you a university student? do you work at a public institution?). Please tell us the baselines you are interested in implementing (i.e. tell us your GitHub issue if you have crated one). We will reach back to you.
- [x] We will discuss with you about your contribution plan, if it sounds like a substantial enough contribution according to the Summer of Reproducibility rules (check our website [flower.dev/summer](https://flower.dev/summer/)), you'll get the OK from us to start working on your baseline!

## What happens next?

- [x] This item will be moved to the `In Progress` stage by a member of the Flower Team.

- [x] Follow the [instructions for creating a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline) which will guide you through the process step-by-step.

## Is something wrong or not clear ?
* Ask a question directly in your issue.
* Reach out to us via the [Flower Slack](https://flower.dev/join-slack/) and ask your question in the #summer-of-reproducibility channel
* Check all the details (including FAQ) in the Summer of Reproducibility website: flower.dev/summer

**Comment by Peterpan828** [comment]
**Scope of the contribution**

I aim to replicate the main results presented in the paper, focusing on reproducing the results found in Table 2,3 and 4. 

- **Table 2** compares DepthFL and HeteroFL with Exclusive Learning using three datasets (MNIST, CIFAR100, and Tiny-ImageNet)
- **Table 3** evaluates the performance of global sub-models from different algorithms (Exclusive learning, HeteroFL, SHeteroFL, InclusiveFL, DepthFL) using the CIFAR100 Dataset.
- **Table 4** verifies the effectiveness of self-distillation in both IID / non-IID data distribution settings, using the CIFAR100 and Tiny-ImageNet Datasets.

**Eligibility**
✔

**Comment by jafermarq** [comment]
Hi @Peterpan828, it's nice you are interested in reproducing the results in the `DepthFL`. But this baseline has been assigned to the authors of the paper ( currently waiting for them to propose a contribution plan). Are you one of the authors?

**Comment by Peterpan828** [comment]
Hi @jafermarq 

Yes, I am one of the authors of the DepthFL paper.

**Comment by jafermarq** [comment]
Amazing! Thank you for confirming @Peterpan828. Your contribution plan makes sense :100:. I have now ✅ all the point in Step 1 & 2, and added you as the _assignee_ to this github issue. If any other of your collaborators in the paper would like to also be assigned to this issue, please let them know that they need to leave a comment here (else, GitHub doesn't allow me to choose them as _assignees_).  You can find the instructions on how to start with the code following the link in the _What happens Next?_ section above. If you have any questions feel free to ask them in the Flower Slack, if you haven't joined already you can do so following this link https://flower.dev/join-slack/

As a brief reminder, the _Summer of Reproducibility_ runs until the end of September and by then, we expect the pull requests with the code to be completed and approved. (more info in our website: [flower.dev/summer](https://flower.dev/summer/)

Looking forward to see `DepthFL` in action!

**Comment by jafermarq** [comment]
Congratulations @Peterpan828 your baseline has been merged. We'll follow up with you soon to complete your _Summer of Reproducibility_ journey 😄 !
