### ISSUE TITLE
FedMLB

### ISSUE THREAD

**Issue by jafermarq** [adap/flower#2048]
# FedMLB

* **Title:** Multi-Level Branched Regularization for Federated Learning
* **Venue:** ICML 2021
* **Link to paper:** https://proceedings.mlr.press/v162/kim22a.html

## Do you want to work on this baseline? 

> 🌻 Check everything about the `Summer of Reproducibility` on [`flower.dev/summer`](https://flower.dev/summer/)

> All available baselines are listed in the [Summer of Reproducibility Dashboard](https://github.com/orgs/adap/projects/6/) and also in the [GitHub Issues with the `summer-of-reproducibility` label](https://github.com/adap/flower/labels/summer-of-reproducibility). The content is the same.

> 📝 It is advised to complete these steps before your start working on your code. But if you can't wait to implement your baseline with Flower (we totally understand it 😄), please ensure you follow the steps on [how to contribute a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline).

What follows are the steps 1 & 2 in the Summer of Reproducibility instructions.

### 1. Join the Summer of Reproducibility program
- [x] Join the [Flower Slack](https://flower.dev/join-slack/) and say _"hi! 👋"_ in the channel `#summer-of-reproducibility`.
- [x] Pick a baseline from our curated list **<---------------------------------------- [you are doing this now]**
### 2. Define the scope of your contribution
- [x] **What are you going to reproduce?** Add a comment to your issue and tell us about your plan regarding this baseline: what experiments from the paper are you reproducing?, for which datasets ? the more details you provide us with the better !
- [x] **Check if you are eligible for a reward**. 
    > As we have to comply with US/EU regulations, we have checked that individual contributors based on these countries or territories are eligible: Australia, Austria, Belgium, Bulgaria, Canada, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Gibraltar, Greece, Hong Kong SAR China, Hungary, India, Ireland, Italy, Japan, Latvia, Liechtenstein, Lithuania, Luxembourg, Malta, Mexico, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, South Korea, Spain, Sweden, Switzerland, Thailand, United Arab emirates, United Kingdom United States.

    If where you are based is not on the list, please send us an email (`summer@flower.dev`) letting us know a bit about yourself (where are you currently based?, are you a university student? do you work at a public institution?). Please tell us the baselines you are interested in implementing (i.e. tell us your GitHub issue if you have crated one). We will reach back to you.
- [x] We will discuss with you about your contribution plan, if it sounds like a substantial enough contribution according to the Summer of Reproducibility rules (check our website [flower.dev/summer](https://flower.dev/summer/)), you'll get the OK from us to start working on your baseline!

## What happens next?

- [x] This item will be moved to the `In Progress` stage by a member of the Flower Team.

- [x] Follow the [instructions for creating a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline) which will guide you through the process step-by-step.

## Is something wrong or not clear ?
* Ask a question directly in your issue.
* Reach out to us via the [Flower Slack](https://flower.dev/join-slack/) and ask your question in the #summer-of-reproducibility channel
* Check all the details (including FAQ) in the Summer of Reproducibility website: flower.dev/summer

**Comment by alessiomora** [comment]
Hi. I would like to provide the implementation of this paper. I would like to firstly focus on reproducing the results for CIFAR-100 (with distribution-based label skew, Dirichlet concentration param \in [0.3, 0.6]) with ResNet-18 as model architecture.

**Comment by jafermarq** [comment]
Hey @alessiomora , great to hear you want to reproduce FedMLB. 
Could you point us to the specific table/plot for those experiments you mention? is this for the 100 client or 500client setup? also, what point of reference would you include for FedMLB? (i.e. what baseline in the FedMLB paper) -- we have some info about this in the first point in our FAQ: https://flower.dev/summer/#faq

**Comment by alessiomora** [comment]
Hi @jafermarq. I will start by reproducing the left part of Table 1 in the paper, that is the results for CIFAR-100 with (a) Moderate-scale with Dir(0.3), 100 clients, 5% participation and (b) Large-scale with Dir(0.3), 500 clients, 2% participation, for FedAvg and FedMLB.
I can also reproduce Table 2 (for FedAvg, FedMLB and FedAvg+KD).
Then, I am planning to reproduce the results with Tiny-Imagenet as well (the right part of Table 1).

**Comment by jafermarq** [comment]
Hi @alessiomora This sounds perfect! I've ticked some of the check list above in the issue. Please take a look at the info regarding the point in step 2 about reward eligibility. If all looks good, feel free to ✅ it.

**Comment by alessiomora** [comment]
Hi @jafermarq. I confirm I am based in a territory among the ones listed above (Italy).

**Comment by jafermarq** [comment]
Many thanks for confirming! Everything in step 1 and 2 is completed. Looking forward to see `FedMLB` in action 🙌.

**Comment by jafermarq** [comment]
Congratulations @alessiomora! your baseline has been merged. We'll follow up with you soon to complete your _Summer of Reproducibility_ journey 😄 !
