### ISSUE TITLE
MOON

### ISSUE THREAD

**Issue by jafermarq** [adap/flower#2049]
# MOON

* **Title:** Model-Contrastive Federated Learning
* **Venue:** CVPR 2021
* **Link to paper:** https://openaccess.thecvf.com/content/CVPR2021/html/Li_Model-Contrastive_Federated_Learning_CVPR_2021_paper.html

## Do you want to work on this baseline? 

> 🌻 Check everything about the `Summer of Reproducibility` on [`flower.dev/summer`](https://flower.dev/summer/)

> All available baselines are listed in the [Summer of Reproducibility Dashboard](https://github.com/orgs/adap/projects/6/) and also in the [GitHub Issues with the `summer-of-reproducibility` label](https://github.com/adap/flower/labels/summer-of-reproducibility). The content is the same.

> 📝 It is advised to complete these steps before your start working on your code. But if you can't wait to implement your baseline with Flower (we totally understand it 😄), please ensure you follow the steps on [how to contribute a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline).

What follows are the steps 1 & 2 in the Summer of Reproducibility instructions.

### 1. Join the Summer of Reproducibility program
- [x] Join the [Flower Slack](https://flower.dev/join-slack/) and say _"hi! 👋"_ in the channel `#summer-of-reproducibility`.
- [x] Pick a baseline from our curated list **<---------------------------------------- [you are doing this now]**
### 2. Define the scope of your contribution
- [x] **What are you going to reproduce?** Add a comment to your issue and tell us about your plan regarding this baseline: what experiments from the paper are you reproducing?, for which datasets ? the more details you provide us with the better !
- [x] **Check if you are eligible for a reward**. 
    > As we have to comply with US/EU regulations, we have checked that individual contributors based on these countries or territories are eligible: Australia, Austria, Belgium, Bulgaria, Canada, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Gibraltar, Greece, Hong Kong SAR China, Hungary, India, Ireland, Italy, Japan, Latvia, Liechtenstein, Lithuania, Luxembourg, Malta, Mexico, Netherlands, New Zealand, Norway, Poland, Portugal, Romania, Singapore, Slovakia, Slovenia, South Korea, Spain, Sweden, Switzerland, Thailand, United Arab emirates, United Kingdom United States.

    If where you are based is not on the list, please send us an email (`summer@flower.dev`) letting us know a bit about yourself (where are you currently based?, are you a university student? do you work at a public institution?). Please tell us the baselines you are interested in implementing (i.e. tell us your GitHub issue if you have crated one). We will reach back to you.
- [x] We will discuss with you about your contribution plan, if it sounds like a substantial enough contribution according to the Summer of Reproducibility rules (check our website [flower.dev/summer](https://flower.dev/summer/)), you'll get the OK from us to start working on your baseline!

## What happens next?

- [x] This item will be moved to the `In Progress` stage by a member of the Flower Team.

- [ ] Follow the [instructions for creating a new baseline](https://github.com/adap/flower/tree/main/baselines#contributing-a-new-baseline) which will guide you through the process step-by-step.

## Is something wrong or not clear ?
* Ask a question directly in your issue.
* Reach out to us via the [Flower Slack](https://flower.dev/join-slack/) and ask your question in the #summer-of-reproducibility channel
* Check all the details (including FAQ) in the Summer of Reproducibility website: flower.dev/summer

**Comment by QinbinLi** [comment]
Hi @jafermarq .

I'm Qinbin Li from UC Berkeley. I'd like to reproduce the main results of Table 1 of MOON paper (https://openaccess.thecvf.com/content/CVPR2021/papers/Li_Model-Contrastive_Federated_Learning_CVPR_2021_paper.pdf). I'll cover results of MOON and FedAvg on datasets CIFAR-10 and CIFAR-100 to meet the requirements. I'll also cover baseline FedProx and dataset Tiny-ImageNet if time allows. Thanks!

**Comment by jafermarq** [comment]
Hi @QinbinLi , great to have you onboard! 

Table 1 with CIFAR-10/100 and FedAvg as baseline sounds like a good plan! It would be great if you could include FedProx as well.

**Comment by jafermarq** [comment]
Hey @QinbinLi, let me know if you think including also the CIFAR-10/100 results as shown in Figure 6 and Figure 7. Figure 6 is just plotting the per-round performance metrics from running your experiments for Table1. Then Figure 7, could be interesting to include as a simple ablation study. So do you think you could also reproduce Fig6 & 7 for CIFAR-10/100 MOON and FedAvg. 

Let me know and all then tick all the points above and you'll be good to go!

**Comment by QinbinLi** [comment]
Hi @jafermarq ,

Thank you! I can also include FedProx and Figure 6. Can I reproduce Fig 8 instead of Fig 7? I think changing #parties (Fig 8) is more impressive and interesting.

**Comment by jafermarq** [comment]
Hi @QinbinLi , absolutely! Figure 8 looks good too. I have now ✅ all points for Step 1 & 2. To start working on your baseline you just need to follow the steps described in the page after clicking on the link in the _What happens next?_ section of the Issue above. If you have any questions please reach out to me or another in the Flower Team via our Slack!

Looking forward to seeing `MOON` in action!!🙌
