### ISSUE TITLE
Broken links in README for Flower Baseline section

### ISSUE THREAD

**Issue by divyanshugit** [adap/flower#2090]
### Describe what the documentation is missing.

All the links referring to the code in the repository are broken. Since the directory structure has been updated recently.

### Suggest your improvement.

Update the links as per the current structure.

**Comment by jafermarq** [comment]
Hi @divyanshugit, following my comment to your PR #2091, i'll be closing this issue since it has been resolved with #2117. Many thanks again for spotting the broken links
