### ISSUE TITLE
Need feedback to resolve killed due to memory related issues 

### ISSUE THREAD

**Issue by heyiamdhruv** [adap/flower#2157]
### What is your question?

**I am trying ConvLSTM model with flower framework 
I want to understand below implemented code is correct considering flower framework implementation and how I can verify that weights are getting updated/**

### Code

!pip install -q flwr[simulation] torch torchvision matplotlib
!pip install tensorflow opencv-contrib-python youtube-dl moviepy pydot
!pip install git+https://github.com/TahaAnwar/pafy.git#egg=pafy
!pip install torchsummary

import os
import cv2
import math
import random
import numpy as np
import datetime as dt
import tensorflow as tf
from collections import deque
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import plot_model
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, random_split
from torchsummary import summary
import flwr as fl
from flwr.common import Metrics
from collections import OrderedDict
from typing import List, Tuple
import pafy
from moviepy.editor import *

seed_constant = 27
np.random.seed(seed_constant)
random.seed(seed_constant)
tf.random.set_seed(seed_constant)

NUM_CLIENTS = 2
CLASSES_LIST = ["WalkingWithDog", "TaiChi", "Swing", "HorseRace"]
IMAGE_HEIGHT , IMAGE_WIDTH = 64, 64
SEQUENCE_LENGTH = 20
DATASET_DIR = "/content/UCF-101"

all_classes_names = os.listdir('/content/UCF-101')
random_range = random.sample(range(len(all_classes_names)), 20)

for counter, random_index in enumerate(random_range, 1):
    selected_class_Name = all_classes_names[random_index]
    video_files_names_list = os.listdir(f'/content/UCF-101/{selected_class_Name}')
    selected_video_file_name = random.choice(video_files_names_list)
    video_reader = cv2.VideoCapture(f'/content/UCF-101/{selected_class_Name}/{selected_video_file_name}')
    _, bgr_frame = video_reader.read()
    video_reader.release()
    rgb_frame = cv2.cvtColor(bgr_frame, cv2.COLOR_BGR2RGB)
    cv2.putText(rgb_frame, selected_class_Name, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
    plt.subplot(5, 4, counter);plt.imshow(rgb_frame);plt.axis('off')

def frames_extraction(video_path):
    frames_list = []
    video_reader = cv2.VideoCapture(video_path)
    video_frames_count = int(video_reader.get(cv2.CAP_PROP_FRAME_COUNT))
    skip_frames_window = max(int(video_frames_count/SEQUENCE_LENGTH), 1)

    for frame_counter in range(SEQUENCE_LENGTH):
        video_reader.set(cv2.CAP_PROP_POS_FRAMES, frame_counter * skip_frames_window)
        success, frame = video_reader.read()
        if not success:
            break
        resized_frame = cv2.resize(frame, (IMAGE_HEIGHT, IMAGE_WIDTH))
        normalized_frame = resized_frame / 255
        frames_list.append(normalized_frame)

    video_reader.release()
    return frames_list

def create_dataset():
    features = []
    labels = []
    video_files_paths = []

    for class_index, class_name in enumerate(CLASSES_LIST):
        print(f'Extracting Data of Class: {class_name}')
        files_list = os.listdir(os.path.join(DATASET_DIR, class_name))
        for file_name in files_list:
            video_file_path = os.path.join(DATASET_DIR, class_name, file_name)
            frames = frames_extraction(video_file_path)

            if len(frames) == SEQUENCE_LENGTH:
                features.append(frames)
                labels.append(class_index)
                video_files_paths.append(video_file_path)

    features = np.asarray(features)
    labels = np.array(labels)

    return features, labels, video_files_paths

features, labels, video_files_paths = create_dataset()
one_hot_encoded_labels = to_categorical(labels)

features_train, features_test, labels_train, labels_test = train_test_split(features, one_hot_encoded_labels,
                                                                            test_size = 0.25, shuffle = True,
                                                                            random_state = seed_constant)

def create_convlstm_model():

    model = Sequential()
    model.add(ConvLSTM2D(filters = 1, kernel_size = (3, 3), activation = 'tanh',data_format = "channels_last", recurrent_dropout=0.2,
                         return_sequences=True, input_shape = (SEQUENCE_LENGTH,IMAGE_HEIGHT, IMAGE_WIDTH, 3)))
    model.add(MaxPooling3D(pool_size=(1, 2, 2), padding='same', data_format='channels_last'))
    model.add(TimeDistributed(Dropout(0.2)))
    model.add(ConvLSTM2D(filters = 2, kernel_size = (3, 3), activation = 'tanh', data_format = "channels_last",recurrent_dropout=0.2,
                         return_sequences=True))
    model.add(MaxPooling3D(pool_size=(1, 2, 2), padding='same', data_format='channels_last'))
    model.add(TimeDistributed(Dropout(0.2)))
    model.add(ConvLSTM2D(filters = 4, kernel_size = (3, 3), activation = 'tanh', data_format = "channels_last",
                         recurrent_dropout=0.2, return_sequences=True))
    model.add(MaxPooling3D(pool_size=(1, 2, 2), padding='same', data_format='channels_last'))
    model.add(TimeDistributed(Dropout(0.2)))
    model.add(ConvLSTM2D(filters = 8, kernel_size = (3, 3), activation = 'tanh', data_format = "channels_last",
                         recurrent_dropout=0.2, return_sequences=True))
    model.add(MaxPooling3D(pool_size=(1, 2, 2), padding='same', data_format='channels_last'))
    #model.add(TimeDistributed(Dropout(0.2)))
    model.add(Flatten())
    model.add(Dense(len(CLASSES_LIST), activation = "softmax"))

    return model

convlstm_model = create_convlstm_model()
print("Model Created Successfully!")

early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 10, mode = 'min', restore_best_weights = True)
convlstm_model.compile(loss = 'categorical_crossentropy', optimizer = 'Adam', metrics = ["accuracy"])
convlstm_model_training_history = convlstm_model.fit(x = features_train, y = labels_train, epochs = 5, batch_size = 4,
                                                     shuffle = True, validation_split = 0.2,
                                                     callbacks = [early_stopping_callback])

model_evaluation_history = convlstm_model.evaluate(features_test, labels_test)

def get_parameters(net) -> List[np.ndarray]:
    return convlstm_model.get_weights()

def set_parameters(net, parameters: List[np.ndarray]):
    convlstm_model.set_weights(parameters)

class FlowerClient(fl.client.NumPyClient):
    def __init__(self, net, features_train, features_test, labels_train, labels_test):
        self.net = net
        self.trainFeatures = features_train
        self.valFeatures = features_test
        self.trainLabels = features_train
        self.valLabels = features_test

    def get_parameters(self, config):
        return self.net.get_weights()

    def fit(self, parameters, config):
        self.net.set_weights(parameters)
        self.net.fit(x = self.trainFeatures, y = self.trainLabels, epochs = 1, verbose=2)
        return self.net.get_weights(), len(self.trainFeatures), {}

    def evaluate(self, parameters, config):
        self.net.set_weights(parameters)

        loss, accuracy = self.net.evaluate(self.valFeatures,  self.valLabels, verbose=2)
        return loss, len(self.valFeatures), {"accuracy": accuracy}

def client_fn(cid: str) -> FlowerClient:
    convlstm_model = create_convlstm_model()
    convlstm_model.compile("adam", "sparse_categorical_crossentropy", metrics=["accuracy"])

    partition_size = math.floor(len(features_train) / NUM_CLIENTS)
    idx_from, idx_to = int(cid) * partition_size, (int(cid) + 1) * partition_size
    full_x_train_cid = features_train[idx_from:idx_to] / 255.0
    full_y_train_cid = labels_train[idx_from:idx_to]

    split_idx = math.floor(len(full_x_train_cid) * 0.9)
    x_train_cid, y_train_cid = (
        full_x_train_cid[:split_idx],
        full_y_train_cid[:split_idx],
    )
    x_val_cid, y_val_cid = full_x_train_cid[split_idx:], full_y_train_cid[split_idx:]

    return FlowerClient(convlstm_model, x_train_cid, y_train_cid, x_val_cid, y_val_cid)

strategy = fl.server.strategy.FedAvg(
    fraction_fit=1.0,
    fraction_evaluate=0.5,
    min_fit_clients=2,
    min_evaluate_clients=2,
    min_available_clients=2,
)

client_resources = None
if DEVICE.type == "cuda":
    client_resources = {"num_gpus": 1}

fl.simulation.start_simulation(
    client_fn=client_fn,
    num_clients=NUM_CLIENTS,
    config=fl.server.ServerConfig(num_rounds=2),
    strategy=strategy,
    client_resources=client_resources,
)

def weighted_average(metrics: List[Tuple[int, Metrics]]) -> Metrics:
    # Multiply accuracy of each client by number of examples used
    accuracies = [num_examples * m["accuracy"] for num_examples, m in metrics]
    examples = [num_examples for num_examples, _ in metrics]

    print(accuracies)
    return {"accuracy": sum(accuracies) / sum(examples)}

strategy = fl.server.strategy.FedAvg( # Create FedAvg strategy
    fraction_fit=1.0,
    fraction_evaluate=0.5,
    min_fit_clients=2,
    min_evaluate_clients=2,
    min_available_clients=2,
    evaluate_metrics_aggregation_fn=weighted_average,
)

fl.simulation.start_simulation( # Start simulation
    client_fn=client_fn,
    num_clients=NUM_CLIENTS,
    config=fl.server.ServerConfig(num_rounds=2),
    strategy=strategy,
    client_resources=client_resources,
)

### Error 

2023-07-23 15:19:29,905	INFO worker.py:1621 -- Started a local Ray instance.
(pid=9878) 2023-07-23 15:19:37.009096: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(launch_and_get_parameters pid=9878) 2023-07-23 15:19:41.170172: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(pid=9973) 2023-07-23 15:19:45.075092: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(launch_and_fit pid=9973) 2023-07-23 15:19:48.906235: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(launch_and_fit pid=9973) 2023-07-23 15:19:50.759009: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 158269440 exceeds 10% of free system memory.
(launch_and_fit pid=9973) 2023-07-23 15:19:51.151819: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 158269440 exceeds 10% of free system memory.
(launch_and_fit pid=9973) 2023-07-23 15:19:51.465453: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 158269440 exceeds 10% of free system memory.
(launch_and_fit pid=9973) 2023-07-23 15:19:51.576092: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 158269440 exceeds 10% of free system memory.
(pid=10081) 2023-07-23 15:20:05.657422: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(launch_and_fit pid=10081) 2023-07-23 15:20:11.400926: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(launch_and_fit pid=10081) 2023-07-23 15:20:12.694145: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 158269440 exceeds 10% of free system memory.
(launch_and_fit pid=10081) 2023-07-23 15:20:13.076900: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 158269440 exceeds 10% of free system memory.
(launch_and_fit pid=10081) 2023-07-23 15:20:13.333870: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 158269440 exceeds 10% of free system memory.
(launch_and_fit pid=10081) 2023-07-23 15:20:13.445012: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 158269440 exceeds 10% of free system memory.
(pid=10186) 2023-07-23 15:20:19.187682: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(launch_and_evaluate pid=10186) 2023-07-23 15:20:25.597905: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(raylet) [2023-07-23 15:20:29,849 E 9751 9751] (raylet) node_manager.cc:3084: 3 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: b287aac2de42bef55d13e884c4bdb6cffb2d81d1dc96aa08c4633a43, IP: 172.28.0.12) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 172.28.0.12`
(raylet) 
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
(pid=10272) 2023-07-23 15:20:31.453907: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(launch_and_evaluate pid=10272) 2023-07-23 15:20:38.322482: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(pid=10375) 2023-07-23 15:20:44.095134: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(launch_and_fit pid=10375) 2023-07-23 15:20:50.321763: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(pid=10456) 2023-07-23 15:20:56.522290: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(launch_and_fit pid=10456) 2023-07-23 15:21:02.413046: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(pid=10553) 2023-07-23 15:21:09.458987: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(launch_and_evaluate pid=10553) 2023-07-23 15:21:14.693243: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(pid=10632) 2023-07-23 15:21:21.114891: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(launch_and_evaluate pid=10632) 2023-07-23 15:21:28.319856: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(raylet) [2023-07-23 15:21:29,851 E 9751 9751] (raylet) node_manager.cc:3084: 4 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: b287aac2de42bef55d13e884c4bdb6cffb2d81d1dc96aa08c4633a43, IP: 172.28.0.12) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 172.28.0.12`
(raylet) 
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.

**Comment by Protalist** [comment]
same for me

**Comment by sunyafei01** [comment]
i have the same problem

**Comment by WilliamLindskog** [comment]
Hi 

Thanks for raising this. I tried to recreate the example using below code: 

```python
import os
import cv2
import math
import random
import numpy as np
import tensorflow as tf
from collections import deque
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import ConvLSTM2D, MaxPooling3D
from tensorflow.keras.layers import TimeDistributed, Flatten, Dense
from tensorflow.keras.layers import Dropout
import matplotlib.pyplot as plt
import flwr as fl
from typing import List, Tuple

# Seed for reproducibility
seed_constant = 27
np.random.seed(seed_constant)
random.seed(seed_constant)
tf.random.set_seed(seed_constant)

# Simulation parameters
NUM_CLIENTS = 2
CLASSES_LIST = ["WalkingWithDog", "TaiChi", "Swing", "HorseRace"]
IMAGE_HEIGHT, IMAGE_WIDTH = 64, 64
SEQUENCE_LENGTH = 20

# Generate synthetic dataset
def generate_synthetic_video(class_name, num_videos=10):
    videos = []
    for _ in range(num_videos):
        video = np.random.rand(SEQUENCE_LENGTH, IMAGE_HEIGHT, IMAGE_WIDTH, 3).astype("float32")
        videos.append(video)
    return videos

def create_synthetic_dataset():
    features = []
    labels = []
    for class_index, class_name in enumerate(CLASSES_LIST):
        print(f"Generating synthetic data for class: {class_name}")
        class_videos = generate_synthetic_video(class_name, num_videos=50)
        features.extend(class_videos)
        labels.extend([class_index] * len(class_videos))
    features = np.array(features)
    labels = np.array(labels)
    return features, labels

# Create synthetic dataset
features, labels = create_synthetic_dataset()
one_hot_encoded_labels = to_categorical(labels)

# Split dataset into training and testing sets
features_train, features_test, labels_train, labels_test = train_test_split(
    features, one_hot_encoded_labels, test_size=0.25, shuffle=True, random_state=seed_constant
)

# Define ConvLSTM model
def create_convlstm_model():
    model = Sequential([
        ConvLSTM2D(filters=1, kernel_size=(3, 3), activation="tanh", recurrent_dropout=0.2,
                   return_sequences=True, input_shape=(SEQUENCE_LENGTH, IMAGE_HEIGHT, IMAGE_WIDTH, 3)),
        MaxPooling3D(pool_size=(1, 2, 2), padding="same"),
        TimeDistributed(Dropout(0.2)),
        ConvLSTM2D(filters=2, kernel_size=(3, 3), activation="tanh", recurrent_dropout=0.2, return_sequences=True),
        MaxPooling3D(pool_size=(1, 2, 2), padding="same"),
        TimeDistributed(Dropout(0.2)),
        ConvLSTM2D(filters=4, kernel_size=(3, 3), activation="tanh", recurrent_dropout=0.2, return_sequences=True),
        MaxPooling3D(pool_size=(1, 2, 2), padding="same"),
        TimeDistributed(Dropout(0.2)),
        ConvLSTM2D(filters=8, kernel_size=(3, 3), activation="tanh", recurrent_dropout=0.2, return_sequences=True),
        MaxPooling3D(pool_size=(1, 2, 2), padding="same"),
        Flatten(),
        Dense(len(CLASSES_LIST), activation="softmax")
    ])
    return model

# Create and compile model
convlstm_model = create_convlstm_model()
convlstm_model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train model
early_stopping_callback = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)
convlstm_model.fit(
    x=features_train, y=labels_train, epochs=5, batch_size=4, shuffle=True, validation_split=0.2,
    callbacks=[early_stopping_callback]
)

# Federated Learning setup
class FlowerClient(fl.client.NumPyClient):
    def __init__(self, net, train_data, train_labels, test_data, test_labels):
        self.net = net
        self.train_data = train_data
        self.train_labels = train_labels
        self.test_data = test_data
        self.test_labels = test_labels

    def get_parameters(self, config):
        return self.net.get_weights()

    def fit(self, parameters, config):
        self.net.set_weights(parameters)
        self.net.fit(self.train_data, self.train_labels, epochs=1, verbose=2)
        return self.net.get_weights(), len(self.train_data), {}

    def evaluate(self, parameters, config):
        self.net.set_weights(parameters)
        loss, accuracy = self.net.evaluate(self.test_data, self.test_labels, verbose=2)
        return loss, len(self.test_data), {"accuracy": accuracy}

def client_fn(cid: str) -> FlowerClient:
    partition_size = len(features_train) // NUM_CLIENTS
    idx_from, idx_to = int(cid) * partition_size, (int(cid) + 1) * partition_size
    return FlowerClient(
        convlstm_model,
        features_train[idx_from:idx_to],
        labels_train[idx_from:idx_to],
        features_test,
        labels_test,
    )

strategy = fl.server.strategy.FedAvg(
    fraction_fit=1.0,
    fraction_evaluate=0.5,
    min_fit_clients=2,
    min_evaluate_clients=2,
    min_available_clients=2,
)

fl.simulation.start_simulation(
    client_fn=client_fn,
    num_clients=NUM_CLIENTS,
    config=fl.server.ServerConfig(num_rounds=5),
    strategy=strategy,
)
```

the code uses synthetic data so the improvement is marginal but weights can be checked by adding print functions to the `fit` function. 

```python
def fit(self, parameters, config):
    self.net.set_weights(parameters)
    initial_weights = self.net.get_weights()  # Log or store initial weights
    print(f"Initial Weights: {initial_weights[0][:2]}")  # Print first few values for simplicity
    
    self.net.fit(self.train_data, self.train_labels, epochs=1, verbose=2)
    updated_weights = self.net.get_weights()  # Check updated weights
    print(f"Updated Weights: {updated_weights[0][:2]}")  # Print first few values for comparison
    
    return self.net.get_weights(), len(self.train_data), {}
```

The current example using TensorFlow runs as it should, maybe this is due to newer flwr versions. 

Closing this issue.
