### ISSUE TITLE
Simulation methods and privacy accumulation

### ISSUE THREAD

**Issue by xmser** [adap/flower#2216]
### What is your question?

Thank you very much for the flower library and DP implementation you provided. I would like to ask if the simulated method is used, will the tutor privacy consumption be unable to accumulate because the simulated client resources are released.

This is the explanation of the simulation method I got in An Introduction to Federated Learning: [https://flower.dev/docs/framework/tutorial/Flower-1-Intro-to-FL-PyTorch.html](url)
Flower calls client_fn whenever it needs an instance of one particular client to call fit or evaluate (those instances are usually discarded after use, so they should not keep any local state). Clients are identified by a client ID, or short cid. The cid can be used, for example, to load different local data partitions for different clients, as can be seen below:

**Comment by WilliamLindskog** [comment]
The clients are by default stateless meaning that their state does not persist over rounds by are instantiated on-demand. However, you can make use of [stateful clients](https://github.com/adap/flower/blob/main/framework/docs/source/how-to-design-stateful-clients.rst) in Flower. This would allow you to sum the tutor privacy consumption. 

Closing this issue for now.
