### ISSUE TITLE
Custom Clients

### ISSUE THREAD

**Issue by Nicholas-B1** [adap/flower#2236]
### Describe what the documentation is missing.

From quick start pytorch to advanced pytorch you go from 2 to 10 clients. I do not see anywhere that explains how to have a custom about of clients. I might be missing where this is already explained and if so I would love to know.

Thank you! 

### Suggest your improvement.

Show where in the code and the flower framework someone would have to adjust to have their custom number of clients.

**Comment by jafermarq** [comment]
Hi @Nicholas-B1 , based on the discussions in the Flower slack, would be interested in updating the example to include those explanations? open a pull request with your changes and we'll move on from there (you can find a guide on how to do this here: https://flower.dev/docs/framework/contributor-tutorial-contribute-on-github.html)

**Comment by Nicholas-B1** [comment]
Once I successfully run the changed number of clients which might be in a couple weeks I can make a pull request. If I have additional questions on the format of the PR should I direct those questions to the slack still?
________________________________

**Comment by jafermarq** [comment]
maybe here. If possible, let us know what you have tried (with code) and detail what you want to achieve.

**Comment by Nicholas-B1** [comment]
I have done quickstart pytorch with 2 Jetson nano clients and plan to use the advance pytorch to add more clients.
________________________________

**Comment by WilliamLindskog** [comment]
Hi

Thanks for raising this. There are currently documentations on how to create and add more clients: 
- https://flower.ai/docs/framework/tutorial-series-customize-the-client-pytorch.html
- https://github.com/adap/flower/tree/main/examples/advanced-pytorch 

and more examples. 

Closing this issue.
