### ISSUE TITLE
Add metadata to Client in client.py and read it inside server.py

### ISSUE THREAD

**Issue by fredowashere** [adap/flower#2245]
We are making ready-to-run client.py files on for our users and we have certain properties we would like to read inside the server.py.

Is it possible, and if so how, to define arbitrary metadata for each client.py file and to read this data inside the server.py?

**Comment by jafermarq** [comment]
Hey @fredowashere, if your clients have that metadata built-in when the client object is created, then the server can request that data using the `get_properties()` method. Alternatively you can share that metadata with the server via the last return argument in the client's `fit()` method. That argument is internally called "metrics". Then, in your strategy you'll be able to process (in the `aggregate_fit()` method) them the way you want.

**Comment by WilliamLindskog** [comment]
Hi @fredowashere, 

Thanks for raising this issue. Just checking in here. Would you say your question was answered? If so, can we go ahead and close this issue?

**Comment by fredowashere** [comment]
Hi WilliamLindskog, we couldn't make it work at that time but now there's a new version of Flower if I'm not mistaken, so we should bump the deps and retry. Anyway I'm closing this :)
