### ISSUE TITLE
wrong paper associated with FedXgbNnAvg strategy in the docs

### ISSUE THREAD

**Issue by Aml-Hassan-Abd-El-hamid** [adap/flower#2380]
### Describe what the documentation is missing.

In the docs for the FedXgbNnAvg strategy right here: https://flower.dev/docs/framework/ref-api-flwr.html#server-strategy-fedxgbnnavg it's said that its implementation is based on this paper: https://arxiv.org/abs/1602.05629 , 
while in the code in GitHub right here https://github.com/adap/flower/blob/main/src/py/flwr/server/strategy/fedxgb_nn_avg.py, the paper part is labelled as coming, and the code is made by Chenyang, one of the authors of the horizontal XGBosst paper https://arxiv.org/abs/2304.07537,
Also, the paper mentioned in the docs has nothing to do with that strategy so I believe that this is the wrong paper.

### Suggest your improvement.

Add the right paper https://arxiv.org/abs/2304.07537 to the docs of the FedXgbNnAvg strategy

**Comment by gfmota** [comment]
I can help with it. Can I be assiigned?

**Comment by jafermarq** [comment]
Hey @gfmota, i've just assigned this issue to you. 

I've discussed about this briefly with @panh99 , and we think this can easily be fixed if the baseline @Aml-Hassan-Abd-El-hamid mentions had a `__init__` method implemented (with docstrings pointing to the paper where that first proposed the strategy). This issue does not only affect `FedXgbNnAvg` but also some other strategies that directly inherit from `FedAvg` w/o defining a `__init__`. Could you look into all those? You'll likely find the paper to cite at the top of the respective `.py` file. 

One way of doing the above would look like this. But we are open to other ways of doing it:
```python
class FedXgbNnAvg(FedAvg):
    """Configurable FedXgbNnAvg strategy implementation."""
    def __init__(self, *args, **kwargs):
        """Federated XGBoost [Ma et al., 2023 """ # Edit with the full reference etc
        super().__init__(*args, **kwargs)

```

**Comment by gfmota** [comment]
I've created a PR adding this doc in the class, could anyone look it to see if is it what was expected?

**Comment by jafermarq** [comment]
Thanks @gfmota for the fix and @Aml-Hassan-Abd-El-hamid for spotting this!!
