### ISSUE TITLE
Is it possible to check Android status on the server

### ISSUE THREAD

**Issue by albertinoi** [adap/flower#2504]
### What is your question?

Greetings,
As the questions says, I wanted to extract the Android devices status for example
- percentage of computational power used
- Energy consumption
- Bandwidth
- Time required to run the model.

I also wanted to ask since I am not familiar with programming for Android, if I want to use another dataset like CIFAR100 which files do I require to change?

**Comment by danielnugraha** [comment]
Hi, yes it is possible, in your application you can call `Build` methods from your application `Context` and monitor the status of your FL training in Android. Please refer to https://developer.android.com/reference/android/os/package-summary for more informations.

I guess in your case it requires somewhat monitoring of each status, so I suggest to sample the status once in the beginning and once after training and calculate the difference to get what you want.

To change dataset, you need to implement the data loader for the dataset, this includes preprocessing and prepare the dataset to match the input shape of your model.
