### ISSUE TITLE
Excessive training time on Raspberry Pi may result in 'fit_round 1 received 1 results and 1 failures.

### ISSUE THREAD

**Issue by linwei1111** [adap/flower#2515]
### What is your question?

In exsample:quickstart pytorch

I use my raspberry pi and my laptop as my two clients

rpi’s training time over 4 minutes

If the client's training time exceeds 4 minutes, it may result in "fit_round 1 received 1 results and 1 failures." 
![image](https://github.com/adap/flower/assets/131733899/c3480658-d77e-4956-88ec-7842895e78c4)

How can I extend the waiting time

**Comment by linwei1111** [comment]
I find how to solve it ,You can modify the keepalive time of grpc.server

**Comment by jafermarq** [comment]
Hi @linwei1111 , it's great to see you made it work. I'll close this issue now :)
