### ISSUE TITLE
Follow the tutorial but no response on both server side and client side

### ISSUE THREAD

**Issue by Yonggie** [adap/flower#2586]
### Describe the bug

I follow the [tutorial pytorch quickstart](https://flower.dev/docs/framework/tutorial-quickstart-pytorch.html).
Got stuck in running fed learning:
![image](https://github.com/adap/flower/assets/31330044/2bfdb47d-56a9-4f37-9878-1ebcf1fd852d)

It simply not moving anyhow, even though I checked I did have GPU resouce.

BTW, I was using python3.11 on ubuntu.

### Steps/Code to Reproduce

[tutorial pytorch quickstart](https://flower.dev/docs/framework/tutorial-quickstart-pytorch.html)

### Expected Results

fix it?

### Actual Results

Stuck in here.
![image](https://github.com/adap/flower/assets/31330044/2bfdb47d-56a9-4f37-9878-1ebcf1fd852d)

**Comment by Yonggie** [comment]
Oh I find it! Maybe documentation gives a hint that tell us to start the server requires multiple clients started in multiple terminal.

**Comment by danieljanes** [comment]
Thanks for updating the issue @Yonggie :)
