### ISSUE TITLE
compatibility with mysql-connector-python 8.2.0

### ISSUE THREAD

**Issue by kenzo-staelens** [adap/flower#2633]
### Describe the type of feature and its functionality.

currently flwr[simulation] 1.5.0 has a dependency protobuf<4.0.0 and >=3.19.0
with mysql-connector-python 8.2.0 depending on protobuf<=4.21.12 and >=4.21.1

simulation has no issues running on protobuf 4.21.12
i have no idea where this dependency ( protobuf<4.0.0 )is located

### Describe step by step what files and adjustments are you planning to include.

whichever dependency file is the correct one

**Comment by WilliamLindskog** [comment]
Hi 

Thanks for raising this. Closing this right now because flwr 1.5. is no longer supported.
