### ISSUE TITLE
 No file/folder found for package quickstart-pytorch

### ISSUE THREAD

**Issue by xwang317** [adap/flower#2653]
### vertical federated learning example, could not install virtual env through poetry? 

Hi, 
Hope all is well.

I am working on the flower vertical federated learning example. 
https://flower.dev/docs/examples/vertical-fl.html
After cloning the repository, I could not install virtual env successfully through poetry. Every time I run `$ poetry install`, it give me back either: 
> Installing the current project: quickstart-pytorch (0.1.0)
> The current project could not be installed: No file/folder found for package quickstart-pytorch
> If you do not want to install the current project use --no-root

or it just keeps resolving dependencies forever. 

My environment setting is: 
WSL Ubuntu 2204 LTS
Poetry 1.7.1 

Thank you very much in advance! Please let me know if I can provide anything.

**Comment by jafermarq** [comment]
Hi @xwang317 ,  thanks for bringing this up. It seems to happen with more recent versions of `Poetry` (it doesn't happen with 1.5, but it does with 1.7 or 1.8). 
We'll fix this but it is safe to ignore the error. You can activate your environment (via `poetry shell`) and run the simulation.

**Comment by xwang317** [comment]
> Hi @xwang317 , thanks for bringing this up. It seems to happen with more recent versions of `Poetry` (it doesn't happen with 1.5, but it does with 1.7 or 1.8). We'll fix this but it is safe to ignore the error. You can activate your environment (via `poetry shell`) and run the simulation.

Thank you very much @jafermarq!
I also was not able to run the simulation, here is the error report..
could you help with this if possible? Thank you very much! let me know if I can provide anything.  

> salmon@satre:~/vertical-fl$ poetry run python3 simulation.py
The currently activated Python version 3.11.5 is not supported by the project (>=3.8,<3.11).
Trying to find and use a compatible version. 
Using python3.10 (3.10.12)
Traceback (most recent call last):
  File "/home/salmon/.cache/pypoetry/virtualenvs/quickstart-pytorch-yvL9m5xc-py3.10/lib/python3.10/site-packages/torch/__init__.py", line 174, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcufft.so.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/salmon/vertical-fl/simulation.py", line 3, in <module>
    from strategy import Strategy
  File "/home/salmon/vertical-fl/strategy.py", line 2, in <module>
    import torch
  File "/home/salmon/.cache/pypoetry/virtualenvs/quickstart-pytorch-yvL9m5xc-py3.10/lib/python3.10/site-packages/torch/__init__.py", line 234, in <module>
    _load_global_deps()
  File "/home/salmon/.cache/pypoetry/virtualenvs/quickstart-pytorch-yvL9m5xc-py3.10/lib/python3.10/site-packages/torch/__init__.py", line 195, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/salmon/.cache/pypoetry/virtualenvs/quickstart-pytorch-yvL9m5xc-py3.10/lib/python3.10/site-packages/torch/__init__.py", line 160, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/home/salmon/vertical-fl', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/salmon/.cache/pypoetry/virtualenvs/quickstart-pytorch-yvL9m5xc-py3.10/lib/python3.10/site-packages']

**Comment by jafermarq** [comment]
Hi @xwang317 , 
An error is logged right after you start your simulation:
```
The currently activated Python version 3.11.5 is not supported by the project (>=3.8,<3.11).
```
It might be fine to skip it but i'm aren't sure. YOu can skip to the part I talk about cuda and see if that fixes your issue:

#### Specify python version
What you need to do is to have a lower version of Python and tell poetry to use that when building the environment. There are different ways of achieving this. You could first install `pyenv` (if you haven't already -- i wrote a guide of how to do it [here](https://flower.dev/docs/baselines/how-to-use-baselines.html#setting-up-your-machine)) and then:

```bash
pyenv install 3.10.12 # for example (you could use others)

# then you can list all your versions (to see what's available in your system)
pyenv versions # you should see 3.10.12 (and potentially others)

# go to the example directory
cd flower/examples/vertical-fl

# set to use the python version just installed
pyenv local 3.10.12
poetry env use 3.10.12

# finally install
poetry install

# then activate
poetry shell

# then you can run the example
python simulation.py
```

That should fix that error at the beginning. 

#### Missing CUDA packages
regarding the Cuda error... for some reason some auxiliary packages that come with `torch`/`torchvision` don't get pulled & installed with Poetry (they are installed just fine via standard `pip`). In the mean time, you can simply do the following after activating your environment via `poetry shell`:

```
# this will only install the missing packages
pip install -r requirements.txt
```
Hope this helps

**Comment by xwang317** [comment]
> Hi @xwang317 , An error is logged right after you start your simulation:
> 
> ```
> The currently activated Python version 3.11.5 is not supported by the project (>=3.8,<3.11).
> ```
> 
> It might be fine to skip it but i'm aren't sure. YOu can skip to the part I talk about cuda and see if that fixes your issue:
> 
> #### Specify python version
> What you need to do is to have a lower version of Python and tell poetry to use that when building the environment. There are different ways of achieving this. You could first install `pyenv` (if you haven't already -- i wrote a guide of how to do it [here](https://flower.dev/docs/baselines/how-to-use-baselines.html#setting-up-your-machine)) and then:
> 
> ```shell
> pyenv install 3.10.12 # for example (you could use others)
> 
> # then you can list all your versions (to see what's available in your system)
> pyenv versions # you should see 3.10.12 (and potentially others)
> 
> # go to the example directory
> cd flower/examples/vertical-fl
> 
> # set to use the python version just installed
> pyenv local 3.10.12
> poetry env use 3.10.12
> 
> # finally install
> poetry install
> 
> # then activate
> poetry shell
> 
> # then you can run the example
> python simulation.py
> ```
> 
> That should fix that error at the beginning.
> 
> #### Missing CUDA packages
> regarding the Cuda error... for some reason some auxiliary packages that come with `torch`/`torchvision` don't get pulled & installed with Poetry (they are installed just fine via standard `pip`). In the mean time, you can simply do the following after activating your environment via `poetry shell`:
> 
> ```
> # this will only install the missing packages
> pip install -r requirements.txt
> ```
> 
> Hope this helps

Thank you so much @jafermarq ! It works now!
