### ISSUE TITLE
Android cases cannot connect to the server

### ISSUE THREAD

**Issue by iot-future** [adap/flower#2698]
### What is your question?

My server side is running in pycharm in Windows. The client runs in the Android studio emulator. In the emulator I entered the IP address and port number correctly, but the message "unavailable" was displayed.
Could someone please guide me on how to troubleshoot this issue?  Any insights or suggestions would be greatly appreciated.  Thank you in advance!
![Snipaste_2023-12-08_19-32-42](https://github.com/adap/flower/assets/78769065/4330e984-4bbe-4cff-9cb8-874d365f1303)

**Comment by danielnugraha** [comment]
It can be that your loopback address is not set, maybe try to input your original ipv4 address?

**Comment by iot-future** [comment]
> It can be that your loopback address is not set, maybe try to input your original ipv4 address?

Thank you for your response. I apologize for my lack of familiarity with network settings. Could you please guide me on how to configure the network address and perform a connectivity test for the server? Additionally, I would greatly appreciate any other tutorials or suggestions you may have.

**Comment by iot-future** [comment]
> It can be that your loopback address is not set, maybe try to input your original ipv4 address?

I'm sorry. But now I'm sure I set the loopback address for "127.0.0.1". What else might be causing the failure to connect to the server?

**Comment by iot-future** [comment]
The IP address of 10.0.2.2 is accessible
