### ISSUE TITLE
Button not visible in Android

### ISSUE THREAD

**Issue by iot-future** [adap/flower#2714]
### What is your question?

 I recently downloaded the code from GitHub and noticed that the readme file mentions the presence of some buttons in the application.     However, when I ran the code, I couldn't see the buttons on the frontend page, such as Load Dataset,Setup Connection Channel, and Train Federated.  I have checked the code and ensured all the necessary dependencies are installed correctly.     Could you please help me troubleshoot this issue?     Thank you!
![Snipaste_2023-12-17_21-46-13](https://github.com/adap/flower/assets/78769065/a4a8241c-4ce2-4838-b354-6e5323b3c583)
![Snipaste_2023-12-08_19-32-42](https://github.com/adap/flower/assets/78769065/9d0bebd3-8d6b-4456-9eca-559baf5a446f)

**Comment by danielnugraha** [comment]
Readme is updated in PR #2804.
