### ISSUE TITLE
Error " iteration_indptr = bst_prev["learner"]["gradient_booster"]["model"][ KeyError: 'iteration_indptr'" in the server side when implementing the code on my own dataset

### ISSUE THREAD

**Issue by yaman-hub** [adap/flower#2777]
### Describe the bug

I am trying to implement the xgboost-quickstart code on my own dataset using the GitHub ink "https://github.com/adap/flower/tree/main/examples/xgboost-quickstart" after running the server and the two clients, I have output on the client.py however the following error appears on the server side "iteration_indptr = bst_prev["learner"]["gradient_booster"]["model"][ KeyError: 'iteration_indptr" ;

### Steps/Code to Reproduce

Server side: 
`import flwr as fl
from flwr.server.strategy import FedXgbBagging

# FL experimental settings
pool_size = 2
num_rounds = 5
num_clients_per_round = 2
num_evaluate_clients = 2

def evaluate_metrics_aggregation(eval_metrics):
    """Return an aggregated metric (AUC) for evaluation."""
    total_num = sum([num for num, _ in eval_metrics])
    auc_aggregated = (
        sum([metrics["AUC"] * num for num, metrics in eval_metrics]) / total_num
    )
    metrics_aggregated = {"AUC": auc_aggregated}
    return metrics_aggregated

# Define strategy
strategy = FedXgbBagging(
    fraction_fit=(float(num_clients_per_round) / pool_size),
    min_fit_clients=num_clients_per_round,
    min_available_clients=pool_size,
    min_evaluate_clients=num_evaluate_clients,
    fraction_evaluate=1.0,
    evaluate_metrics_aggregation_fn=evaluate_metrics_aggregation,
)

# Start Flower server
fl.server.start_server(
    server_address="0.0.0.0:8080",
    config=fl.server.ServerConfig(num_rounds=num_rounds),
    strategy=strategy,
)`

Clients side:
`import argparse
from typing import Union
from logging import INFO
from datasets import Dataset, DatasetDict
import xgboost as xgb
import pandas as pd
from sklearn.model_selection import train_test_split

import flwr as fl
from flwr_datasets import FederatedDataset
from flwr.common.logger import log
from flwr.common import (
    Code,
    EvaluateIns,
    EvaluateRes,
    FitIns,
    FitRes,
    GetParametersIns,
    GetParametersRes,
    Parameters,
    Status,
)
from flwr_datasets.partitioner import IidPartitioner

# We first define arguments parser for user to specify the client/node ID.
parser = argparse.ArgumentParser()
parser.add_argument(
    "--node-id",
    default=0,
    type=int,
    help="Node ID used for the current client.",
)
args = parser.parse_args()

partitioner = IidPartitioner(num_partitions=30)
fds=pd.read_csv('Noisy_Data.csv')

partition =fds.to_numpy()

#  Define data partitioning related functions

def transform_dataset_to_dmatrix(data: Union[Dataset, DatasetDict]) -> xgb.core.DMatrix:
    """Transform dataset to DMatrix format for xgboost."""
    x = data[:,0:-1]
    y = data[:,-1]
    print(x)
    print(y)
    new_data = xgb.DMatrix(x, label=y)
    return new_data

train_data, valid_data = train_test_split(
    partition, test_size=20, random_state=32
)
num_train=len(train_data)
num_val=len(valid_data)

train_dmatrix = transform_dataset_to_dmatrix(train_data)
valid_dmatrix = transform_dataset_to_dmatrix(valid_data)

# Hyper-parameters for xgboost training
num_local_round = 5
params = {
    "objective": "binary:logistic",
    "eta": 0.1,  # Learning rate
    "max_depth": 8,
    "eval_metric": "auc",
    "nthread": 16,
    "num_parallel_tree": 1,
    "subsample": 1,
    "tree_method": "hist",
}

# Define Flower client
class XgbClient(fl.client.Client):
    def __init__(self):
        self.bst = None
        self.config = None

    def get_parameters(self, ins: GetParametersIns) -> GetParametersRes:
        _ = (self, ins)
        return GetParametersRes(
            status=Status(
                code=Code.OK,
                message="OK",
            ),
            parameters=Parameters(tensor_type="", tensors=[]),
        )

    def _local_boost(self):
        # Update trees based on local training data.
        for i in range(num_local_round):
            self.bst.update(train_dmatrix, self.bst.num_boosted_rounds())

        # Extract the last N=num_local_round trees for sever aggregation
        bst = self.bst[
            self.bst.num_boosted_rounds()
            - num_local_round : self.bst.num_boosted_rounds()
        ]

        return bst

    def fit(self, ins: FitIns) -> FitRes:
        if not self.bst:
            # First round local training
            log(INFO, "Start training at round 1")
            bst = xgb.train(
                params,
                train_dmatrix,
                num_boost_round=num_local_round,
                evals=[(valid_dmatrix, "validate"), (train_dmatrix, "train")],
            )
            self.config = bst.save_config()
            self.bst = bst
        else:
            for item in ins.parameters.tensors:
                global_model = bytearray(item)

            # Load global model into booster
            self.bst.load_model(global_model)
            self.bst.load_config(self.config)

            bst = self._local_boost()

        local_model = bst.save_raw("json")
        local_model_bytes = bytes(local_model)

        return FitRes(
            status=Status(
                code=Code.OK,
                message="OK",
            ),
            parameters=Parameters(tensor_type="", tensors=[local_model_bytes]),
            num_examples=num_train,
            metrics={},
        )

    def evaluate(self, ins: EvaluateIns) -> EvaluateRes:
        eval_results = self.bst.eval_set(
            evals=[(valid_dmatrix, "valid")],
            iteration=self.bst.num_boosted_rounds() - 1,
        )
        auc = round(float(eval_results.split("\t")[1].split(":")[1]), 4)

        return EvaluateRes(
            status=Status(
                code=Code.OK,
                message="OK",
            ),
            loss=0.0,
            num_examples=num_val,
            metrics={"AUC": auc},
        )

# Start Flower client
fl.client.start_client(server_address="127.0.0.1:8080", client=XgbClient())

`

### Expected Results

INFO flwr 2023-11-20 11:21:56,454 | app.py:163 | Starting Flower server, config: ServerConfig(num_rounds=5, round_timeout=None)
INFO flwr 2023-11-20 11:21:56,473 | app.py:176 | Flower ECE: gRPC server running (5 rounds), SSL is disabled
INFO flwr 2023-11-20 11:21:56,473 | server.py:89 | Initializing global parameters
INFO flwr 2023-11-20 11:21:56,473 | server.py:276 | Requesting initial parameters from one random client
INFO flwr 2023-11-20 11:22:38,302 | server.py:280 | Received initial parameters from one random client
INFO flwr 2023-11-20 11:22:38,302 | server.py:91 | Evaluating initial parameters
INFO flwr 2023-11-20 11:22:38,302 | server.py:104 | FL starting
DEBUG flwr 2023-11-20 11:22:38,302 | server.py:222 | fit_round 1: strategy sampled 2 clients (out of 2)
DEBUG flwr 2023-11-20 11:22:38,636 | server.py:236 | fit_round 1 received 2 results and 0 failures
DEBUG flwr 2023-11-20 11:22:38,643 | server.py:173 | evaluate_round 1: strategy sampled 2 clients (out of 2)
DEBUG flwr 2023-11-20 11:22:38,653 | server.py:187 | evaluate_round 1 received 2 results and 0 failures
DEBUG flwr 2023-11-20 11:22:38,653 | server.py:222 | fit_round 2: strategy sampled 2 clients (out of 2)
DEBUG flwr 2023-11-20 11:22:38,721 | server.py:236 | fit_round 2 received 2 results and 0 failures

### Actual Results

INFO flwr 2024-01-08 13:07:13,730 | app.py:163 | Starting Flower server, config: ServerConfig(num_rounds=5, round_timeout=None)
INFO flwr 2024-01-08 13:07:13,753 | app.py:176 | Flower ECE: gRPC server running (5 rounds), SSL is disabled
INFO flwr 2024-01-08 13:07:13,753 | server.py:89 | Initializing global parameters
INFO flwr 2024-01-08 13:07:13,753 | server.py:276 | Requesting initial parameters from one random client
INFO flwr 2024-01-08 13:07:20,409 | server.py:280 | Received initial parameters from one random client
INFO flwr 2024-01-08 13:07:20,409 | server.py:91 | Evaluating initial parameters
INFO flwr 2024-01-08 13:07:20,410 | server.py:104 | FL starting
DEBUG flwr 2024-01-08 13:07:24,609 | server.py:222 | fit_round 1: strategy sampled 2 clients (out of 2)
DEBUG flwr 2024-01-08 13:07:25,086 | server.py:236 | fit_round 1 received 2 results and 0 failures
Traceback (most recent call last):
  File "C:\Users\Acoe\PycharmProjects\Flower_Poinosned_data_detection\Server.py", line 33, in <module>
    fl.server.start_server(
  File "C:\Users\Acoe\AppData\Local\Programs\Python\Python310\lib\site-packages\flwr\server\app.py", line 184, in start_server
    hist = run_fl(
  File "C:\Users\Acoe\AppData\Local\Programs\Python\Python310\lib\site-packages\flwr\server\app.py", line 225, in run_fl
    hist = server.fit(num_rounds=config.num_rounds, timeout=config.round_timeout)
  File "C:\Users\Acoe\AppData\Local\Programs\Python\Python310\lib\site-packages\flwr\server\server.py", line 109, in fit
    res_fit = self.fit_round(
  File "C:\Users\Acoe\AppData\Local\Programs\Python\Python310\lib\site-packages\flwr\server\server.py", line 248, in fit_round
    ] = self.strategy.aggregate_fit(server_round, results, failures)
  File "C:\Users\Acoe\AppData\Local\Programs\Python\Python310\lib\site-packages\flwr\server\strategy\fedxgb_bagging.py", line 65, in aggregate_fit
    global_model = aggregate(global_model, bst)
  File "C:\Users\Acoe\AppData\Local\Programs\Python\Python310\lib\site-packages\flwr\server\strategy\fedxgb_bagging.py", line 129, in aggregate
    iteration_indptr = bst_prev["learner"]["gradient_booster"]["model"][
KeyError: 'iteration_indptr'

**Comment by KuangYalan** [comment]
I have the same problems. Any suggestions?

**Comment by WilliamLindskog** [comment]
Hi @yaman-hub, @KuangYalan, 

Thanks for raising this. Are you still experiencing this issue?

**Comment by itrajanovska** [comment]
I also had this issue a month ago and what worked for me was commenting these lines as it seemed that they were ineffective and probably part of some older code?


 134   │ #    iteration_indptr = bst_prev["learner"]["gradient_booster"]["model"][
 135   │ #        "iteration_indptr"
 136   │ #    ]
 137   │ #    bst_prev["learner"]["gradient_booster"]["model"]["iteration_indptr"].append(
 138   │ #        iteration_indptr[-1] + paral_tree_num_curr
 139   │ #    )

**Comment by WilliamLindskog** [comment]
Hi @itrajanovska 

Thanks for your comment. We have moved away from earlier version implementation, do you experience the same issue after using the latest version (1.13)?

**Comment by WilliamLindskog** [comment]
Hi again, 

I ran the [xgboost-quickstart](https://github.com/adap/flower/tree/main/examples/xgboost-quickstart) and it runs "as should". The mentioned codebase is not longer supported, thus I recommend to check out the linked example. 

Closing this issue for now.
