### ISSUE TITLE
fraction_fit 怎么动态变化

### ISSUE THREAD

**Issue by buaaYYC** [adap/flower#2781]
### What is your question?

    strategy = fl.server.strategy.FedAvg(
        fraction_fit=0.2,
        fraction_evaluate=0.2,
        min_fit_clients=2,
        min_evaluate_clients=2,
        min_available_clients=10,
        evaluate_fn=get_evaluate_fn(model, args.toy),
        on_fit_config_fn=fit_config,
        on_evaluate_config_fn=evaluate_config,
        initial_parameters=fl.common.ndarrays_to_parameters(model_parameters),
    )

Hello, I have a requirement now. I want the number of clients to participate in training to be different in different epochs. How should I modify the strategy? Thank you.

**Comment by helin0815** [comment]
在flwr/server/server.py的代码里好像有地方可以修改，但是也需要改代码

**Comment by buaaYYC** [comment]
> 在flwr/server/server.py的代码里好像有地方可以修改，但是也需要改代码

是的，但是不知道怎么修改这个策略 ，现在我看都是一个固定值，没法和训练轮数挂钩

**Comment by helin0815** [comment]
> > 在flwr/server/server.py的代码里好像有地方可以修改，但是也需要改代码
> 
> 是的，但是不知道怎么修改这个策略 ，现在我看都是一个固定值，没法和训练轮数挂钩。 我现在能想到的方法就是写两个模拟函数fl.simulation.start_simulation，比如前10epochs，客户端选择10个；后10个epochs训练再启动一个模拟函数，选择20个客户端，他的模型参数用第一次训练的参数。

感觉你这个方法也可以，或者你可以试试把fraction_fit这个值从某个配置文件（比如/opt/fraction_fit.txt）中读取，然后在训练10轮以后修改/opt/fraction_fit.txt的内容，然后server.py再去读取这个内容？我不太确定server的启动是不是每轮都会重新分配一下，你可以试试

**Comment by buaaYYC** [comment]
> > > 在flwr/server/server.py的代码里好像有地方可以修改，但是也需要改代码
> > 
> > 
> > 是的，但是不知道怎么修改这个策略 ，现在我看都是一个固定值，没法和训练轮数挂钩。 我现在能想到的方法就是写两个模拟函数fl.simulation.start_simulation，比如前10epochs，客户端选择10个；后10个epochs训练再启动一个模拟函数，选择20个客户端，他的模型参数用第一次训练的参数。
> 
> 感觉你这个方法也可以，或者你可以试试把fraction_fit这个值从某个配置文件（比如/opt/fraction_fit.txt）中读取，然后在训练10轮以后修改/opt/fraction_fit.txt的内容，然后server.py再去读取这个内容？我不太确定server的启动是不是每轮都会重新分配一下，你可以试试

好的我试一试，我刚刚看到一个参数on_fit_config_fn ，感觉可能解决这个问题 
![image](https://github.com/adap/flower/assets/41562415/63b47579-27a0-4516-912d-4d8f1053428c)
![image](https://github.com/adap/flower/assets/41562415/87e7de98-4ceb-4cd9-8f7a-72ab990b19ce)

**Comment by helin0815** [comment]
> > > > 在flwr/server/server.py的代码里好像有地方可以修改，但是也需要改代码
> > > 
> > > 
> > > 是的，但是不知道怎么修改这个策略 ，现在我看都是一个固定值，没法和训练轮数挂钩。 我现在能想到的方法就是写两个模拟函数fl.simulation.start_simulation，比如前10epochs，客户端选择10个；后10个epochs训练再启动一个模拟函数，选择20个客户端，他的模型参数用第一次训练的参数。
> > 
> > 
> > 感觉你这个方法也可以，或者你可以试试把fraction_fit这个值从某个配置文件（比如/opt/fraction_fit.txt）中读取，然后在训练10轮以后修改/opt/fraction_fit.txt的内容，然后server.py再去读取这个内容？我不太确定server的启动是不是每轮都会重新分配一下，你可以试试
> 
> 好的我试一试，我刚刚看到一个参数on_fit_config_fn ，感觉可能解决这个问题 ![image](https://private-user-images.githubusercontent.com/41562415/295165991-63b47579-27a0-4516-912d-4d8f1053428c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTQwNjUsIm5iZiI6MTcwNDc5Mzc2NSwicGF0aCI6Ii80MTU2MjQxNS8yOTUxNjU5OTEtNjNiNDc1NzktMjdhMC00NTE2LTkxMmQtNGQ4ZjEwNTM0MjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5NDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YmUwYzg4NzBmMGU4MjBmZjNlNTI0OTQyZWNlYmEzMDljY2JiYjEzNzFhYTk0MjZhM2JlMzgzMTQ1ZmE2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0VotMCkNkRFdOvJB-PlkHgMYnlIq-cy7xqght7SQEow) ![image](https://private-user-images.githubusercontent.com/41562415/295166231-87e7de98-4ceb-4cd9-8f7a-72ab990b19ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTQwNjUsIm5iZiI6MTcwNDc5Mzc2NSwicGF0aCI6Ii80MTU2MjQxNS8yOTUxNjYyMzEtODdlN2RlOTgtNGNlYi00Y2Q5LThmN2EtNzJhYjk5MGIxOWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5NDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYTYyYTk2ZDk4YzUxY2YzZjRiMTRlZWQ0MjU4N2I0ODcxMWNhOTI5OWZjNjExMmQ1Mjk3MmIxZGZmZjFiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HUV9qDbmheZw8RUSNWvn5MOxxOh5TCFaDLL21C45mQ8)

你使用flower框架是在做什么呢，我现在的研究方向是联邦学习的差分隐私

**Comment by buaaYYC** [comment]
我研究联邦学习的客户端选择策略

**Comment by yan-gao-GY** [comment]
Hi, this can be done by overriding the `configure_fit` function of the strategy.
E.g.,

```
def configure_fit(
    self, server_round: int, parameters: Parameters, client_manager: ClientManager
) -> List[Tuple[ClientProxy, FitIns]]:
    """Configure the next round of training."""
    config = {}
    if self.on_fit_config_fn is not None:
        # Custom fit config function provided
        config = self.on_fit_config_fn(server_round)
    fit_ins = FitIns(parameters, config)

    # Sample clients
    sample_size, min_num_clients = self.num_fit_clients(
        client_manager.num_available()
    )
    clients = client_manager.sample(
        num_clients=sample_size, min_num_clients=min_num_clients
    )

    # Sample the clients sequentially given server_round
    sampled_idx = (server_round - 1) % len(clients)
    sampled_clients = [clients[sampled_idx]]

    # Return client/config pairs
    return [(client, fit_ins) for client in sampled_clients]
```
The above code allows to sequentially sample the clients given `server_round`. You could do whatever clients sampling base one the given `server_round`.

**Comment by buaaYYC** [comment]
> Hi, this can be done by overriding the `configure_fit` function of the strategy. E.g.,
> 
> ```
> def configure_fit(
>     self, server_round: int, parameters: Parameters, client_manager: ClientManager
> ) -> List[Tuple[ClientProxy, FitIns]]:
>     """Configure the next round of training."""
>     config = {}
>     if self.on_fit_config_fn is not None:
>         # Custom fit config function provided
>         config = self.on_fit_config_fn(server_round)
>     fit_ins = FitIns(parameters, config)
> 
>     # Sample clients
>     sample_size, min_num_clients = self.num_fit_clients(
>         client_manager.num_available()
>     )
>     clients = client_manager.sample(
>         num_clients=sample_size, min_num_clients=min_num_clients
>     )
> 
>     # Sample the clients sequentially given server_round
>     sampled_idx = (server_round - 1) % len(clients)
>     sampled_clients = [clients[sampled_idx]]
> 
>     # Return client/config pairs
>     return [(client, fit_ins) for client in sampled_clients]
> ```
> 
> The above code allows to sequentially sample the clients given `server_round`. You could do whatever clients sampling based on the given `server_round`.

Thank you very much

**Comment by Klein920116** [comment]
如果启动了flower server后，客户端一直没有连接，可以手动停止server吗？

**Comment by helin0815** [comment]
> 如果启动了flower server后，客户端一直没有连接，可以手动停止server吗？

你具体是指什么？启动服务端后再启动客户端，客户端连不上服务端的话，当然是可以手动停止server的，停止了以后你再去排查一下你的代码哪里不对导致客户端连不上

**Comment by WilliamLindskog** [comment]
Closing this issue as it seems to be resolved.
