### ISSUE TITLE
Package Limitation: Neural Network Architecture Support

### ISSUE THREAD

**Issue by ouaelesi** [adap/flower#2809]
### What is your question?

Does the Package Exclusively Support Neural Network Architectures to train models?

**Comment by danielnugraha** [comment]
Please elaborate your question a bit more, what type of model do you want to federate with Flower?

**Comment by jafermarq** [comment]
> Please elaborate your question a bit more, what type of model do you want to federate with Flower?

I think @ouaelesi was wondering if Flower supports other forms of ML that do not make use of Neural Networks. We do have several examples that show how you can do FL without NNs, just to name a few: [quickstart-XGboost](https://github.com/adap/flower/tree/main/examples/xgboost-quickstart), [quickstart-Pandas](https://github.com/adap/flower/tree/main/examples/quickstart-pandas),  [quickstart-sklearn](https://github.com/adap/flower/tree/main/examples/sklearn-logreg-mnist).

@ouaelesi, does this answer your question ? Do you work with other frameworks not present in our `examples/` directory?

**Comment by WilliamLindskog** [comment]
Thanks for raising this. Closing this as Flower supports both parametric (NNs) and non-parametric models (boosted models). See example for reference.
