### ISSUE TITLE
Loading a saved checkpoint misses some steps

### ISSUE THREAD

**Issue by neogismm** [adap/flower#2824]
### Describe what the documentation is missing.

This is what is mentioned in the [doc](https://flower.dev/docs/framework/how-to-save-and-load-model-checkpoints.html) :
```python
list_of_files = [fname for fname in glob.glob("./model_round_*")]
latest_round_file = max(list_of_files, key=os.path.getctime)
print("Loading pre-trained model from: ", latest_round_file)
state_dict = torch.load(latest_round_file)
net.load_state_dict(state_dict)
``` 
The existing explanation overlooks the requirement to explicitly mention the conversion of the loaded state dict into ndarrays before transforming them into parameters, as the initial_parameters function expects parameters to be provided.

### Suggest your improvement.

These lines to be appened after net.load(state_dict)
```python
state_dict_ndarrays = [v.cpu().numpy() for v in net.state_dict().values()]
parameters = fl.common.ndarrays_to_parameters(state_dict_ndarrays)
```

**Comment by danieljanes** [comment]
Thanks for opening the issue @neogismm! Do you want to open a PR for this, or should we do it?

**Comment by neogismm** [comment]
I'll get it done. Thanks @danieljanes
