### ISSUE TITLE
Plotting losses/accuracies in flwr

### ISSUE THREAD

**Issue by BalajiAI** [adap/flower#2862]
### What is your question?

Usually, I log my flwr experiment into a log.txt file. At the end of the experiment, flwr will print the metrics.
I'll copy those metrics and plot using matplotlib. Are there any in-build function available in flwr for visualizing the fl training and evaluation?
Thanks!

**Comment by adam-narozniak** [comment]
Hi @BalajiAI! No, currently, there are no built-in functions for plotting the results of training/evaluation.

**Comment by BalajiAI** [comment]
Thanks @adam-narozniak. No worries, I wrote a piece of code which takes the fl experiment log and can visualize the plots for me.
