### ISSUE TITLE
Client cannot connect via gRPC

### ISSUE THREAD

**Issue by PaulKMandal** [adap/flower#2962]
### Describe the bug

Client gets a gRPC error when trying to connect on flwr version 0.17.0

### Steps/Code to Reproduce

My code is available here: https://github.com/PaulKMandal/flower_cv/tree/main

### Expected Results

The model should begin training

### Actual Results

I get the following error:
```
Traceback (most recent call last):
  File "/home/paul/Research/flower_cv/client.py", line 31, in <module>
    fl.client.start_client(server_address="[::]:8080", client=ObjectDetectionClient())
  File "/home/paul/Research/flower_cv/venv/lib/python3.11/site-packages/flwr/client/app.py", line 248, in start_client
    _start_client_internal(
  File "/home/paul/Research/flower_cv/venv/lib/python3.11/site-packages/flwr/client/app.py", line 361, in _start_client_internal
    message = receive()
              ^^^^^^^^^
  File "/home/paul/Research/flower_cv/venv/lib/python3.11/site-packages/flwr/client/grpc_client/connection.py", line 132, in receive
    proto = next(server_message_iterator)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/Research/flower_cv/venv/lib/python3.11/site-packages/grpc/_channel.py", line 540, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/home/paul/Research/flower_cv/venv/lib/python3.11/site-packages/grpc/_channel.py", line 966, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-02-15T12:42:51.805677812-06:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B::%5D:8080: Failed to connect to remote host: Connection refused"}"
```

**Comment by danieljanes** [comment]
Hi @PaulKMandal, are the server plus and (at least) two clients running?

I'd strongly recommend upgrading to the latest Flower release (1.7 as of today). I had to check the release log to be sure, Flower 0.17.0 was released in 2021.

This guide helps with upgrading from pre-1.0 to 1.0+ releases: https://flower.ai/docs/framework/how-to-upgrade-to-flower-1.0.html

**Comment by PaulKMandal** [comment]
> Hi @PaulKMandal, are the server plus and (at least) two clients running?
> 
> I'd strongly recommend upgrading to the latest Flower release (1.7 as of today). I had to check the release log to be sure, Flower 0.17.0 was released in 2021.
> 
> This guide helps with upgrading from pre-1.0 to 1.0+ releases: https://flower.ai/docs/framework/how-to-upgrade-to-flower-1.0.html

I was only testing with one client running. I'll try upgrading, I just know that I will need to rewrite a good amount of the code.

**Comment by raminduw200** [comment]
I'm using version 1.7.0 of flwr, but I'm still encountering this error. It works fine locally, but when the server hosted on an AWS EC2 cluster, I get this error on each client running on the same machine. I've opened ports 8080, 9091, 9092, and 9093 on EC2. Clients connect and train successfully, but this error occurs at the end of training.

**Comment by GabriJP** [comment]
I believe to have had the same problem. For some reason, the server only creates an IPv6 socket.

For me the solution was to completely disable IPv6 system-wide on the server machine.

You can easily check if this is your problem by running something like `netplan -tulpn`.

**Comment by WilliamLindskog** [comment]
Hi @PaulKMandal, @raminduw200 

Thanks for raising this. Are you still experiencing this issue?

**Comment by WilliamLindskog** [comment]
Hi again,

I am closing this issue as it seems to have been resolved by comment.
