### ISSUE TITLE
I cant run code on the Flower Tutorial : Get started with Flower

### ISSUE THREAD

**Issue by Iver-star** [adap/flower#3058]
### What is your question?

I am a beginner of flower and when i copy the code of the flower tutorial ，The program can not run.
The code is from https://flower.ai/docs/framework/tutorial-series-get-started-with-flower-pytorch.html
The error message is following.
![Snipaste_2024-03-05_19-51-09](https://github.com/adap/flower/assets/46343881/aa27c7bd-1b44-49e3-adb7-9927e056eea5)
I would greatly appreciate it if someone could answer.

**Comment by jafermarq** [comment]
Hey @Iver-star, I just tested running the code in the notebook following the link you provided. I could running it without issues. Are you running the notebook locally on your machine?

**Comment by Iver-star** [comment]
Hello. yeah, I run the code locally on my machine. I changed my python, pytorch, and flower version. But it doesn't work. I want to know if this is because my version is not compatible.

**Comment by Iver-star** [comment]
> Hey @Iver-star, I just tested running the code in the notebook following the link you provided. I could running it without issues. Are you running the notebook locally on your machine?

Hello @jafermarq . yeah, I run the code locally on my machine. I changed my python, pytorch, and flower version. But it doesn't work. I want to know if this is because my version is not compatible.

**Comment by jafermarq** [comment]
Hi @Iver-star, could you try following the instructions in some of our other examples? for example [`quickstart-pytorch`](https://github.com/adap/flower/tree/main/examples/quickstart-pytorch) or [`simulation-pytorch`](https://github.com/adap/flower/tree/main/examples/simulation-pytorch). The latter one you can run in a notebook if you prefer.

**Comment by Iver-star** [comment]
Hi @jafermarq , I am using a Windows system. I have taken your suggestion and successfully ran qiuckstart pytorch. However, the error message for simulation pytorch is the same as the one in the previous tutorial. I guess it may be because the ray library required for simulation is not compatible with my system.

I tried the simulation on my laptop and found no problems with any programs. Next, I will try reinstalling the system to solve the problem.

Thank you very much for your reply @jafermarq .
