### ISSUE TITLE
pip install flwr, but there are some ImportErrors

### ISSUE THREAD

**Issue by xiaoToby** [adap/flower#3071]
### Describe the bug

I git clone the repositry on local ,by this command, [git clone](https://github.com/adap/flower.git)
And I also use this cmd to install flower , pip install flwr
My python version is 3.8.18, and check the newest version of flower is 1.7.0.
Everything is fine, but when i run a flower program, sth happends.
For example, I ran python example/simulation_pytorch/sim.py,
there are some errors like this : 
ImportError: cannot import name 'handle_legacy_message_from_msgtype' from 'flwr.client.message_handler.message_handler' (/usr/local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py) 

I though that there are some files which are not included on /usr/local/lib/python3.8/site-packages/flwr/
So, I did next cmd:
cp /flower/src/py/flwr  /usr/local/lib/python3.8/site-packages/
Then, everything is fine

I guess, if there is no update on pypi?

### Steps/Code to Reproduce

1

### Expected Results

1

### Actual Results

1

**Comment by xiaoToby** [comment]
I followed the instructions.
And I found that isssue, on my opinion, if there is no update on pypi?

**Comment by jafermarq** [comment]
> I followed the instructions. And I found that isssue, on my opinion, if there is no update on pypi?

Happy to hear you found the issue. What was it? Currently `flwr` in pypi works fine. We'll be pushing an update (1.8) soon.

**Comment by xiaoToby** [comment]
I mean, if there is content leak on pypi(flwr 1.7)?

Because ,I installed flwr 1.7 by this command pip install flwr,
And I test this file, example/simulation_pytorch/sim.py. 

The error log is :
ImportError: cannot import name 'handle_legacy_message_from_msgtype' from 'flwr.client.message_handler.message_handler' (/usr/local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py)

I also downloaded the source code of flwr, so I tried to copy files to site-packages/flwr
The command is : cp /flower/src/py/flwr /usr/local/lib/python3.8/site-packages/

And then I ran this file, example/simulation_pytorch/sim.py.  Everything is fine.
So I doubt that if there are some files are lost on pypi(flwr 1.7).

**Comment by danieljanes** [comment]
Seems like this was resolved a while ago
