### ISSUE TITLE
how to load the mnist dataset locally

### ISSUE THREAD

**Issue by xiaoToby** [adap/flower#3076]
### What is your question?

If there is no network connection, I want to load the datasets locally,but i check the FederatedDataset class, it shows it will only load datasets from huggingface hub.

![image](https://github.com/adap/flower/assets/40045458/ac0a4ee7-77dc-4931-aad8-58e915619e31)
![image](https://github.com/adap/flower/assets/40045458/50c6c5a2-1369-4866-a4cf-6ce56f0f5a04)

Is there any solution?

**Comment by xiaoToby** [comment]
BTW, what the functiono of it value: img_key = "image".
I met that error(the screenshot below), when I check the datasets.load_dataset() which says it can load the local dataset.
![image](https://github.com/adap/flower/assets/40045458/e9dad9c0-8394-4a46-84fe-0fc13b5fb99e)

I need someone help me

**Comment by CarlosMari** [comment]
Hi! I have a workaround that may work for you.
If instead of defining a FederatedDataset you create a partitioner (for example NaturalIdPartitioner), you can change its dataset as far as you have a dataset from the datasets library. So if you can create a dataset object this may be able to solve your problem.

```
from flwr_datasets import FederatedDataset
from flwr_datasets.partitioner.natural_id_partitioner import NaturalIdPartitioner
from datasets import load_dataset

dataset = load_dataset('CIFAR10')
part = NaturalIdPartitioner('label')
part.dataset = dataset
part.load_partition(0)
```

**Comment by WilliamLindskog** [comment]
Hi 

Thank you for raising this. There is now documentation on how to use `flwr-datasets` with local data. Please have a look [here](https://flower.ai/docs/datasets/how-to-use-with-local-data.html)

I will close this issue for now.

**Comment by adam-narozniak** [comment]
@xiaoToby 
Loading of local datasets is supported; however, it happens by the creation of `datasets.Dataset` (without any download). The link that William sent explains that process. 

It's likely that in the near future, we will support  another common object directly (without any conversion).
