### ISSUE TITLE
Problem when running examples/llm-flowertune/main.py

### ISSUE THREAD

**Issue by PaulaDelgado-Santos** [adap/flower#3160]
### Describe the bug

Hi, I have followed the steps in examples/llm-flowertune/README.md (installing new dependencies) but I find the next problem:

`wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])`

`flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 15 crashed when the ClientAppActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last)`

`self._wandb.init(\n  File "/home/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1195, in init\n    raise e\n  File "/home/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1172, in init\n    wi.setup(kwargs)\n  File "/home/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 306, in setup\n    wandb_login._login(\n  File "/home/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 317, in _login\n    wlogin.prompt_api_key()\n  File "/home/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 247, in prompt_api_key\n    raise UsageError("api_key not configured (no-tty). call " + directive)\nwandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])\n',)`

### Steps/Code to Reproduce

`git clone --depth=1 https://github.com/adap/flower.git && mv flower/examples/llm-flowertune . && rm -rf flower && cd llm-flowertune`
`pip install -r requirements.txt`
`python main.py`

### Expected Results

The code running 

### Actual Results

Problem with ClientAppActor.run(), apparently: _api_key not configured (no-tty)_

**Comment by jafermarq** [comment]
Hi @PaulaDelgado-Santos, it seems the issue is related to Weights&Biases... have you logged in ? https://docs.wandb.ai/quickstart#2-log-in-to-wb

**Comment by PaulaDelgado-Santos** [comment]
True, I forgot to do so. Now is working, thanks a lot! :)

**Comment by jafermarq** [comment]
Amazing! I'll flag this issue as resolved then.
