### ISSUE TITLE
flwr_datasets with custom/local dataset

### ISSUE THREAD

**Issue by gubertoli** [adap/flower#3201]
### Describe the bug

FDS raising warning for custom datasets:

https://github.com/adap/flower/blob/dcffb484fb7d1e712f65d414fb31aa021f0a760e/datasets/flwr_datasets/utils.py#L82-L88

### Steps/Code to Reproduce

I am using the following code (a custom dataset loaded with pandas):

```python
dataset = Dataset.from_pandas(full_data, preserve_index=False, split="train")
partitioner = IidPartitioner(num_partitions=30)
fds = FederatedDataset(
        dataset=dataset,
        partitioners={"train": partitioner}
    )
```

### Expected Results

No warning for custom datasets.

### Actual Results

In this case the dataset is a custom dataset, but I am receiving the following warning (_features were redacted_):

```bash
utils.py:85: UserWarning: The currently tested dataset are ['mnist', 'cifar10', 'fashion_mnist', 'sasha/dog-food', 'zh-plus/tiny-imagenet']. Given: Dataset({
    features: ['xxx', 'xxx', 'xxx', 'label'],
    num_rows: 103904
}).
  warnings.warn(
```

**Comment by WilliamLindskog** [comment]
Hi @gubertoli 

Thanks for raising this. `flwr-datasets` now supports loading custom/local datasets: https://flower.ai/docs/datasets/how-to-use-with-local-data.html. Does this solve this issue?

**Comment by gubertoli** [comment]
@WilliamLindskog by the time I used the solution from PR #3212, but seems this issue and the PR are solved by Flower Dataset changes.
Thanks!
