### ISSUE TITLE
 How to let the client train using the initial model provided by the server?

### ISSUE THREAD

**Issue by zhangtian-3841** [adap/flower#3301]
### What is your question?

Dear Flower developers,

Hello! Thank you for your excellent work in helping me solve many problems! However, I have some questions and I sincerely ask for your assistance:

question 1:
- In the process of implementing federated learning based on Flower and PyTorch, I found that the initial model loaded by the client before training is local. 
- However, in certain cases, I need the client to train using the initial model provided by the server(For example, I need the client to continue training using the global model obtained from previous training sessions.). 

question 2:
- During the training process, on certain conditions (e.g., a specific port is accessed and requests an immediate halt to the training), how can I make the server or client stop the training process proactively?
- I noticed that the disconnect_all_clients function can stop the federated learning process for a server that exceeds the specified number of rounds. Can I modify it to achieve my goal?

Thank you for your assistance!

**Comment by zhangtian-3841** [comment]
Additionally, I have another question and would appreciate your help or advice: 

During the training process, on certain conditions (e.g., a specific port is accessed and requests an immediate halt to the training), how can I make the server or client stop the training process proactively?

 I noticed that the disconnect_all_clients function can stop the federated learning process for a server that exceeds the specified number of rounds. Can I modify it to achieve my goal?
 
  Once again, thank you for your assistance and response.

**Comment by rlakinie** [comment]
For question 1, what I did to work was pass the model parameters (provided from the server) into the the strategy definition. 

Related: https://flower.ai/docs/framework/tutorial-series-use-a-federated-learning-strategy-pytorch.html

**Comment by WilliamLindskog** [comment]
Agreeing with above comment, you can pass previous parameters like that when initalizing the clients. 

You can also use following documentation to configure clients participation in a federation by configuring the config values that are passed to the fit and evaluate functions. The `ClientManager` object can also be configured to achieve your desired outcome. 
https://flower.ai/docs/framework/how-to-configure-clients.html
https://flower.ai/docs/framework/main/zh_Hans/ref-api/flwr.server.ClientManager.html

closing this.
