### ISSUE TITLE
how to show the full args in task page?

### ISSUE THREAD

**Issue by MarkRushB** [adap/flower#3362]
### What is your question?

for my tasks, I have a large dict as payload, it is truncated by default, I just want to show it completely.

From document, I see we have a method called: [**format_task**](https://flower.readthedocs.io/en/latest/config.html?highlight=format_task#format-task), I tried this method but looks like the args has already been truncated before passing into this method. So I cannot make anything here.

Any idea on this? Thanks folks

**Comment by XiaobinZhao** [comment]
format_task just for template, the args of task already be truncated. You can set `argsrepr_maxsize` `kwargsrepr_maxsize` with the Celery instance, for example:
```
app = Celery(main=...,   backend=...,  result_backend=...)

app.amqp.argsrepr_maxsize = 102400
app.amqp.kwargsrepr_maxsize = 102400

```

**Comment by WilliamLindskog** [comment]
Hi @MarkRushB, 

Thanks for raising this. Are you still experiencing this issue?

**Comment by WilliamLindskog** [comment]
If I understand your question correct, you can print the context that is passed to server and client, using the `pyproject.toml` file that is required to run the new flwr versions. 

closing this issue.
