### ISSUE TITLE
Perform strategy in the sampled clients and its subset at the same time

### ISSUE THREAD

**Issue by raquelvaladao** [adap/flower#3402]
### What is your question?

Hello, I’m working on a baseline with a simulation.
I’d like to know if there’s a way to perform the aggregation to whe whole group of sampled clients as well as a subgroup of these clients. For example if I have 10,
- aggregation happens for all 10 and I get prime weights.
- At the same time for 5 with given criteria , I aggregate only them

Then I send to the last 5 the last aggregation, and for the previous 5 the full aggregation weights

would it have to do with changing the aggregate_fit and configure_fit? I thought it would have something to do with ClientProxy (to obtain the criteria from the client ) as well but couldnt figure out

**Comment by WilliamLindskog** [comment]
Hi

Thanks for raising this issue. Yes, this can be achieved by customizing the `aggregate_fit` and `configure_fit` methods in your strategy. Flower provides the flexibility to implement tailored aggregation logic, enabling you to send different weights to specific client groups. To do this, you can modify `aggregate_fit` to compute the aggregated weights for the entire group of sampled clients as usual. Then, you can identify a subgroup of clients based on specific criteria (e.g., metrics sent back by the clients) and perform a separate aggregation for this subgroup. Both sets of aggregated weights can be saved for later use.

In the `configure_fit` method, you can determine which set of weights to send to each client. For example, clients meeting the criteria for the subgroup can receive the subgroup-aggregated weights, while others receive the full-group aggregated weights. You can use the `ClientProxy` object or the results returned by clients to decide which group each client belongs to.

Closing this issue.
