### ISSUE TITLE
Method Doesn't Exist

### ISSUE THREAD

**Issue by Ziad-El3assal** [adap/flower#3406]
### Describe the bug

While runing the code of quickstart_sklearn the `to_client()` attribute doesn't exist in MNIST_client which inherit from `fl.client.NumPyClient`

### Steps/Code to Reproduce

![image](https://github.com/adap/flower/assets/84142720/5690a986-226c-4e2f-b1a1-a6c69d6b3821)

### Expected Results

The expected Result is the code to initiate the client but instead I got an error message.

### Actual Results

![image](https://github.com/adap/flower/assets/84142720/abc044fe-8b7b-4a6f-a743-a9f466582a10)

**Comment by Ziad-El3assal** [comment]
I found that the `to_client()` method is inherited from `flwr.client` not `flwr,client.NumPyClient` but tried to make my flower client inherit both classes it raised an issue about metaclass conflict.

**Comment by Omar1998Hassa** [comment]
I have the same issue

**Comment by Ziad-El3assal** [comment]
The problem was with the version of the installation in the source code it worked after installing flwr 1.9 not 1.4
