### ISSUE TITLE
How to solve hydra. errors Error reported for OverrideParseException: LexerNoViableAltException: \

### ISSUE THREAD

**Issue by QuinnLSY** [adap/flower#3466]
### What is your question?

I encountered a prompt while running Fedavgm saying "hydraulic. errors Error reported for OverrideParseException: LexerNoViableAltException: \". Refer to the documentation that indicates the use of escape characters for special characters during override, but I am unsure where these were used. How can I solve this problem? Thank you very much!

**Comment by jafermarq** [comment]
Hi @QuinnLSY , thanks for creating the issue. Could you share how you were running the baseline? Did you follow the setup steps outlined in the [Environment Setup](https://flower.ai/docs/baselines/fedavgm.html#environment-setup) section of the `FedAvgm` baseline?

**Comment by QuinnLSY** [comment]
I've solved this issue by reinstalling the environment. Thanks for the reminder!

**Comment by jafermarq** [comment]
perfect! I'll close the issue since it is now resolved. Let us know if you encounter any further issue. You can ask your question in the [Flower Discuss Forum](https://discuss.flower.ai/) if you prefer.
