### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#347]
Define and document the release process.

Topics include:
- Define how to manage releases (e.g., branching, tags, …)
- Document release note handling
- Document where (and how) build artifacts are published

**Comment by 4knahs** [comment]
Tags on releases would be very welcome, right now its hard to decide if one should update their flower version as one has to check commits and there is no changelog or description of updates.

**Comment by danieljanes** [comment]
@4knahs fully agree.

**Comment by danieljanes** [comment]
We've tagged the commit of the latest 0.10.0:

https://github.com/adap/flower/releases/tag/v0.10.0
