### ISSUE TITLE
Environment setup script

### ISSUE THREAD

**Issue by tanertopal** [adap/flower#348]
Create a convenience script which configures a fresh Ubuntu system so that a default coding environment is created. The Purpose is to ease the onboarding process for new contributors.

- Install / configure PyEnv
- Configure VSCode
- Install VSCode extensions
  - gRPC/protobuf
  - Python

Alternative ideas to evaluate:

- Visual Studio Code Remote - Containers.

**Comment by WilliamLindskog** [comment]
@tanertopal can we close?
