### ISSUE TITLE
New baseline: MNIST + FedAvg

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#352]
Create a new baseline for MNIST and FedAvg, as described in McMahan et al., 2017 (https://arxiv.org/abs/1602.05629):
- 100 partitions
- IID case and non-IID case
- Two-layer CNN

**Comment by danieljanes** [comment]
Flower Baselines documentation:
- https://flower.dev/docs/using-baselines.html
- https://flower.dev/docs/contributing-baselines.html

**Comment by tanertopal** [comment]
The baseline can now be found here:
* https://github.com/adap/flower/tree/main/baselines/flwr_baselines/publications/fedavg_mnist
