### ISSUE TITLE
Remove need for .flower_ops file

### ISSUE THREAD

**Issue by tanertopal** [adap/flower#353]
Currently when running the baseline we have to create a .flower_ops file to set various configs.We would like to remove the need for the config file as most of the settings in there could be automated.

The file contains

**Path configuration**
> [paths]
> wheel_dir = ~/some/path/flower/dist/
> wheel_filename = flower-0.3.0-py3-none-any.whl

Which could be automatically obtained by a lookup in the dist directory.

**AWS configs**
> [aws]
> image_id = ami-123456789
> key_name = flower
> subnet_id = subnet-123456
> security_group_ids = sg-123456789
> logserver_s3_bucket = my_s3_bucket_name

- Using the default VPC a subnet which has enough capacity to start the required number of instances could be automatically selected.
- key_name could default to flower OR the user could be asked if a new key named `flower` should be created/downloaded/locally made available.
- We could default to a security group named flower and again if it does not exit we could offer to create it.
-  logserver_s3_bucket not sure how to replace this.

> [ssh]
> private_key = ~/.ssh/my_private_key

Here we could default to a key named `flower`.

Finally all these are ideas/suggestions. If someone wants to tackle this we would be happy.

**Comment by WilliamLindskog** [comment]
Closing this.
