### ISSUE TITLE
Move datasets code for baselines into different repository/package

### ISSUE THREAD

**Issue by tanertopal** [adap/flower#354]
Currently the federated datasets for the baselines are generated on demand in [flwr_experimental/baseline/dataset](https://github.com/adap/flower/tree/main/src/flwr_experimental/baseline/dataset) and cached afterwards. The cache will be used if present. 
We would like to move the datasets code into a different repository named e.g. federated-datasets and host the generated datasets for everyone to load using the PyPi package which downloads and caches the datasets. Especially in case of bigger datasets each client in the federated baseline experiment doesn't have to download the whole (original) dataset so this would be a significant improvement.
It would be great if someone wants to tackle this task.

**Comment by WilliamLindskog** [comment]
flwr-datasets.
Closing this.
