### ISSUE TITLE
Bug in server_address (flower/examples/quickstart-pytorch/)

### ISSUE THREAD

**Issue by rociocarratalasaez** [adap/flower#3544]
### Describe the bug

Hi!

I am learning to use Flower and I have been playing around with flower/examples/quickstart-pytorch/
I found that the server_address (in server.py) is currently **server_address="0.0.0.0:8080".**
However, the server_address (in client.py) is currently **server_address="127.0.0.1:8080".**

Thus, when executing the test it fails, with a message like this:
grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:8080: connection attempt timed out before receiving SETTINGS frame"

To let the sample work, **the server_address in server.py should be server_address="127.0.0.1:8080"**

### Steps/Code to Reproduce

cd quickstart-pytorch
python3 server.py &
python3 client.py &
python3 client.py &

### Expected Results

From server.py:
INFO :      Starting Flower server, config: num_rounds=3, no round_timeout
INFO :      Flower ECE: gRPC server running (3 rounds), SSL is disabled
INFO :      [INIT]
INFO :      Requesting initial parameters from one random client
INFO :      Received initial parameters from one random client
INFO :      Evaluating initial global parameters
INFO :      
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 2 clients (out of 2)
INFO :      aggregate_fit: received 2 results and 0 failures
WARNING :   No fit_metrics_aggregation_fn provided
INFO :      configure_evaluate: strategy sampled 2 clients (out of 2)
INFO :      aggregate_evaluate: received 2 results and 0 failures
INFO :      
INFO :      [ROUND 2]
INFO :      configure_fit: strategy sampled 2 clients (out of 2)
INFO :      aggregate_fit: received 2 results and 0 failures
INFO :      configure_evaluate: strategy sampled 2 clients (out of 2)
INFO :      aggregate_evaluate: received 2 results and 0 failures
INFO :      
INFO :      [ROUND 3]
INFO :      configure_fit: strategy sampled 2 clients (out of 2)
INFO :      aggregate_fit: received 2 results and 0 failures
INFO :      configure_evaluate: strategy sampled 2 clients (out of 2)
INFO :      aggregate_evaluate: received 2 results and 0 failures
INFO :      
INFO :      [SUMMARY]
INFO :      Run finished 3 rounds in 20.06s
INFO :      History (loss, distributed):
INFO :      	('\tround 1: 360.64947509765625\n'
INFO :      	 '\tround 2: 346.9279022216797\n'
INFO :      	 '\tround 3: 300.2779541015625\n')History (metrics, distributed, evaluate):
INFO :      	{'accuracy': [(1, 0.1128), (2, 0.1883), (3, 0.3044)]}
INFO :   

From client.py:
INFO :      
INFO :      [RUN 0, ROUND ]
INFO :      Received: get_parameters message 8f06797d-1169-41a1-8107-54bd0e6597cf
INFO :      Sent reply
INFO :      
INFO :      [RUN 0, ROUND ]
INFO :      Received: train message 9959d750-74c2-4b16-8536-4600e2e149fc
Training: 100%|███████████████████████████████████████| 625/625 [00:05<00:00, 117.52it/s]
INFO :      Sent reply
INFO :      
INFO :      [RUN 0, ROUND ]
INFO :      Received: evaluate message aaf18405-b277-449d-bd65-b53f34c7dc5e
Testing: 100%|████████████████████████████████████████| 157/157 [00:00<00:00, 229.56it/s]
INFO :      Sent reply
INFO :      
INFO :      [RUN 0, ROUND ]
INFO :      Received: train message 80607d91-e0c3-4f11-b2d2-636e512a6804
Training: 100%|███████████████████████████████████████| 625/625 [00:05<00:00, 124.60it/s]
INFO :      Sent reply
INFO :      
INFO :      [RUN 0, ROUND ]
INFO :      Received: evaluate message 6b62fa54-88ff-494a-9527-f5107d175983
Testing: 100%|████████████████████████████████████████| 157/157 [00:00<00:00, 227.56it/s]
INFO :      Sent reply
INFO :      
INFO :      [RUN 0, ROUND ]
INFO :      Received: train message ec4e879f-7df1-4604-92bf-6c5f5628f09b
Training: 100%|███████████████████████████████████████| 625/625 [00:05<00:00, 123.33it/s]
INFO :      Sent reply
INFO :      
INFO :      [RUN 0, ROUND ]
INFO :      Received: evaluate message 4ac03f7b-306a-4f69-b116-e58d491bb753
Testing: 100%|████████████████████████████████████████| 157/157 [00:00<00:00, 227.52it/s]
INFO :      Sent reply
INFO :      
INFO :      [RUN 0, ROUND ]
INFO :      Received: reconnect message fcbd2075-19db-407f-99bf-aeef8e631570
INFO :      Disconnect and shut down

### Actual Results

From client.py:

Traceback (most recent call last):
  File "/Users/rocio/Test_Flower_FL/quickstart-pytorch/client.py", line 149, in <module>
    start_client(
  File "/opt/homebrew/lib/python3.9/site-packages/flwr/client/app.py", line 291, in start_client
    _start_client_internal(
  File "/opt/homebrew/lib/python3.9/site-packages/flwr/client/app.py", line 453, in _start_client_internal
    message = receive()
  File "/opt/homebrew/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 138, in receive
    proto = next(server_message_iterator)
  File "/opt/homebrew/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/lib/python3.9/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8080: connection attempt timed out before receiving SETTINGS frame"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-06-03T15:14:59.002451+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8080: connection attempt timed out before receiving SETTINGS frame"}"
>

**Comment by WilliamLindskog** [comment]
Hi @rociocarratalasaez, 

Thanks for raising this. Are you still experiencing this issue?

**Comment by WilliamLindskog** [comment]
Hi again,

The new version of flwr includes other mechanisms of running the same example: https://github.com/adap/flower/tree/main/examples/quickstart-pytorch

When running this, it works, thus I will close this issue.
