### ISSUE TITLE
Implement Secure Aggregation

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#356]
Secure aggregation [Bonawitz et al., 2017] is an important element of many FL workloads. We need to add a way to use secure aggregation within different strategies, ideally in a modular way (i.e., there is one secure aggregation implementation which can easily be plugged into different strategy implementations).

Paper: https://eprint.iacr.org/2017/281.pdf

**Comment by anik123** [comment]
Hi, 

Any update on this? 

Thanks in advance.

**Comment by Bhushankolpe** [comment]
> Hi,
> 
> Any update on this?
> 
> Thanks in advance.



> Secure aggregation [Bonawitz et al., 2017] is an important element of many FL workloads. We need to add a way to use secure aggregation within different strategies, ideally in a modular way (i.e., there is one secure aggregation implementation which can easily be plugged into different strategy implementations).
> 
> Paper: https://eprint.iacr.org/2017/281.pdf

sir the official implementation of secure aggregation is ready or not yet?

**Comment by rtaiello** [comment]
Hi @danieljanes  any updatas about Secure Aggregation? I've seen in docs: https://flower.dev/docs/secagg.html
But I can't find any tutorial/example. Thanks in advance.

**Comment by WilliamLindskog** [comment]
Currently exists: https://github.com/adap/flower/tree/main/examples/flower-secure-aggregation

Closing this issue.
