### ISSUE TITLE
JavaScript/TypeScript SDK

### ISSUE THREAD

**Issue by tanertopal** [adap/flower#358]
To support more heterogeneous environments/setups it would be great to have JavaScript/TypeScript Client SDK. The task shouldn't be to hard as [gRPC-Web](https://github.com/grpc/grpc-web) improved substantially. We are happy to support if someone wants to tackle this issue and ideally provide an example with e.g. TensorFlow Lite.
A potential use-case could be improving an image classification model as described in the [TF Lite docs](https://www.tensorflow.org/lite/guide/get_started#re-train_a_model_transfer_learning)

**Comment by WilliamLindskog** [comment]
@charlesbvll is this still relevant or can we close?

**Comment by charlesbvll** [comment]
As we have started working on this internally I will close this (old) issue
