### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ExifTags'

### ISSUE THREAD

**Issue by ajulyav** [adap/flower#3687]
### What is your question?

When running an example of examples/quickstart-pytorch, it shows the error of `AttributeError: module 'PIL.Image' has no attribute 'ExifTags'`
all dependencies are installed, i.e. tqdm==4.66.3,  PIL == 9.3.0
The error pops up at the line:  `for batch in tqdm(trainloader, "Training"):` `for batch in tqdm(testloader, "Testing"):`

**Comment by danieljanes** [comment]
This might be due to an old version of PIL, could you try installing PIL >= 9.4.0?

Related: https://github.com/huggingface/datasets/issues/6881
