### ISSUE TITLE
Constraints in the number of clients used.

### ISSUE THREAD

**Issue by gavryelmartis** [adap/flower#3703]
### What is your question?

Does the framework have any constraints on the number of clients used in parallel processing? 
I have over 200 clients and have implemented parallel processing to allow them to run simultaneously. I have noticed that with a smaller number of clients (fewer than 60), it runs successfully. However, when I increase the number of clients, they are unable to connect to the server.

**Comment by jafermarq** [comment]
Hi @gavryelmartis, Flower can handle parallel connections with clients. There is not a limit on how many can be handled as far as I know. I have run FL with flower involving 10K+ active clients w/o issue

What do you mean by: _"have implemented parallel processing to allow them to run simultaneously"_

**Comment by gavryelmartis** [comment]
Hi @jafermarq, I have attached a snippet of my code and here is the error message:

grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
status = StatusCode. UNAVAILABLE
details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8080: Fail
ed to connect to remote host: Connection refused"

<img width="813" alt="ss1" src="https://github.com/adap/flower/assets/60367753/d77dae2f-f13d-429f-a974-1f143eb041df">

**Comment by jafermarq** [comment]
maybe there are some limitations due to your machine ? Also bear in mind that what you are doing above very closely resembles what Flower's simulation engine does.

**Comment by WilliamLindskog** [comment]
Hi @gavryelmartis 

Thanks for raising this. Is this an issue that you are still experiencing? Please feel free to leave your comments here or close the issue if resolved.

**Comment by WilliamLindskog** [comment]
Hi again, 

I am closing this issue as the simulation using `flwr` can scale well beyond above mentioned number of clients.
