### ISSUE TITLE
Flower Server Question

### ISSUE THREAD

**Issue by Klein920116** [adap/flower#3822]
### What is your question?

Q1. If I wanna run two flower server on a machine, how should I do? Must use diffrent grpc port?
Q2. How can I stop flower server manually? It seems no any timeout param for users to stop server if there are some wrongs on client side.
Q3. How can I monitor the process of federated learning? Is there any interface can get the status of server and client?

**Comment by WilliamLindskog** [comment]
To run multiple Flower servers concurrently on a single machine using the `flwr run` command, you need to ensure that each `ServerApp` operates on a distinct gRPC port to prevent conflicts. This can be achieved by configuring each `ServerApp` with a unique port number. You can follow this [example](https://github.com/adap/flower/blob/main/framework/docs/source/docker/tutorial-quickstart-docker.rst) using Docker and choose the ports that should be used. 

To stop the Flower server manually, you can interrupt the process by pressing `Ctrl+C` in the terminal where the server is running. If the server is running as part of a script or within a container, you can use standard process management tools to terminate it:
- For a script, use a task manager (e.g., kill in Linux/macOS or Task Manager in Windows).
- For Docker, stop the container with:

```bash
docker stop <CONTAINER_ID>
```

You can also use Weights and Bias integration, or Prometheus and Grafana integration for visualization. 
- https://github.com/adap/flower/tree/main/examples/advanced-pytorch
- https://github.com/adap/flower/tree/main/examples/flower-via-docker-compose

Closing this issue for now.
