### ISSUE TITLE
Does Flower support several servers?

### ISSUE THREAD

**Issue by zzs97str** [adap/flower#3926]
### What is your question?

Traditional federated learning setups usually involve a single server and multiple clients. Does the Flower framework support multiple servers? These servers would receive parameters from their respective clients. After a certain number of rounds, aggregate the parameters from multiple server ends through averaging or other methods. Does Flower support several servers? I tried to search that but got nothing.

**Comment by WilliamLindskog** [comment]
Hi @zzs97str 

Thanks for raising this. The answer is yes, it requires setting up a deployment federation. You can do this using docker and specifying the ports on which the server listens. 

You can use this [example](https://github.com/adap/flower/blob/d7004b80de988a3fb2258067763ec78009326c33/framework/docs/source/docker/tutorial-quickstart-docker.rst) to instantiate several servers that work with various supernodes. 

Closing this issue for now.
