### ISSUE TITLE
ImportError: cannot import name 'ClientApp' from 'flwr.client'

### ISSUE THREAD

**Issue by nguyenhongson1902** [adap/flower#4008]
### Describe the bug

Hey folks, I've been trying out Flower recently and come up with the error when importing ClientApp
Here is the code:
`from flwr.client import ClientApp`
Here is the error:
`ImportError: cannot import name 'ClientApp' from 'flwr.client'`

My environment:
- Mac OS 14.5
- Python 3.10.10 (conda)
- flwr 1.4.0

### Steps/Code to Reproduce

1. Open Python in the terminal
2. Run `from flwr.client import ClientApp`

### Expected Results

The `ClientApp` should've been imported because there is a lot of tutorial-like source code that uses it.

### Actual Results

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ClientApp' from 'flwr.client' (/home/ubuntu/miniconda3/envs/pytorch-gpu/lib/python3.10/site-packages/flwr/client/__init__.py)
```

**Comment by jafermarq** [comment]
Hi @nguyenhongson1902 , please update to the latest version of Flower (`flwr 1.10.0`)

```bash
pip install -U "flower[simulation]"
```

**Comment by jafermarq** [comment]
Great! glad to hear it is fixed now 💯
