### ISSUE TITLE
execution of client example crash after training is terminated

### ISSUE THREAD

**Issue by altor** [adap/flower#408]
Hello !

I'm trying to use the example you provide ([quickstart](https://github.com/adap/flower/tree/main/src/py/flwr_example/quickstart) and [tensorflow](https://github.com/adap/flower/tree/main/src/py/flwr_example/tensorflow)). I achieve to train models but clients can't achieve to stop themselves without crashing.

I just run `run_server.sh` and `run_clients.sh` in separate terminals, see the clients downloading data and train their models. After training, the server evaluate the model ant stop itself properly.
At this moments, clients crash by rising an exception with this message : 

```
Traceback (most recent call last):
  File "client.py", line 114, in <module>
    main()
  File "client.py", line 110, in main
    fl.client.start_keras_client(args.server_address, client)
  File "/usr/local/lib/python3.7/dist-packages/flwr/client/app.py", line 47, in start_keras_client
    start_client(server_address, flower_client)
  File "/usr/local/lib/python3.7/dist-packages/flwr/client/app.py", line 35, in start_client
    server_message = receive()
  File "/usr/local/lib/python3.7/dist-packages/flwr/client/grpc_client/connection.py", line 59, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1601383903.613729459","description":"Error received from peer ipv6:[::]:8080","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Socket closed","grpc_status":14}"
```

**Comment by danieljanes** [comment]
Hi @altor - thanks for creating the issue! We are aware of this, the reason for this exception is that the current `Client`/`KerasClient` implementations do not implement a *graceful shutdown* when the server is done training. We'll soon release an update that fixes the issue :) until we do, if the server shows the final accuracy/loss logs, your workload ran successfully.

**Comment by altor** [comment]
Ok, For the moment, i'll just catch the exception and close the client properly
Thanks for your answer !

**Comment by danieljanes** [comment]
We'll update this issue once the change has landed.

**Comment by altor** [comment]
Thanks !

**Comment by danieljanes** [comment]
PR is ready: #449

**Comment by danieljanes** [comment]
PR is merged, graceful shutdown is available on branch main. New release will follow shortly.

**Comment by altor** [comment]
thanks !

**Comment by danieljanes** [comment]
@altor the new release 0.10.0 is now available on PyPI
