### ISSUE TITLE
（example）pytorch-from-centralized-to-federated  "Client program is stuck at the 'Sent reply' stage."

### ISSUE THREAD

**Issue by Saber-xxf** [adap/flower#4147]
### What is your question?

"Client program is stuck at the 'Sent reply' stage."    "Server side is also stuck."

![image](https://github.com/user-attachments/assets/004455f2-25de-47fa-ab0f-4ef90ae32527)
![image](https://github.com/user-attachments/assets/dde2dab7-d2a8-423b-b153-b30f8b54ac12)

**Comment by jafermarq** [comment]
Hi @Saber-xxf , thank you for creating the issue. Have you started two clients? By default the server expects two clients to be online before it can starts the round. You can change this behaviour by adjusting the `*_min_clients` arguments to the [FedAvg](https://flower.ai/docs/framework/ref-api/flwr.server.strategy.FedAvg.html) strategy.

However! I'd recommend you taking a look at newer examples that make use of the latest (much improved!) functionality in flower. In particular, take a look at: [examples/quickstart-pytorch](https://github.com/adap/flower/tree/main/examples/quickstart-pytorch)

**Comment by Saber-xxf** [comment]
Dear friend, thank you for your suggestion. I have indeed resolved the issue, which was caused by the minimum client setting being set to 2. Thanks again!

**Comment by jafermarq** [comment]
Great to hear!
