### ISSUE TITLE
Support for SMPC using secret sharing

### ISSUE THREAD

**Issue by petrosDemetrakopoulos** [adap/flower#4211]
## Security/Privacy Feature:
Secure Multi-Party Computation (SMPC) with Secret Sharing for Federated Learning

## Functionality
The proposed feature aims to enhance privacy and security in federated learning by implementing Secure Multi-Party Computation (SMPC) with secret sharing. This functionality will allow multiple clients participating in federated learning to securely share and aggregate their local model updates without revealing their individual data to any other party, including the central server.

The key functionalities of this feature include:
1. **Additive Secret Sharing Mechanism**: Each client can **split its local model update into multiple shares**, which are distributed among the other clients or securely sent to a central server. The shares are generated in a way that ensures the sum of all shares reconstructs the original update, but no single share reveals any meaningful information about the original data.
2. **Secure Aggregation Protocol**: The server aggregates the encrypted or masked shares from all clients to compute the global model update without learning the individual contributions from any client. This process ensures that the aggregation is secure and private, providing strong privacy guarantees even if the server is compromised.

## Step-by-step plan to implement the feature

1. **Create a new module**: (i.e. `src/py/smpc_secret_sharing.py`). This new module will contain the core logic for implementing the SMPC with secret sharing functionality. It will include:
- Functions for generating and distributing secret shares
- Methods for aggregating shares securely
- Helper functions for encryption, decryption, and secure communication between clients and server (if needed)

2. **Modify the existing**` strategy` module: The purpose of this modification is to Integrate the SMPC with secret sharing into the existing aggregation strategies. This modification will include the following steps:
- Add a new strategy class, `SecureAggregationStrategy`, that extends the FedAvg or another base strategy.
- Implement the `aggregate_fit` method using the secret sharing methods from the new `smpc_secret_sharing` module.

3. Update the `client` module: This modification will provide support for clients to generate shares of their local model updates and send them securely and includes the following steps:
- Add methods in the `NumPyClient` class or related client classes to support creating and sending shares to the server (e.g., `generate_and_send_shares`).

4. Update the `server` module: This is needed to adjust the server-side code to handle secure aggregation of model updates using secret sharing. This includes the following steps:
- Modify the server's logic to receive shares from clients and use the `SecureAggregationStrategy` for aggregating updates securely.
- Ensure the server correctly processes and aggregates encrypted shares.

5. Write tests
6. Update documentation

### Is there something else you want to add?

Nothing else to add

**Comment by panh99** [comment]
Hi @petrosDemetrakopoulos . We introduced the Secure Aggregation feature starting with `flwr 1.8.0`. Could you check out our [Secure Aggregation example page](https://flower.ai/docs/examples/flower-secure-aggregation.html)? Feel free to let me know if you need any additional features.
