### ISSUE TITLE
How I can add a header value like bearer token to client's request?

### ISSUE THREAD

**Issue by padrian2s** [adap/flower#4232]
### What is your question?

How I can add a header value like bearer token to client's request to act as m2m authentication. So I need only to add a value on request header.

**Comment by GabrieleLerani** [comment]
Hi there, in the documentation it is written that clients and server usually communicate with gRPC, so I don't think you can directly add the bearer token to the request header as in the traditional HTTP header. I suggest you to either implement an high level authentication strategy using the client configuration explained here [https://flower.ai/docs/framework/how-to-configure-clients.html](), or to adopt the built-in authentication: [https://flower.ai/docs/framework/how-to-authenticate-supernodes.html]().

Best of luck with your project.

**Comment by WilliamLindskog** [comment]
Hi 

Thank you for raising this. This problem seems to have been resolved with above comment. 

Will close this for now.
