### ISSUE TITLE
bug in flwr/common/config.py when replacing config args using --run_config

### ISSUE THREAD

**Issue by xiliguguagua** [adap/flower#4317]
### Describe the bug

flwr --run_config XXX won't work, the script still uses default args in pyporject.toml

line 185 in flwr/simulation/run_simulation.py:
`override_config = parse_config_args(
            [args.run_config] if args.run_config else args.run_config
        )`
- in parse_config_args(), the overrde_config is parsed and **toml.loaded**

line 100 in flwr/common/config.py:
`default_config = get_project_config(project_dir)["tool"]["flwr"]["app"].get(
        "config", {}
    )`
`flat_default_config = flatten_dict(default_config)`
`return fuse_dicts(flat_default_config, override_config)`
- in get_project_config(), the default_config is **toml.loaded** from dir
- but then **flattened**
- however override_config is **not flattened**
- so later in fuse_dicts(flat_default_config, override_config) the keys of them are not properly matched

line 105 in in flwr/common/config.py:
- change to:
- `flat_default_config = flatten_dict(default_config)`
- `flat_override_config = flatten_dict(override_config)`
- `return fuse_dicts(flat_default_config, flat_override_config)`
- will fix the bug

### Steps/Code to Reproduce

any command with ' --run_config XXX '

### Expected Results

config args being overrided

### Actual Results

not overrided, still the default args.

**Comment by jafermarq** [comment]
Hi @xiliguguagua , thanks for opening the issue? What version of flower are you using? Can you show a minimal example so I can reproduce the error? If I override the config as shown in the [examples/quickstart-pytorch](https://github.com/adap/flower/tree/main/examples/quickstart-pytorch) it seems to work just fine.

```
# override the default `num-server-rounds` from 3 to 5 and the `learning-rate` from 0.1 to 0.05
flwr run . --run-config "num-server-rounds=5 learning-rate=0.05"
```

Maybe you are not passing `--run-config "<your overrides here>"` correctly?

**Comment by xiliguguagua** [comment]
thanks for answering, I'm using the latest version 1.11.1
change the example in [examples/flowertune-llm](https://github.com/adap/flower/tree/main/examples/flowertune-llm)
from
`flwr run . --run-config "model.name='openlm-research/open_llama_7b_v2' model.quantization=8"`
to
`flwr run . --run-config "model.name='openlm-research/open_llama_7b_v2' model.quantization=-1"`

**Comment by xiliguguagua** [comment]
you need to use configs with '.'(XXX.XXX like 'model.quantization') to reproduce as it will be parsed into a following category when not flattened, and will not match with the one not flattened
args like 'num-server-round' with no '.' will lucky avoid the bug

**Comment by jafermarq** [comment]
@xiliguguagua  do you want to open a PR with the changes you propose? Let me loop in the meantime @yan-gao-GY (who created this example) and @charlesbvll (who designed the config system)

**Comment by xiliguguagua** [comment]
ok sure
