### ISSUE TITLE
examples/flower-authentication/Readme.md deprecated

### ISSUE THREAD

**Issue by cam-ai** [adap/flower#4326]
### Describe the bug

when i follow your readme, flwr v1.11.0 output errors like

- replace flower-client-app with flower-supernode
- replace argment --dir with --flwr-dir
- others, like server-app did not work, and did not know how to proceed.

### Steps/Code to Reproduce

Just follow readme
start supper-link
start client 1
start client 2
start server app

### Expected Results

if i followed the readme
i should start it successfully

### Actual Results

can't start it successfully

**Comment by jafermarq** [comment]
Hi @cam-ai , thanks for flagging this. Let me loop in @danielnugraha, he has been working on the auth logic recently
