### ISSUE TITLE
Training with Sample-Level Differential Privacy using Opacus Privacy Engine cannot be reproduced

### ISSUE THREAD

**Issue by Audris-A** [adap/flower#4328]
### Describe the bug

I followed the README instructions for running the [opacus example](https://github.com/adap/flower/tree/main/examples/opacus). When I ran the last command flwr returned the following information:

> It appears you've passed a reference like `server:app`. Note that since version `1.11.0`, `flower-server-app` no longer supports passing a reference to a `ServerApp` attribute. Instead, you need to pass the path to Flower app via the argument `--app`. This is the path to a directory containing a `pyproject.toml`. You can create a valid Flower app by executing `flwr new` and following the prompt.

### Steps/Code to Reproduce

Follow the instructions found in README.md.

### Expected Results

The Flower app successfully runs.

### Actual Results

The Flower app cannot be run.

**Comment by mohammadnaseri** [comment]
Hi @Audris-A , 

Thanks for opening the issue. The example is being updated and its [PR](https://github.com/adap/flower/pull/4262) will be merged soon. You can already try running the example using that PR.

**Comment by jafermarq** [comment]
Hi @Audris-A , the PR to update the example was updated. Let us know if it works as you'd expect. If not, please re open the issue and we'll look into it!

**Comment by Audris-A** [comment]
Seems like it is working as expected. However, maybe for the dependency install comand, the comment line should be moved out of the code block, otherwise the copy copies both the comment and the pip install command.

**Comment by mohammadnaseri** [comment]
@Audris-A Good point. Would you like to open a PR to fix that?

**Comment by Audris-A** [comment]
Here is the PR #4331.
