### ISSUE TITLE
Not able to run example in flwr_example/quickstart_pytorch

### ISSUE THREAD

**Issue by yinfredyue** [adap/flower#433]
I cannot run
```
$ ./src/py/flwr_example/quickstart_pytorch/run-server.sh
/usr/bin/python3: Error while finding module specification for 'flwr_example.quickstart_pytorch.server' (ModuleNotFoundError: No module named 'flwr_example.quickstart_pytorch')
```

But I can run the other example
```
$ ./src/py/flwr_example/pytorch/run-server.sh
```

**Comment by danieljanes** [comment]
Thanks for the report @yinfredyue , we're looking into it.

**Comment by tanertopal** [comment]
@yinfredyue We just made a new release 0.9.0. Could you please update and try it again?

**Comment by yinfredyue** [comment]
I am afraid the problem still exists.

**Comment by danieljanes** [comment]
@yinfredyue thanks for the feedback. How are you trying to run the script? Are you using the `flwr` package from PyPI or did you clone the GitHub repository?

**Comment by yinfredyue** [comment]
I cloned the repo.

I found the reason. The path in `run-server.sh` is wrong:

```
# Wrong:
# cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/../../../

# Correct
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/../../
```

Shall I create a PR to fix the issue?

**Comment by danieljanes** [comment]
Ah cool, yes, a PR would be great @yinfredyue

**Comment by tanertopal** [comment]
@yinfredyue we just checked the scripts. The `cd` statements are not relevant in these scripts. To avoid confusion in the future we are removing them.
The `python -m flwr_example.quickstart_pytorch.server` call should load the example server from your installed version of the Flower library.
There might be something we are not thinking of so maybe you could elaborate how you installed Flower?

**Comment by yinfredyue** [comment]
Yeah, you are right. Previously I was thinking it is loading files in `flwr_example/`.
I just tried it, indeed, changing `cd` is not relevant. But I did get errors (like in my first comment) when I ran it before.
I reinstalled `flwr` and it works.

Thank you!

**Comment by yinfredyue** [comment]
I re-examine the issue. Previously I get confused with `python -m` command. Apparently, it looks for local modules first, and if not found, global modules. For example, if we run `python -m flwr_experiemental.logserver.server`.
If we run in `flower/src/py/`, Python runs the local version, `flwr_experimental/logserver/server.py`, (which is what user of the framework want);
If we run in other directories, there's no module `flwr_experimental` in the current directory, then modules in the `flwr` package would be run. 
Currently most script uses `python -m`. I believe this would cause confusion to future users of flower (if they are not very familiar with python modules and packages).
