### ISSUE TITLE
Baseline creation documentation contains error

### ISSUE THREAD

**Issue by wittenator** [adap/flower#4366]
### Describe what the documentation is missing.

The section on usage with the new baselines format contains an error. It says that you can run a baseline with `flwr run . --run-config lr=0.01,num-server-rounds=200`, but in reality you have to use `flwr run . --run-config lr=0.01 num-server-rounds=200`. 

### Suggest your improvement.

Reading the documentation it is also not immediately clear how the configuration is supposed to work. I saw that the parameters are described in the pyproject.toml, but I think it would be helpful to make that a little clearer. I would also propose that the template already has configurations for the dataset where the name and the partitioner are configurable and the model can be instantiated like in the old Hydra baselines. This would probably result in people writing more configurable baselines in general.

**Comment by jafermarq** [comment]
Thanks @wittenator , a fix is on the way: https://github.com/adap/flower/pull/4387
