### ISSUE TITLE
examples/quickstart-pytorch: RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by zjh199683** [adap/flower#4384]
### Describe the bug

An error occurs when running quickstart-pytorch using GPU: 
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same.

### Steps/Code to Reproduce

def test(net, testloader, device):
    """Validate the model on the test set."""
    criterion = torch.nn.CrossEntropyLoss()
    correct, loss = 0, 0.0
    with torch.no_grad():
        for batch in testloader:
            images = batch["img"].to(device)
            labels = batch["label"].to(device)
            outputs = net(images)
            loss += criterion(outputs, labels).item()
            correct += (torch.max(outputs.data, 1)[1] == labels).sum().item()
    accuracy = correct / len(testloader.dataset)
    loss = loss / len(testloader)
    return loss, accuracy

### Expected Results

The model needs to be placed into the appropriate device.

### Actual Results

def test(net, testloader, device):
    """Validate the model on the test set."""
    net.to(device)
    criterion = torch.nn.CrossEntropyLoss()
    correct, loss = 0, 0.0
    with torch.no_grad():
        for batch in testloader:
            images = batch["img"].to(device)
            labels = batch["label"].to(device)
            outputs = net(images)
            loss += criterion(outputs, labels).item()
            correct += (torch.max(outputs.data, 1)[1] == labels).sum().item()
    accuracy = correct / len(testloader.dataset)
    loss = loss / len(testloader)
    return loss, accuracy

**Comment by jafermarq** [comment]
Hi @zjh199683, thanks for raising issue. It seems you have identified the bug: there is a missing 

```python
net.to(device)
```
in `test()` in `task.py`. Could you open a PR with the fix?

**Comment by zjh199683** [comment]
I've already opened it. Please check it.

**Comment by jafermarq** [comment]
Great! What did you do to run the simulation on gpu? did you adjust the federation in `pyproject.toml` to include something like this? Would it be useful to indicate this in the readme?

```
options.backend.client-resources.num-cpus = 2 # each ClientApp assumes to use 2CPUs
options.backend.client-resources.num-gpus = 0.2 # at most 5 ClientApp will run in a given GPU
```

**Comment by jafermarq** [comment]
Great! thanks for confirming. I've merged your PR. Do you think it would be useful for others to extend the README.md in the example and show how to run the example with GPU? What i'm thinking is to do the following:
- add a new federation to the `pyprojec.toml` (but leave the default federation unchanged so it run in CPU-only mode). 
- Indicate in the `README.md` how to use it. 

The idea would be to follow a bit how it is presented in https://github.com/adap/flower/tree/main/examples/flowertune-vit#run-with-the-simulation-engine (you can see first `flwr run .` uses CPU, but later `flwr run . local-simulation-gpu` would use the second federation with GPU settings. 

If you are interested in helping with the above, feel free to open a new issue or a PR directly. Thank you!
