### ISSUE TITLE
Update Exchange Time Metric

### ISSUE THREAD

**Issue by hayekr** [adap/flower#4425]
### What is your question?

Im looking to track parameter exchange time on a flwr system that is not simulated: Does the framework track communication time during model parameter exchange by default? If yes, which class/metrics can I access this from? If not, which specific methods should I track to measure the parameter exchange interval?

**Comment by WilliamLindskog** [comment]
Hi @hayekr, 

We've mods for computing message size and parameters' size. But not for parameter exchange time. However, in client_app.py, you can return a timestamp at the end of the `fit()` method like this:

```
from flwr.common import now
...
    def fit(self, parameters, config):
        model = get_dummy_model()
        return [model], 1, {"fit_time": now().isoformat()}
```
Then, in the server_app.py , we can pass a custom aggregation function to the `fit_metrics_aggregation_fn` of the strategy, like this:

```
def get_fit_metrics_aggregation_fn(fit_metrics):
        received_time = now().isoformat()
        total_num_examples = 0
        total_time_delta = 0
        for num_examples, metrics in fit_metrics:
            difference = datetime.fromisoformat(received_time) - datetime.fromisoformat(
                metrics["fit_time"]
            )
            total_num_examples += num_examples
            total_time_delta += difference.total_seconds() * num_examples

        weighted_time_delta = total_time_delta / total_num_examples

        return {"weighted_time_delta": weighted_time_delta}

# Define strategy
strategy = FedAvg(
     initial_parameters=dummy_parameters,
     fit_metrics_aggregation_fn=get_fit_metrics_aggregation_fn,  # <--- Add this
 )
```

The same can be done on for the eval() function, they would specify a similar function and pass it to `evaluate_metrics_aggregation_fn` of the strategy.
