### ISSUE TITLE
How to Implement Early Stopping strategy

### ISSUE THREAD

**Issue by asierzd** [adap/flower#4457]
### What is your question?

Hello everyone! 

I am doing a custom strategy with FedAVG as base strategy. 

I was wondering, if there is any way to implement an Early stopping for the strategy, making use of the Flower framework methods, I haven’t seen in the documentation anything related to this, neither how to stop the federated training process manually.

Thank you in advance!

**Comment by WilliamLindskog** [comment]
Hi @asierzd 

Thanks for asking your question here. To answer, here is a discussion with answers to your question. There is no direct way to do early stopping in Flower atm but there are work-arounds. I hope it helps. https://discuss.flower.ai/t/early-stopping-implementation/426/7

Closing this issue for now.
