### ISSUE TITLE
Rename `rnd` to `fl_round`

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#448]
`rnd` might be mistaken for *random*, thus we should perhaps rename it to `fl_round` (other suggestions are welcome)

Note: this would be an incompatible change.

**Comment by sisco0** [comment]
Should `current_round` be renamed to `fl_current_round` as well?
https://github.com/adap/flower/blob/8b9054866a46d0a41638a0a7ca9632b646eecea2/src/py/flwr/server/server.py#L166

**Comment by tanertopal** [comment]
@sisco0 Thank you for this! @danieljanes and I will discuss this PR as it will impact user facing APIs. Are you already on our Slack? Would be great to connect there too.

**Comment by danieljanes** [comment]
Released in Flower 1.0
