### ISSUE TITLE
Change strategy

### ISSUE THREAD

**Issue by yyin-dev** [adap/flower#456]
Is it possible to provide some documentation/tutorials on how to change/customize the training strategy? Thanks!

**Comment by danieljanes** [comment]
Yes, absolutely, this is one of our most pressing documentation issues: #340

Do you want to customize parameters of existing strategies or implement a fully custom strategy?

We're aware that the documentation doesn't explain those things yet, feel free to reach out via `contact@adap.com`, we'd be happy to help you in the meantime.

**Comment by yinfredyue** [comment]
I want to implement new strategies. I have browsed through the library code and have some rough ideas, but it still looks hard. I believe a tutorial/walkthrough would be great helps.
Just curious, when do you expect this documentation to be finished? :)

**Comment by danieljanes** [comment]
We might actually have a first version by the end of this week :)

**Comment by yinfredyue** [comment]
Thank you. Looking forward to that!

**Comment by danieljanes** [comment]
A first step towards better Strategy documentation is in #470, which improves the docstrings of the Strategy abstractions. All strategies are derived from this abstract base class, so hopefully the docstings help with implementing them.

**Comment by danieljanes** [comment]
Strategy documentation is making progress: #478

**Comment by danieljanes** [comment]
First step towards strategy documentation was merged: https://flower.dev/docs/strategies.html

**Comment by WilliamLindskog** [comment]
Current Flower version supports this: https://flower.ai/docs/framework/how-to-use-strategies.html. See as well baselines. 

Closing this issue.
