### ISSUE TITLE
Improve docstring for `Strategy`

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#464]

**Comment by pedropgusmao** [comment]
Are we sticking to a specific docstring style? I found a few [here](http://daouzli.com/blog/docstring.html) that we could choose from. I particularly like the Numpydoc.

**Comment by danieljanes** [comment]
Good question - we've never defined and documented the style we want to use for Flower, but you're right, we should pick one and declare it as the official style. It should be one that plays well with Sphinx to enable us to link to other parts of the codebase from the docstring itself. We've also started to use docformatter, so it would be good to pick a style that docformatter understands.

Perhaps it's best if we build a very small demo that showcases how a good docstrin in the format we pick looks like, how it can link to / mention other code fragments, and how docformatter itneracts with it. Would you like to take this topic @pedropgusmao ?

**Comment by danieljanes** [comment]
Btw, I like the Numpydoc style as well. We sometimes have rather involved type signatures, so it helps to have a dedicated line for that. We should also pick a style that makes it clear which parameters are optional and what their default values are.
