### ISSUE TITLE
Is there any Secured Aggregation implemented?

### ISSUE THREAD

**Issue by tushar-semwal** [adap/flower#468]

**Comment by danieljanes** [comment]
Hi @tushar-semwal , we haven't implemented it yet, but it's one of our top priorities. Would you be interested in contributing?

**Comment by tushar-semwal** [comment]
Unfortunately I am on limited bandwidth for a few months. Apologies @danieljanes.

**Comment by danieljanes** [comment]
No worries @tushar-semwal , I just mentioned it because we welcome contributions!

**Comment by WilliamLindskog** [comment]
Flower now supports [Secure Aggregation](https://github.com/adap/flower/tree/main/examples/flower-secure-aggregation). Closing this issue.
