### ISSUE TITLE
Improve website menu display 

### ISSUE THREAD

**Issue by pedropgusmao** [adap/flower#472]
Should we consider using a different theme structure for the menu in the website? Something like
```
Quickstrart
  |--Keras tensorflow
  |-- Pytorch
Installation
API
Examples
Cloud Usage 
```

And maybe a different Sphinx theme? I found this: https://sphinx-themes.org/

**Comment by danieljanes** [comment]
Yes, a better organization of the docs would be great. I'm also in favor of using a new theme if we find one that matches the style of the website.

**Comment by pedropgusmao** [comment]
Okay, I'm learning Sphinx to be able to modify it properly.

**Comment by tanertopal** [comment]
@pedropgusmao I just deployed a new theme with some fixes in the docs. Tracked here: https://github.com/adap/flower/issues/552

Checkout: https://flower.dev/docs

Does this resolve this issue? Do you think we can improve further?

**Comment by pedropgusmao** [comment]
That's a great new look for Flower!
