### ISSUE TITLE
FL and privacy preserving techniques

### ISSUE THREAD

**Issue by sidheek** [adap/flower#485]
Federated averaging is being mentioned in the paper but not much about secured aggregation. What all privacy preserving and FL techniques are implemented? 

Can the framework be deployed on institutions with different infrastructure? For example for healthcare institutions where the edge devices will be inside the institutions firewall.

**Comment by danieljanes** [comment]
Thanks for your question @sidheek . 

**Deployment** Flower clients can be deployed almost everywhere, which includes healthcare institutions and devices behind a firewall. We're planning to provide guides on how to do this, but in essence you just need to make sure that the client process can establish a connection to the server:

server.py:
```python
import flwr as fl
fl.server.start_server(
    server_address="[::]:8080",  # <-- server IPv6
    config={"num_rounds": args.rounds},
)
```

client.py:
```python
import flwr as fl
client = ...
fl.client.start_client(
    server_address="[::]:8080",  # <-- This needs to match the server IPv6 address, the client process needs to be able to connect to this address
    client=client,
)
```

Start the client on any device, for example, the device located inside the healthcare institutions insfrastructure:
```bash
python client.py
```

**Secure Aggregation** Secure Aggregation is not implemented yet, but it's one of our top priorities: #356 The Flower core framework does not make any assumption about the privacy-preserving techniques, you can use most techniques by implementing a strategy and matching client, which makes Flower compatible with future developments.

**Comment by WilliamLindskog** [comment]
Currently supports SA and DP. Closing this.
