### ISSUE TITLE
Server-side model parameter initialization

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#499]
The current server implementation uses the parameters of a single (random) client as the initial global model parameters. This works well for simple cases, however, some users require better control over model initialization (as discussed in #487).

Server-side model initialization could be provided via the `Strategy` abstraction.

Implementation proposal:

1. Add new `Strategy` non-abstract method called `initialize_parameters`
2. The default implementation would return `None` - if `None` is returned, the server will still sample the initial parameters from one of the connected clients
3. The user can override `initialize_parameters` to provide server-side parameter initialization
4. (Optional) built-in `Strategy` implementations can be configured via an `initialize_parameters_fn` that the strategy will call if provided

**Comment by pedropgusmao** [comment]
@danieljanes What if `Strategy` receives the model in the constructor and then we pass the `Strategy` to the Server` (as it is done now) so that the `Server` have access to the parameter via `Strategy`?

**Comment by danieljanes** [comment]
@pedropgusmao I like it - much simpler than the `initialize_parameters_fn` I proposed. @pedropgusmao @jafermarq @tanertopal please take a look at #658 , it's a first draft to enable server-side parameter initialization. It follows the idea outlined above, but I'll refactor it to pass the initial weights via the constructor instead of indirectly through a function.

It's a simple solution to have something working for now before we move to a more generalized solution (e.g., general-purpose callbacks or dedicated aggregators).

**Comment by danieljanes** [comment]
This has been resolved a while ago, closing
