### ISSUE TITLE
Implement baselines using LEAF datasets. 

### ISSUE THREAD

**Issue by pedropgusmao** [adap/flower#519]
It would be nice to have LEAF baselines ready for Strategy comparisons.

**Comment by WilliamLindskog** [comment]
@jafermarq @adam-narozniak do we want to support all LEAF datasets? https://leaf.cmu.edu/

Only find example for FEMNIST.

**Comment by adam-narozniak** [comment]
We support all besides the Reddit dataset. I couldn't find the raw version of this dataset anywhere on the internet.
(We have the femnist-based baseline, but it uses custom data loading, not flwr-datasets.)

**Comment by WilliamLindskog** [comment]
Closing this issue for now then.
