### ISSUE TITLE
grpc error: details: failed to connect to all addresses

### ISSUE THREAD

**Issue by lfzhagn** [adap/flower#537]
Hi, I was just trying the examples on [https://flower.dev/docs/example_walkthrough_pytorch_mnist.html](url). After runing  `bash ./run-clients.sh`, I got the following errors. Can someone provides any help? 
`$ DEBUG flower 2020-12-17 14:45:45,394 | connection.py:36 | ChannelConnectivity.IDLE
DEBUG flower 2020-12-17 14:45:45,394 | connection.py:36 | ChannelConnectivity.TRANSIENT_FAILURE
INFO flower 2020-12-17 14:45:45,394 | app.py:61 | Opened (insecure) gRPC connection
DEBUG flower 2020-12-17 14:45:45,410 | connection.py:36 | ChannelConnectivity.IDLE
DEBUG flower 2020-12-17 14:45:45,410 | connection.py:36 | ChannelConnectivity.CONNECTING
DEBUG flower 2020-12-17 14:45:45,410 | connection.py:36 | ChannelConnectivity.TRANSIENT_FAILURE
INFO flower 2020-12-17 14:45:45,410 | app.py:61 | Opened (insecure) gRPC connection
DEBUG flower 2020-12-17 14:45:45,597 | connection.py:68 | Insecure gRPC channel closed 
`
`Traceback (most recent call last):  
  File "E:\Anaconda3\envs\ptq\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Anaconda3\envs\ptq\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\envs\ptq\lib\site-packages\flwr_example\quickstart_pytorch\client.py", line 96, in <module>
    fl.client.start_client(args.server_address, client)
  File "E:\Anaconda3\envs\ptq\lib\site-packages\flwr\client\app.py", line 64, in start_client
    server_message = receive()
  File "E:\Anaconda3\envs\ptq\lib\site-packages\flwr\client\grpc_client\connection.py", line 60, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "E:\Anaconda3\envs\ptq\lib\site-packages\grpc\_channel.py", line 416, in __next__
    return self._next()
  File "E:\Anaconda3\envs\ptq\lib\site-packages\grpc\_channel.py", line 786, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1608187545.406000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1608187545.406000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"`

**Comment by lfzhagn** [comment]
issue solved by changing the ipv4 port.

**Comment by Samvid95** [comment]
Hey I am having the same problem. I tried changing the port. But it still having the same issue. Can you tell me what did you exactly change?

**Comment by Nada-Bu** [comment]
I have the same issue but after I changed port 5040 for both server and client, the FL worked fine.

**Comment by mahdibeit** [comment]
@lfzhagn  For me changing the [::] to localhost for both client and server side as follow worked:

`fl.client.start_numpy_client("[::]:8080", client=CifarClient())`
to
`fl.client.start_numpy_client("localhost:8080", client=CifarClient())`

**Comment by Glen909** [comment]
> issue solved by changing the ipv4 port.

hi can you show me how to change ipv4 port? thank you so much in advance

**Comment by kennyTheDev02** [comment]
> > issue solved by changing the ipv4 port.
> > @lfzhagn
> > hi can you show me how to change ipv4 port? thank you so much in advance

Hi, to my knowledge using 8080 is okay, I got it working using a Raspberry Pi 4 as a server and iMac as client. 

You can also refer to the answer to questions on failed to connected to all addresses from Eliasbrohammer's answer from issues #1212 on June 9, 2022

[https://github.com/adap/flower/issues/1212](url)
