### ISSUE TITLE
Evaluation of the final model on empty client set

### ISSUE THREAD

**Issue by NicholasRasi** [adap/flower#540]
Hello,
I'm trying to run the basic [Tensorflow Example](https://github.com/adap/flower/tree/main/examples/quickstart_tensorflow) but when the [final model evaluation is executed](https://github.com/adap/flower/blob/42ef63b6a8097c3b571b65e11b5471477253a48d/src/py/flwr/server/app.py#L97) the client returns an empty set, thus the evaluation is not executed.
This should be due to the fact that the server [closes the connections](https://github.com/adap/flower/blob/42ef63b6a8097c3b571b65e11b5471477253a48d/src/py/flwr/server/server.py#L117) with the clients after the fit.

Thank you

**Comment by danieljanes** [comment]
Thanks for the report @NicholasRasi ! What you're describing is right, good catch. We'll fix this asap.

**Comment by danieljanes** [comment]
This is fixed by #553 and will be available in Flower 0.13.0.
