### ISSUE TITLE
Communication implementation

### ISSUE THREAD

**Issue by yinfredyue** [adap/flower#541]
I am reading Flower code, and have this question: why Flower uses a queue (in `client/grpc_client/connection.py`) for server-client communication? Why Flower needs the `GRPCBridge` abstraction? Isn't gRPC itself enough?

I am still new to gRPC, so this question might be basic. Any help/explanation would be appreciated!

**Comment by danieljanes** [comment]
Hi @yinfredyue ,

Thanks for the question. Flower uses gRPC for client/server communication, but it's not inherently tied to it. This means that we could add additional transport mechanisms (e.g., WebSockets) in the future to enable workloads that have both gRPC-based and WebSockets-based clients. The `GRPCBridge` is one component that helps with this abstraction.

The queue on the client side might be temporary - Flower uses bidirectional streaming under the hood, so there's the possibility to replace the queue with something else to take full advantage of this. For the use cases we have right now the queue is enough though.
