### ISSUE TITLE
Flower CLI

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#557]
Projects that use one of the built-in strategies on the server-side without customizing them with callback methods still require the user to write a fairly simplistic `server.py` to start the server. It would be easier (especially for new users) if the server was available as a CLI command:

`flwr start-server`

Additionally, we could allow the user to specify the strategy and pass arguments to that strategy:

`flwr start-server --strategy=fedavg` (all FedAvg parameters left at their defaults)

`flwr start-server --strategy=fedavg --strategy-params="{fraction_fit=0.5, min_available_clients=10}"`

This would also allow us to simplify our quickstart guides.

**Comment by kushal-g** [comment]
I would like to take this up.

**Comment by WilliamLindskog** [comment]
current CLI documentation: https://flower.ai/docs/framework/ref-api-cli.html

Closing this.
