### ISSUE TITLE
Pytorch Lightning Example

### ISSUE THREAD

**Issue by tchaton** [adap/flower#564]
Dear people from Flower,

Would it be possible for you create an example with Pytorch Lightning.

Reasons: Pytorch Lightning is an advanced Training and I wonder how it could be leveraged from Federated Learning.

Best,
T.C

**Comment by danieljanes** [comment]
Hi @tchaton , we'd love to have a PyTorch Lightning example! Would you be interested in contributing?

**Comment by karthik1145** [comment]
I am interested in implementing this.
