### ISSUE TITLE
Migrate to `# pylint: disable=`

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#569]
Replace all comments of the form

`# pylint: disable-msg=...`

with

`# pylint: disable=...`

(the former is deprecated)

**Comment by zliel** [comment]
Hello, can I work on this?

**Comment by zliel** [comment]
Hello @danieljanes, can I work on this?

**Comment by danieljanes** [comment]
Hi @zliel, yes absolutely!

**Comment by zliel** [comment]
Thank you! Just finished up, if there's anything wrong with my PR please let me know!
