### ISSUE TITLE
Unify docstring style

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#575]
The repository does not enforce a particular docstring style yet. This can make it hard to know what style to use when editing docstrings. We should therefore:

1. [ ] Make a decision: which docstring style do we want to use?
2. [ ] Document this decision in our contributor guide
3. [ ] Migrate existing docstrings to this style
4. [ ] Check if there is tooling available to enforce this style on the CI

Criteria for choosing a docstring style:

- [ ] Is there tooling available to auto-generate/auto-format/lint docstrings?
- [ ] How readable is it with complex type signatures?

I believe @pedropgusmao looked into this before, would you like to comment on your findings?

**Comment by WilliamLindskog** [comment]
@danieljanes is this something that we can close?

**Comment by WilliamLindskog** [comment]
Closing this issue as it is enforced when opening PRs.
