### ISSUE TITLE
Testing | __init__.py check

### ISSUE THREAD

**Issue by CanTuerk** [adap/flower#581]
I have recently faced a problem in another repository, where `mypy` was all of a sudden throwing errors despite me not having changed a single line of code inside the file the errors were coming from. 
After a while I found out that the only thing wrong was a missing `__init__.py` file inside the directory.

To catch this issue early on in the CI I added the test which checks the Python directories for init.py files and allows adding directories which are exempt from the check.

I would suggest to integrate this script into the flower repository too as it could prevent annoying issues in the future.

**Comment by danieljanes** [comment]
Thanks for the issue @CanTuerk , I agree, we should do this.
