### ISSUE TITLE
Fix mypy / pytorch errors

### ISSUE THREAD

**Issue by tanertopal** [adap/flower#589]
# Description
We have disabled mypy for pytorch in https://github.com/adap/flower/blob/main/mypy.ini#L5-L7. As we would rather run it but it doesn't work especially on local we need to check regularly if it can be enabled again. This ticket is for the purpose of tracking it.

# Task
- [ ] Enable mypy for pytorch. Make sure it also works on your machine.

**Comment by WilliamLindskog** [comment]
@tanertopal should we close this?
