### ISSUE TITLE
E2E test for examples

### ISSUE THREAD

**Issue by tanertopal** [adap/flower#601]
# Description
Not all examples currently have a simple E2E test as seen in https://github.com/adap/flower/blob/main/.github/workflows/examples.yml

# Task
- [x] Create CI test for `examples/pytorch_from_centralized_to_federated`
- [x] Create CI test for `examples/simulation`

**Comment by danieljanes** [comment]
We should definitely add this, but please make sure that both tests only use the minimal amount of CI resources possible.
