### ISSUE TITLE
Differential Privacy

### ISSUE THREAD

**Issue by tanertopal** [adap/flower#605]
Differential Privacy is an important element of many FL workloads. The purpose of this issue is to track interest related to it. Please upvote this issue if you need a Flower-provided Differential Privacy solution for your FL setup.

**Comment by anik123** [comment]
Hi,

Any update on this?

Thanks in advance.

**Comment by giorgosera** [comment]
@tanertopal I am also interested in this.

**Comment by danieljanes** [comment]
@anik123 @giorgosera a first code example using DP SGD just got merged into main: https://github.com/adap/flower/tree/main/examples/dp-sgd-mnist

**Comment by giorgosera** [comment]
That's great news @danieljanes. Thank you!

**Comment by anik123** [comment]
wow. Thanks, @danieljanes . I will give it a try.

**Comment by bridgesra** [comment]
It appears that the `PRIVACY_LOSS` variable in this code is using basic composition (summing epsilon and summing delta) across all clients. Is that right? 

In many applications the clients require privacy, so one would perform privacy accounting per client. Further, for a large number of rounds, we may wish to use advanced composition theorems. Is there a privacy post-processing example that does this yet?

**Comment by WilliamLindskog** [comment]
Hi 

Thanks for all the comments and help. The mentioned example is not longer supported, there is extensive documentation and code example for using DP with Flower: 
- https://github.com/adap/flower/blob/c955c2767411da28ebb328f03bce74edd3539229/framework/docs/source/how-to-use-differential-privacy.rst
- https://github.com/adap/flower/tree/c955c2767411da28ebb328f03bce74edd3539229/examples/fl-dp-sa
and more. 

It is also possible to configure such strategies to perform privacy accounting per client. To configure advanced privacy accounting in Flower, define a custom strategy that tracks per-client privacy budgets by initializing a dictionary to store `epsilon` and `delta` for each client. Implement a method to update these budgets during training rounds by adding the current privacy loss to each client’s total. In the strategy’s `aggregate_fit` method, you can call this update function for all participating clients and log the updated budgets. If advanced composition is needed, integrate the logic directly into the privacy update method. Finally, initialize the custom strategy with desired privacy parameters (e.g., `epsilon`, `delta`, and `noise_multiplier`) and use it in your Flower server configuration.

Closing this issue for now.
