### ISSUE TITLE
Logo licensing.

### ISSUE THREAD

**Issue by roberthoenig** [adap/flower#608]
I use Flower for my dissertation.
I would like to include the Flower logo from flower.dev in one of my diagrams.

**Am I allowed to do this?** 
If so, should I provide any attribution?

**Comment by danieljanes** [comment]
Hi Robert, great to hear!

Yes, you are allowed to use the Flower logo in your dissertation. Please include a reference to `https://flower.dev`, thanks :)

**Comment by roberthoenig** [comment]
Great, thanks! I'll include the reference.
