### ISSUE TITLE
Unbundle `start_server` function

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#622]
The current `start_server` function follows a fixed recipe: train in a federated way (and perform either centralized or distributed evaluation along the way), reconfigure the strategy to enforce distributed evaluation, then evaluate the final model on *all* connected devices. There's also not meaningful return value, `start_server` just prints the progress logs. This approach is rather limiting and it only works like this for historic reasons.

A better approach would allow users to customize this behaviour, e.g., by returning a `Server` object from `start_server` and allowing the user to call `fit`/`evaluate`/etc. themselves in any order / any number of times. Additionally, `fit`/`evaluate`/etc. should have meaningful return values.

**Comment by WilliamLindskog** [comment]
Outdated. Closing this.
