### ISSUE TITLE
Changes in the return value of the evaluation of the clients

### ISSUE THREAD

**Issue by patselle** [adap/flower#632]
Hi, 

I want to return a string (to be exact a serialized dictionary) instead of len(x_test), loss, accuracy in the python file examples/quickstart_tensorflow/client.py, class CifarClient, in the evaluation method.<br>
I do this, for example, to give the server a unique client ID:
```
my_dict = {
'id': 'client_0',
'num_train': len(x_train),
...
}
```

So I changed in common/typing.py class EvaluateRes the types from<br>
```
num_examples: int
loss: float
accuracy: float  # Deprecated
```
to 
`my_dict: str`.

also i tried to adjust the code in the `flwr/client/numpy_client.py`, class `NumPyClientWrapper(Client)` like this
```
my_dict = cast(str, results)
return EvaluateRes(my_dict=my_dict)
```
and for len(results) == 2
```
results = cast(Tuple[str, Metrics], results)
my_dict, metrics = results
return EvaluateRes(my_dict=my_dict, metrics=metrics)
```
Finally I try to adjust the serde.py: evaluate_res_to_proto and evaluate_res_from_proto to
```
return ClientMessage.EvaluateRes(
    my_dict = res.my_dict,
    metrics=metrics_msg,
)
```
```
return typing.EvaluateRes(
    my_dict = msg.my_dict,
    metrics=metrics,
).
```

when running the code, I now get the following error on the client:
```
File ... common/serde.py", line 178, in evaluate_res_to_proto
ValueError: Protocol message EvaluateRes has no "my_dict" field.
```
apart from the code that needs to be changed in the `server.py`, I am afraid that I also need to make changes in `message_handle.py` and/or `transport_pb2.py`, this would be beyond my skills since I have no idea about binaerserialization. can you maybe help me there?

Thanks in advance

**Comment by danieljanes** [comment]
Hi @patselle , thanks for the question. What you're trying to do will be possible in the next release of Flower (0.14): you'll be able to return a dict containing (almost) arbitrary scalar values from both `fit` and `evaluate`. The release notes are here: https://flower.dev/docs/changelog.html (under the header "Unreleased").

You can test-drive the new features by installing Flower 0.14 nightly builds: `pip install flwr-nightly`. Would be great to get your feedback on the new features!

**Comment by patselle** [comment]
Hi @danieljanes,
I tried your note about the unreleased release notes and it worked fine.
Thank you

**Comment by danieljanes** [comment]
Thanks for the update @patselle , great to hear it works.

**Comment by WilliamLindskog** [comment]
Closing.
