### ISSUE TITLE
Update Quickstart PyTorch docs to 0.14 return values

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#650]

**Comment by mariaboerner1987** [comment]
The README does not require an update since it does not include an explanation of the fit and evaluate function. 
The client.py has also no explanatory comments within the code in order to keep it short. 
I can include it if you like. Otherwise I would keep it as it is. 
@danieljanes

**Comment by danieljanes** [comment]
@mariaboerner1987 this issue is not about the example, it's about the quickstart documentation: https://flower.dev/docs/quickstart_pytorch.html

**Comment by mariaboerner1987** [comment]
https://github.com/adap/flower/pull/652
