### ISSUE TITLE
Is there a way to synchronise models during epochs?

### ISSUE THREAD

**Issue by a1302z** [adap/flower#660]
Flower seems like a very promising framework, but I'm wondering though suppose you have a very large dataset, you'd like to synchronise and aggregate your models more frequently than just after every epoch, is there any way how this is currently possible? Unfortunately I did not see any.

**Comment by danieljanes** [comment]
Hi @a1302z , thanks for the question. What you're asking is easily possible, you can return the updated model parameters after any amount of training on the client.

Let me give an example using TensorFlow/Keras (it works exactly the same way for other frameworks, just train for a limited number of batches and return the updated weights):

```python
class CifarClient(fl.client.NumPyClient):
    def get_parameters(self):
        # ...

    def fit(self, parameters, config):
        # Update local model parameters
        self.model.set_weights(parameters)

        # Train the model for only three steps (= 3 batches)
        model.fit(x_train, y_train, epochs=1, steps_per_epoch=3)

        # Return updated weights after doing three steps
        return model.get_weights(), len(x_train), {}

    def evaluate(self, parameters, config):
        # ...
```

Furthermore, you can make this configurable from the server side using the `config` dict:

```python
class CifarClient(fl.client.NumPyClient):
    def get_parameters(self):
        # ...

    def fit(self, parameters, config):
        # Update local model parameters
        self.model.set_weights(parameters)

        # Get hyperparameters for this round
        num_steps: int = config["num_steps"]

        # Train the model using hyperparameters from config
        model.fit(x_train, y_train, epochs=1, steps_per_epoch=num_steps)

        # Return updated weights after training for `num_steps` batches
        return model.get_weights(), len(x_train), {}

    def evaluate(self, parameters, config):
        # ...
```

Feel free to take a look at the advanced TensorFlow example to see these components in a full project (check server.py to see how `num_steps` can be configured on the server side): https://github.com/adap/flower/tree/main/examples/advanced_tensorflow

**Comment by a1302z** [comment]
Thanks a lot
