### ISSUE TITLE
Cant Install flwr top of the Poetry Shell

### ISSUE THREAD

**Issue by sachugowda** [adap/flower#666]
i got error when i try to run install import flwr top of the poetry

ModuleNotFoundError: No module named 'flwr'

**Comment by tanertopal** [comment]
Hi @sachugowda. Can you maybe elaborate a little further and explain in which environment and how you installed Flower? Ideally provide some information about your system and the commands you have executed.

**Comment by sachugowda** [comment]
Dear @tanertopal , Thanks for your Reply.
i am using Ubuntu 18, and i have successfully installed Flower and cloned from github.
i cant install poetry and if i installed using https://python-poetry.org/docs/ i can used poetry command to start shell and i cant execute this command poetry run python3 -c "import flwr"

even i tried in google colab also.. kindly help me to run examples to learn more in FL

**Comment by sachugowda** [comment]
![Screenshot from 2021-03-08 17-06-20](https://user-images.githubusercontent.com/4860900/110316512-d9745f00-8030-11eb-92aa-4472b283bc24.png)
![Screenshot from 2021-03-08 17-07-25](https://user-images.githubusercontent.com/4860900/110316526-de391300-8030-11eb-9bcc-ee7fa48bde96.png)

**Comment by sachugowda** [comment]
![Screenshot from 2021-03-08 17-16-47](https://user-images.githubusercontent.com/4860900/110317393-1bea6b80-8032-11eb-8956-b275ffe58d39.png)

**Comment by sachugowda** [comment]
Thanks you, working fine

**Comment by ningxie1991** [comment]
> e commands you have exe

@sachugowda How did you resolve this? I am having the same issue.

**Comment by sauravtii** [comment]
How did you solve this @sachugowda ?
I am also facing the same issue.
