### ISSUE TITLE
Another possible funcionality

### ISSUE THREAD

**Issue by patselle** [adap/flower#693]
Hi Flower-Team,

first of all, thanks to the functionalities coming with release 0.14 and 0.15.
Another possible point I am thinking about:

I rewrote flower in a way that the server stores the global model (the model after averaging),  i.e. the last 5 models form the 5 last federated learning processes. 
The clients also store the last model they used in the last federated learning process they participated in locally.
So that they can then use it for interference, for example.

If a new federated learning process is started, the server sends the model parameters of the last federated learning process to the clients in the beginning of this process. 
However, this is often not necessary, since the clients may already have exactly these parameters.

Could it be possible, for example, that the clients send, i.e. the hash (obtained by hashing all model parameters) to the server when they log on to the server, and if these parameters correspond to the current parameters, the server does not send these model parameters to the clients at the start of the federated learning process?

Best Regards

Patrick

**Comment by danieljanes** [comment]
Hi @patselle, thanks for the proposal!

Most parts of this are already possible through custom strategy implementations: you'd include the hash of the current client-side parameters in the dictionary that the client returns back to the server (in `fit` or `evaluate`). The server-side strategy would then keep a map from client to parameter hashes and when a client gets samples for the next round, it'd compare the values in this dict to the current global parameters hash. If those weights are already present on a client, the strategy could just send empty weights and the hash to the client, and the client would then use the locally saved parameters.

The one thing we can add is a way to communicate these locally available weights/hashes when the client connects initially. There are actually plans to build a more generic version of this, namely a way for clients to send arbitrary values to the server with the initial connection request (the features is codenamed "handshake") - that way, the client could, for example, announce properties about itself to the server, and the server could sample based on these properties (e.g., sample only clients that have a GPU).

Does this help? Let us know if you attempt to implement this in a strategy, we could think about including it as a built-in feature for the existing strategy implementations at a later point.

**Comment by patselle** [comment]
Hi @danieljanes,

thank you for your response.
I will try this out.

**Comment by WilliamLindskog** [comment]
Closing this as it seems to have been resolved.
