### ISSUE TITLE
Running the server and clients on different machines

### ISSUE THREAD

**Issue by jaimish11** [adap/flower#697]
Is there any way to run a server on a separate machine (let's say a cloud instance like AWS EC2) and run clients locally?

I was able to run a federated training workflow locally (with both the client and server running locally) but when I tried to run the server on a different remote machine, my local client was unable to connect to it. Do you have any guidelines or help on how to connect local clients to a remote server? Specific IP address formats maybe?

This is important in terms of real-world benchmarks. If I want to know the performance of my model in a real-world setting, I would need to be able to do this. And if anyone is planning to run flwr in a production environment, this would be required. 

My setup details:
Server - Running on an AWS EC2 instance 
Client - Running locally
Problem - DNS resolution of the public IPv4 address of my EC2 instance

**Comment by tanertopal** [comment]
Hi @jaimish11 we have run setups with 10.000 clients on AWS distributed over 100 machines connecting to a single server. The functionality is already there.

Can you post your server code? If you want to use IPv4 you can use the server_address '0.0.0.0:8080' to listen on all addresses.

Apart from that make sure that port 8080 is publicly accessible by configuring the AWS EC2 security groups. To test that you could first start on the server machine a simple python HTTP server with `python3 -m http.server 8080`.

Let me know if this helped.

**Comment by jaimish11** [comment]
Hi @tanertopal. So it turns out, Nginx was unable to forward my requests to the federated server running on the EC2 instance. I had to ditch Nginx altogether and access the IP directly. That did in fact work. 

I was wondering what sort of server setup you used to handle multiple clients? Was it all routed through Nginx or did you handle it in another way?

**Comment by tanertopal** [comment]
You actually don't need anything else than the server. As we are using gRPC streaming for communication you might have to check if nginx supports that well. Especially your version of nginx. I am not sure tbh.

With regards to the server size on AWS that depends especially on the model size. I would recommend the server to have memory equal to MODEL_SIZE x NUMBER_OF_CONCURRENT_CLIENTS as when the models get aggregated that will be your memory peak usage.

Does this make sense?

**Comment by tanertopal** [comment]
@jaimish11 any updates on your side?
