### ISSUE TITLE
What is fraction_eval used for?

### ISSUE THREAD

**Issue by riccardo94p** [adap/flower#715]
Hello everyone, I am experimenting with this framework as part of my thesis. I was wondering what the `fraction_eval` parameter is meant for in the Strategy. The documentation states: "_Fraction of clients used during validation. Defaults to 0.1._"

If I understood correctly, the Strategy is on the server side. So if the train/test/validation data splits are in the client nodes, what is the purpose of this parameter?

I tried reading the source code but I couldn't figure this out. 
Thank you in advance to anyone who will find time to answer this.

**Comment by tanertopal** [comment]
@riccardo94p assuming you have 100 clients participating in the round the server will by default sample `NUMBER_OF_CONNECTED_CLIENTS * fraction_eval` number of clients for the evaluation step. Similar the `fraction_fit` will determine which fraction of clients will be sampled for the fit step.

**Comment by tanertopal** [comment]
@riccardo94p I am converting this to a discussion for now.
