### ISSUE TITLE
Example simulation docker execution fails

### ISSUE THREAD

**Issue by arnewitt** [adap/flower#747]
Hi all,

first of all, I am very impressed with your work! Looking forward to see how flower grows (pun intended) and maybe contributing, if I find time!

Regarding my issue, I am having trouble launching the docker container in the [basic simulation](https://github.com/adap/flower/tree/main/examples/simulation) using the command:

`
docker build -t flower_federated_learning_simulation .
`

I get the following output:

`
[+] Building 0.0s (1/2)                                                                                                                                                  
 => [internal] load build definition from Dockerfile                                                                                                                0.0s
 => => transferring dockerfile: 2B                                                                                                                                  0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount549581533/Dockerfile: no such file or directory
`

Kind regards

**Comment by arnewitt** [comment]
I have been able to resolve my issue: apparently there was something wrong with my docker installation, reinstalling docker fixed the issue.

Kind regards

**Comment by danieljanes** [comment]
Thanks for the update @arnewitt !
