### ISSUE TITLE
Client not starting

### ISSUE THREAD

**Issue by smsubham** [adap/flower#756]
Am getting the following error when I try to start client after server while trying to run the below example.

[pytorch_from_centralized_to_federated](https://github.com/adap/flower/tree/main/examples/pytorch_from_centralized_to_federated)

`Files already downloaded and verified
Files already downloaded and verified
DEBUG flower 2021-06-10 15:54:23,140 | connection.py:36 | ChannelConnectivity.IDLE
DEBUG flower 2021-06-10 15:54:23,140 | connection.py:36 | ChannelConnectivity.CONNECTING
DEBUG flower 2021-06-10 15:54:23,141 | connection.py:36 | ChannelConnectivity.TRANSIENT_FAILURE
INFO flower 2021-06-10 15:54:23,141 | app.py:61 | Opened (insecure) gRPC connection
DEBUG flower 2021-06-10 15:54:23,343 | connection.py:68 | Insecure gRPC channel closed
Traceback (most recent call last):
  File "client.py", line 98, in <module>
    main()
  File "client.py", line 94, in main
    fl.client.start_numpy_client("[::]:8080", client)
  File "C:\Users\HP\anaconda3\lib\site-packages\flwr\client\app.py", line 112, in start_numpy_client
    start_client(
  File "C:\Users\HP\anaconda3\lib\site-packages\flwr\client\app.py", line 64, in start_client
    server_message = receive()
  File "C:\Users\HP\anaconda3\lib\site-packages\flwr\client\grpc_client\connection.py", line 60, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "C:\Users\HP\anaconda3\lib\site-packages\grpc\_channel.py", line 416, in __next__
    return self._next()
  File "C:\Users\HP\anaconda3\lib\site-packages\grpc\_channel.py", line 689, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1623320663.140000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4134,"referenced_errors":[{"created":"@1623320663.140000000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>`
![image](https://user-images.githubusercontent.com/16716026/121510537-5edb2700-ca05-11eb-9d22-90c7fed7c863.png)

Python Version: 3.8.5
OS: Windows 10
RAM: 8 GB
Using conda base environment to run this.

**Comment by alessiomora** [comment]
I had the same problem on Windows. Just try to insert "localhost" instead of "[::]" in the address provided in the client and server code. That is:
[client.py] fl.client.start_numpy_client("localhost:8080", client=client)
[server.py] fl.server.start_server("localhost:8080", config={"num_rounds": HERE_YOUR_NUM_OF_ROUNDS}, strategy=strategy)
