### ISSUE TITLE
Federated Segmentation Example

### ISSUE THREAD

**Issue by mansiparashar** [adap/flower#770]
Hello, would it be possible to get documentation for running a segmentation task of Flower? Thank you!

**Comment by danieljanes** [comment]
Hi @mansiparashar , thanks for reaching out! We don't have an image segmentation example yet. If you have a particular image segmentation pipeline/project in mind we can help you to federate it using Flower (it should work pretty much the same way as it does for image classification and other tasks). Would you be interested in contributing such an example?

**Comment by mansiparashar** [comment]
Yes sure, I will take it up

**Comment by patselle** [comment]
Hi,

I am also working on different sematic segmentation tasks (u-net, deeplabv3) and can provide some examples in the near future.<br>
But I have already successfully tested flower on mask r-cnn (instance segmentation) and can provide the code for it.

Best regards
Patrick

**Comment by mansiparashar** [comment]
@patselle Hi,
That's really kind of you. Can we connect over slack, or can you mail me at contact.mansiparashar@gmail.com . 
Thanks!

**Comment by WilliamLindskog** [comment]
Hi, 

Thanks for raising this. Here's an example of how to use Flower for [medical image segmentation](https://www.youtube.com/watch?v=eeoLim3e7nk). Closing this issue for now.
