### ISSUE TITLE
Long time of training in a single round result in idle channel disconnection

### ISSUE THREAD

**Issue by venture2928** [adap/flower#775]
Hi, there. I am using the framework to implement my task, the task of a single round of training time is long. In the experiment I found that, the client will change the connection status of the channel to idle after ten minutes of training, resulting in disconnection, probably because no data is sent to the server, the server output the end of this round of training, tthe client can not send data to the server again after the actual training is completed.
Is there a way to extend the idle judgment time? Or is there a timed reconnection function?
Thanks a lot.

**Comment by tanertopal** [comment]
@venture2928 could you provide a bit more background information on your environment / system and ideally some code to replicate your issue?

**Comment by WilliamLindskog** [comment]
@venture2928 is this still an issue that you are facing?
