### ISSUE TITLE
Saving global weights at server side

### ISSUE THREAD

**Issue by rpittala-equinix** [adap/flower#777]
Hello, 
I am trying to implement saving of global weights and when i try to open the saved file, i see the weights are all encrypted.
How can i access and see the global weigths?

**Comment by patselle** [comment]
Hi,

if the weights are enrypted you probably have saved the parameters (binaries). You have to convert them back into weights:

```
def parameters_to_weights(parameters: Parameters) -> Weights:
    """Convert parameters object to NumPy weights."""
    return [bytes_to_ndarray(tensor) for tensor in parameters.tensors]
```
see `src/py/flwr/common/parameter.py `

Best Regards
