### ISSUE TITLE
set_parameters wrong

### ISSUE THREAD

**Issue by zhangboshi** [adap/flower#807]
Hello, when using the efficientnetb0 pre-training model, the joint training will stop at the position shown in the figure below, and the following error will be reported.
![image](https://user-images.githubusercontent.com/59415080/127867393-9591b26e-e0df-49f3-8f7d-869cd3fbe248.png)
![image](https://user-images.githubusercontent.com/59415080/127867469-9b6f244a-35a0-43af-a842-e3fd7af22767.png)

**Comment by wodeyoulai** [comment]
Hello,I have the same problem. Have you solved it？

**Comment by Nada-Bu** [comment]
I've faced the same problem too.

**Comment by zhangboshi** [comment]
I’m watching the fedBN example of flower official website.because your model has the 'bn' layer, the model parameters to numpy parameters will wrong
![image](https://user-images.githubusercontent.com/59415080/130625040-9c9e315a-3a63-4386-93b1-5033128812b9.png)
This official code gives the correct idea.server and client add like the next picture describe.
![image](https://user-images.githubusercontent.com/59415080/130626479-f20a1900-b7b9-4aaf-b0fc-078b72c70da4.png)

**Comment by zhangboshi** [comment]
> I've faced the same problem too.
