### ISSUE TITLE
Error: 'Sequential' object has no attribute 'set_weight'

### ISSUE THREAD

**Issue by Samvid95** [adap/flower#817]
So I am trying out Federated Learning on structured data and following this [dataset of German credit data](https://www.kaggle.com/kabure/german-credit-data-with-risk). I have a simple tensorflow based model and code. 

Here is my client class- 

```
class GCR_Client(fl.client.NumPyClient):
    def __init__(self, model, x_train, y_train, client_name):
        self.model = model
        self.x_train = x_train
        self.y_train = y_train
        self.client_name = client_name
    
    def get_parameters(self):
        return self.model.get_weights()
    
    def fit(self, parameters, config):
        self.model.set_weights(parameters)
        self.model.fit(self.x_train.values, self.y_train.values, epochs=15, batch_size=64)
        return self.model.get_weights(), len(self.x_train), {"Fit Data from":self.client_name}
    
    def evaluate(self, parameters, config):
        self.model.set_weight(parameters)
        return 0,0,{"Clinet Evaluation" : "Undefined", "Client Name":self.client_name}
```

In order to remove all the external factors I removed the code where I calculate the evaluation. 

Whenever I run the code with 1 server and multiple clients, I get error in the `def evaluate(self, parameters, config)` function. 
Error is `'Sequential' object has no attribute 'set_weight'`

`def fit(self, parameters, config):` method contains the same line but the error is only being generated from `evaluate` function only. I am not sure what's wrong with the code.

**Comment by danieljanes** [comment]
@Samvid95 thanks for reaching out. Could it be the missing `s`?

- `self.model.set_weights(parameters)` in `fit`
- `self.model.set_weight(parameters)` in `evaluate`

**Comment by Samvid95** [comment]
Hahaha I completely missed it. Thank you 

Now let me remove this question from the face of the internet. /s
