### ISSUE TITLE
iOS Client Example

### ISSUE THREAD

**Issue by jerrychen017** [adap/flower#843]
Hi there, I was wondering if you had any iOS client example using flower? Or a C++ version of flower? Thank you!

**Comment by danieljanes** [comment]
Hi @jerrychen017 , the first step towards an iOS SDK is in #838 (C++ SDK. Afaik, the people working on it develop it on Linux/Android for now, but iOS should (theoretically) work with zero or minor modifications. Please let us know if you're interested in contributing!

**Comment by jerrychen017** [comment]
Hi @danieljanes , thanks for pointing me to the right place! I will definitely take a look and let you know if I think I can make meaningful contribution!
