### ISSUE TITLE
Add flwr.__version__

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#883]
Having `flwr.__version__` will enable programmatic version checking, similar to how other libraries do it (e.g., `numpy`, `tensorflow`, `torch`, `torchvision`)

**Comment by sisco0** [comment]
Maybe the way to go for not duplicating the _Poetry_ version name is just the one specified in https://github.com/python-poetry/poetry/issues/144#issuecomment-623927302.

**Comment by sisco0** [comment]
We need to open a second step for this issue where we create a test for the version. Checking if `__version__` is a string is an option as pointed out in https://github.com/adap/flower/pull/952#pullrequestreview-840117791.

**Comment by tanertopal** [comment]
@sisco0 I added a simple test for it #967. We can successfully close this issue now.
