### ISSUE TITLE
Using get_properties()

### ISSUE THREAD

**Issue by sikhapentyala** [adap/flower#905]
I am testing a case where all the clients, before the start of FL fit rounds, communicate some information (Config:Dict[str,int]) to the server. The server collects the information from all the clients and generates new aggregated information. This new information should be shared with all the clients before they start fit rounds.

I am working with numpy_client. I have used it as follows:
-- Step 1: Generate the information, it will look as below
              info = {'k1':val, 'k2':val} before start the client. The values are generated based on the dataset
-- Step 2: Define the get_properties()  to return info in Client class based on numpy_client
-- Step 3: Start the client

For the server, I am not clear how the info from all clients can be captured and aggregated. For distribution of the aggregated info, I am defining on_fit_config where the config will have the aggregated info.

Given the above scenario,
1. Could you clarify how is get_properties used in the server?
2. Is the above correct approach?
3. Do you have any other suggestions for this preprocessing step.

Thanks

**Comment by danieljanes** [comment]
Hi @sikhapentyala - you're spot on, the new `get_properties` method is intended to be used for the idea you described above :)

It is, however, not quite finished yet. The main aspects of the new features have been merged into branch `main`, but the server doesn't call `get_properties` just yet (which is also why we haven't made a new major release yet).

If you're interested, we can ping you once we have a first usage example. We'd be curious to get feedback on the feature before we release it!

**Comment by sikhapentyala** [comment]
Hi @danieljanes, thank you for the details. 

I would appreciate any update when this feature is ready for use. 
I would be happy to test this feature!

**Comment by WilliamLindskog** [comment]
It is now available: https://github.com/adap/flower/blob/968fc774156e3371ad0c58c5f2638c04e3ab0144/src/py/flwr/client/client.py#L44

Closing this.
