### ISSUE TITLE
TypeError: Can't instantiate abstract class CifarClient with abstract methods get_properties

### ISSUE THREAD

**Issue by phleungae** [adap/flower#920]
I just did a clean installation using Anaconda3, running on Windows 10 64Bit. I assume that for my first trial, I do not need to modify the code and therefore I followed the installation instruction and quickly tried on "quickstart_tensorflow", "quicksart_Pytorch" and "advanced_tensorflow". But when I run "python client.py", all 3 examples shows the same error message as shown below.

![error](https://user-images.githubusercontent.com/62581563/144386346-b4efb4e2-77be-45c5-9f08-8ffc26c743c0.png)

I am quite new to programming and have never faced problem with abstract class and method. May I know what is happening here ? Thank you very much !

**Comment by dulicui** [comment]
I encountered the same problem as you and found the reasons are as follows:

1. The version of flwr installed through pip is 0.17.0(0.18.0 has not been released), there is no abstract methods get_properties for abstract class Client or NumPyClient;
2.  The code I debugged is 0.18.0, and examples in src/py/flwr_example are not updated I guess.
So, you can fall back to the version corresponding to the installed version to debug.

**Comment by makhanov-nu** [comment]
Can anyone have a solution for this problem? It's been 2 months since the issue was created.

**Comment by aayush9753** [comment]
I am encountering the same problem. @phleungae  @makhanov-nu Have you found any solution?

**Comment by danieljanes** [comment]
@aayush9753 @makhanov-nu @dulicui @phleungae sorry for the issue you were experiencing, there was a transition period where the code examples did not fully match the version released at the time.

Could you try again? With Flower 0.18 released everything should work as expected.
