### ISSUE TITLE
Add PyTorch checkpointing example to docs

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#922]
Add an example for saving PyTorch checkpoints to the docs. The code is here:

https://github.com/adap/flower/discussions/911#discussioncomment-1743210

The relevant docs are here:

https://flower.dev/docs/saving-progress.html

**Comment by ekaksher** [comment]
Hey, is this issue still open? If so I would like to work on it.

**Comment by gfmota** [comment]
Is it done? If so, can you close the issue?
