### ISSUE TITLE
Can't install app for Android Example

### ISSUE THREAD

**Issue by Victoria-Wei** [adap/flower#930]
Hi,

I want to perform federated learning with Android Clients, and I tired to run through the Flower Android Example in this repo. 
However, I failed to install the apk file on all 3 Android mobiles.
It says that `[INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`
Is there anything I can do to solve this problem?

**Comment by sisco0** [comment]
What is the current device you are trying to run this application in? The key is ensuring that third-party dependencies are available for your architecture.

**Comment by Victoria-Wei** [comment]
How to check if the third-party dependencies are available?

I tried on 
(1) HTC U11 with Kernel version,
```
4.4.153-perf-g66b46bd
and@AABM #1
SMP PREEMPT
```
, Baseband version of `8998-200321-1905141529`, and android version of 9

(2) HTC Desire 12s with Kernel version,
```
3.18.71-perf-g13ca675(gcc version 4.9.x
20150123(prerelease)(GCC))
jenkins@sh-16-201.rnd.longcheer.net #1
Tue Aug 11 10:52:57 CST 2020
```
, Baseband version of `953_GEN_PACK-1.181186.4.183606.3`, and android version of 8.1.0

(3) ASUS_Z017DA with Kernel version,
```
3.18.66-perf-gf957510
android@mcrd1-39 #1
Wed Sep 5 17:34:49 CST 2018
```
, Baseband version of `M3.10.47.19-Leo_080001`, and android version of 8.0.0

I'm not sure if the provided information is enough, since I'm not familiar with this.... If there is any information needed, please let me know.
Thank you!

**Comment by sisco0** [comment]
I would suggest compiling the project contained in the https://github.com/adap/flower/tree/main/examples/android/client folder by setting different splits so binaries for different platforms could be generated. For that purpose, we only need to append this configuration to 

```yaml
splits {
    abi {
        enable true
        reset()
        include 'x86', 'armeabi-v7a', 'x86_64'
        universalApk true
    }
}
```

Then, building the _APK_ newly could come up with a solution. But, just for getting to know better what are your target platforms based on, could you kindly run the next command and show the output under your hardware? ([Reference](https://handstandsam.com/2016/01/28/determining-supported-processor-types-abis-for-an-android-device/))

```bash
adb shell getprop ro.product.cpu.abilist
```

**Comment by Victoria-Wei** [comment]
Sorry for the late reply.... I was busy for the past few days. And thank you for your reply!!!

I don't know how to run the command `adb shell getprop ro.product.cpu.abilist` on my phone, so I downloaded an app that tells the command set (not sure what the actual English word for this is) the mobile uses.

2 of the above mobiles use arm64-v8a. (I didn't test the third one due to memory shortage) Therefore, I appended the following configuration to build.gradle under the app folder like you said.
```
splits {
    abi {
        enable true
        reset()
        include 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
        universalApk true
    }
}
```
( I found out later that I could simply include 'arm64-v8a' to build the desired APK. From the above configuration, it will build different APKs for different "command sets" if I understand it correctly.)

The APK built with 'arm64-v8a' can be installed successfully on both mobiles. Both of them seem to be running, even with Android version =  8.1.0. I will then take a closer look at what the app is doing exactly and how.

Thank you for all your assistance!! It is really a huge help for me!!!! 
Thank you again and Merry Christmas~~

**Comment by sisco0** [comment]
`adb` command could be run by connecting the devices by using USB to your computer, it is like the shell login for debugging (ADB = Android Debugging).

Great to know about the issue being solved by using the specific target architecture. This issue could be closed.

**Comment by Victoria-Wei** [comment]
Thank you again for your help!
