### ISSUE TITLE
Examples not installing the correct version of Ray

### ISSUE THREAD

**Issue by pedropgusmao** [adap/flower#936]
When running a simulation example, the install procedure installs ray==1.9.0

```
git clone --depth=1 https://github.com/adap/flower.git && mv flower/examples/simulation_pytorch . && rm -rf flower && cd simulation_pytorch 
poetry install
poetry shell
python
import ray
print(ray.__version__)
```
If the line in https://github.com/adap/flower/blob/715d029422773031a14a6044e31590f6d6f75640/examples/simulation_pytorch/pyproject.toml#L16 is uncommented and the line above it is commented, then the expected behavior (ray==1.6.0) is obtained (if we just clone the repo and do not delete it, of course). 

I think this is due to Poetry not being able to correctly find `["simulation"]` or due to `["simulation"]` not containing any `ray` version. If we remove the parent directory (`flower/`), how can the example `pyproject.toml` know the definition of `["simulation"]`. Should it get it from PyPI?

**Comment by sisco0** [comment]
The latest `ray` version is used as it could be seen by running `poetry install -vvv`. This behavior is the expected one from the _Poetry_ package, as it is already detecting an `import ray` under the `main.py` file.

The linked `../../` path is not accessible after running the `rm -rf flower` command in the first line of the shared _Bash_ script, so we would fail on fixing these extras. There would be two alternatives here:

1. Do not `rm -rf` any directory and perform the _comment_/_uncomment_ procedure as you did successfully.
2. Add the same extras (duplicate code, which is not always a good option) to this `pyproject.toml` under `examples/simulation_pytorch`.

**Comment by pedropgusmao** [comment]
I really like the idea of having a hierarchical poetry system tbh, but I guess Examples were also meant to be used in a stand-alone fashion i.e. if you already have Flower you don't have to build it. @tanertopal @danieljanes any thoughts?

**Comment by danieljanes** [comment]
The reason for this behaviour is the following: back in the 0.17 release, the Ray dependency was specified as [`^1.6.0`](https://github.com/adap/flower/blob/d963b39ff191164654b659e0e3a72aeef8cc3480/pyproject.toml#L67), so Poetry installs the latest version (which is `1.9.1`).

Workarounds:
- Try to install Ray 1.6 manually, then run the example install as mentioned above (IIRC, this should keep Ray at 1.6) --> this is probably the easiest thing to try
- Install `flwr-nightly` (note: there are a few breaking changes to be aware of, for example, the required `get_properties` method)
- Install Flower from branch [`release/v0.17`](https://github.com/adap/flower/tree/release/0.17) (it's basically `0.17` with two additional Ray-related cherry-picks, the version fix amongst them)
- Wait for 0.18
