### ISSUE TITLE
Add FedNova baseline

### ISSUE THREAD

**Issue by danieljanes** [adap/flower#943]
FedNova paper: https://arxiv.org/pdf/2007.07481.pdf

**Comment by sisco0** [comment]
Is a new `fednova.py` file expected to be created with its corresponding `fednova_test.py` test file under `src/py/flwr/server/strategy` for solving this issue?

**Comment by danieljanes** [comment]
Flower Baselines are a separate from the built-in strategies, here's how to contribute: https://flower.dev/docs/contributing-baselines.html

**Comment by jafermarq** [comment]
Closing this since `FedNova` has been implemented as part of _Summer of Reproducibility_: https://github.com/adap/flower/tree/main/baselines/fednova
