### ISSUE TITLE
FL starting but no progress!

### ISSUE THREAD

**Issue by fahim17pk** [adap/flower#955]
Hi, I am running pyTorch CIFAR-10 Example. I make the environment and change the server and client file with localhost:8080. It start but went to some infinite loop. No error message to find the mistake. 

**Server side messages:**
INFO flower 2021-12-22 15:06:15,217 | app.py:77 | Flower server running (insecure, 1 rounds)
INFO flower 2021-12-22 15:06:15,218 | server.py:118 | Initializing global parameters
INFO flower 2021-12-22 15:06:15,219 | server.py:304 | Requesting initial parameters from one random client
INFO flower 2021-12-22 15:06:24,682 | server.py:307 | Received initial parameters from one random client
INFO flower 2021-12-22 15:06:24,683 | server.py:120 | Evaluating initial parameters
INFO flower 2021-12-22 15:06:24,684 | server.py:133 | FL starting

**Client side messages:**
DEBUG flower 2021-12-22 15:06:24,674 | connection.py:36 | ChannelConnectivity.IDLE
DEBUG flower 2021-12-22 15:06:24,676 | connection.py:36 | ChannelConnectivity.CONNECTING
INFO flower 2021-12-22 15:06:24,676 | app.py:61 | Opened (insecure) gRPC connection
DEBUG flower 2021-12-22 15:06:24,676 | connection.py:36 | ChannelConnectivity.READY

**Comment by fahim17pk** [comment]
Hi again! I just find if you initiate 2 client then it works and 0 failure. I think some issue of indexing for just one client.

**Comment by DrishyaRaj** [comment]
Hi I have the same issue, Could you please explain how did you solve this ?
