### ISSUE TITLE
Error when converting model to .tflite

### ISSUE THREAD

**Issue by ramireguilherme** [adap/flower#956]
Hello @akhilmathurs ,
I'm trying to run the_tflite.py for the example provided on https://flower.dev/blog/2021-12-15-federated-learning-on-android-devices-with-flower
I'm getting the following error:
`flower/examples/android/android/tflite_convertor/tfltransfer/heads/keras_model_head.py", line 51, in __init__
    input_def = next(self._predict_signature.inputs.values().__iter__())
AttributeError: 'list' object has no attribute 'values'
`
I didn't do any modifications, how can I solve this issue?

**Comment by sisco0** [comment]
The error seems related to a breaking change on export functions from _Tensorflow_. You could find more information at https://github.com/tensorflow/tensorflow/issues/45949#issuecomment-817198226. The proposed solution is at using another _Tensorflow_ version.

**Comment by tanertopal** [comment]
@ramireguilherme @sisco0 can you confirm if the fix in #1001 works for you?

**Comment by ramireguilherme** [comment]
@tanertopal  Thank you! That fixed the issue. I was able to run the example and convert to .tflite format.
