### ISSUE TITLE
Accessing global model parameters into custom strategy file

### ISSUE THREAD

**Issue by shubham-malaviya** [adap/flower#991]
For example, let say custom strategy is `class FedCustom(flwr.server.strategy.FedAvg):`  ,then is it possible to access global model parameters into function like `aggregate_fit() `?

**Comment by sisco0** [comment]
`aggregate_fit` is already defined as an Strategy class internal function, so we could access all members from the Strategy class from it by prepending `self.` without inconvenience. If you want to access the `Server` instance model parameters at the `aggregate_fit` function you could do so just by using the `parameters` parameter from this function, as this is already set to `self.parameters` in its call. I attach the corresponding related source code.

https://github.com/adap/flower/blob/415ec559ab6fa5b48a8bad99dbf52ce5b58ac538/src/py/flwr/server/server.py#L145
https://github.com/adap/flower/blob/415ec559ab6fa5b48a8bad99dbf52ce5b58ac538/src/py/flwr/server/server.py#L121
https://github.com/adap/flower/blob/415ec559ab6fa5b48a8bad99dbf52ce5b58ac538/src/py/flwr/server/strategy/fedavg.py#L170-L172

Could you kindly provide at what function are you required to query the `Server` `self.parameters` values?

**Comment by shubham-malaviya** [comment]
> 

Thanks @sisco0 . I wanted to access previous round's global parameters into the `aggregate_fit` function. Previously I set the `self.server_parameters` into `aggregate_fit` itself, but your approach of setting it into `configure_fit` is more convenient. 

Thanks again!
